-- 20 Post-UTME History Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('history','ALL','The "Scramble for Africa" and the subsequent partition of the continent among European powers was formalised at:','The Treaty of Berlin, 1885','The Congress of Vienna, 1815','The Treaty of Versailles, 1919','The Brussels Conference, 1890','A','The Berlin Conference (1884–1885), convened by Otto von Bismarck, established the rules for European colonisation and partition of Africa — the formal starting point of the Scramble for Africa.'),

('history','ALL','The trans-Atlantic slave trade is estimated to have forcibly transported approximately how many Africans to the Americas between the 15th and 19th centuries?','1–2 million','5–8 million','12–15 million','25–30 million','C','Scholarly estimates, including those from the Trans-Atlantic Slave Trade Database, put the number of enslaved Africans transported to the Americas at approximately 12–12.5 million over the entire trade.'),

('history','ALL','The Sokoto Caliphate, established following the Fulani Jihad, was founded by:','Usman dan Fodio in 1804','Muhammad Bello in 1817','Al-Hajj Umar Tall in 1852','Rabih az-Zubayr in 1893','A','Usman dan Fodio launched the Fulani Jihad in 1804 and established the Sokoto Caliphate — the largest state in sub-Saharan Africa at the time — transforming the political and religious landscape of the Western Sudan.'),

('history','ALL','The "indirect rule" system of colonial administration in Nigeria was most closely associated with:','Frederick Lugard, who institutionalised it after the conquest of Northern Nigeria','Herbert Macaulay, who championed it in Lagos Colony','Lord Milner, who applied it across British Africa','Cecil Rhodes, who first used it in Southern Africa','A','Frederick Lugard (Governor-General) systemised and theorised indirect rule in Northern Nigeria, later applying it across Nigeria and articulating it in "The Dual Mandate in British Tropical Africa" (1922).'),

('history','ALL','The "Atlantic Charter" of 1941, signed by Roosevelt and Churchill, is significant in African history because:','It formally ended World War I and established the League of Nations','Its principle of self-determination for all peoples provided moral ammunition for African nationalist movements after World War II','It established the boundaries of British and American spheres of influence in Africa','It agreed to return all European colonies to their original populations','B','The Atlantic Charter''s clause on the right of peoples to choose their own government was seized upon by African nationalists (including Nnamdi Azikiwe and Kwame Nkrumah) as supporting the case for self-determination and independence.'),

('history','ALL','The Zulu kingdom reached its greatest power and military effectiveness under which leader?','Shaka (c.1816–1828)','Cetshwayo (1872–1879)','Dingane (1828–1840)','Mpande (1840–1872)','A','Shaka revolutionised Zulu military organisation — introducing the ibutho (regiment) system, the short stabbing assegai (iklwa), and the encircling "bull horn" battle formation — building the Zulu into the dominant power in southeastern Africa.'),

('history','ALL','The "Mfecane" (also called Difaqane in Sotho) of the early 19th century refers to:','The forced migration of Boers from the Cape Colony into the interior (the Great Trek)','A period of widespread warfare, migration, and state formation triggered largely by the rise of the Zulu kingdom in southeastern Africa','The wars between British forces and the Zulu kingdom in 1879','The spread of Islam across the Western Sudan through jihad','B','The Mfecane (c.1815–1840) was a period of intense inter-group conflict and mass migrations across southern and central Africa, causing enormous demographic disruption and the formation of new states — traditionally linked to Shaka''s Zulu expansionism.'),

('history','ALL','Nigeria attained independence from Britain on:','1st October 1960','1st October 1963','1st January 1960','12th April 1961','A','Nigeria became independent from British colonial rule on 1 October 1960, with Abubakar Tafawa Balewa as the first Prime Minister. Nigeria became a republic within the Commonwealth on 1 October 1963.'),

('history','ALL','The first Pan-African Congress was convened in 1900 in London primarily through the efforts of:','W.E.B. Du Bois','Marcus Garvey','Booker T. Washington','Henry Sylvester Williams','D','Henry Sylvester Williams, a Trinidadian barrister, organised the first Pan-African Conference in London in 1900. W.E.B. Du Bois attended and became the dominant figure in subsequent congresses.'),

('history','ALL','The "Abyssinia Crisis" of 1935–1936, in which Italy invaded Ethiopia, was significant because:','It demonstrated the effectiveness of the League of Nations in stopping aggressor states','It exposed the failure of the League of Nations to enforce collective security, accelerating its collapse','It led directly to the outbreak of World War II','It resulted in Ethiopia becoming an Italian colony for 50 years','B','Mussolini''s invasion of Ethiopia (Abyssinia) and the League of Nations'' failure to impose effective sanctions demonstrated the League''s impotence — undermining confidence in collective security and emboldening Hitler.'),

('history','ALL','The concept of "Négritude" in African intellectual history was co-founded by:','Kwame Nkrumah and Jomo Kenyatta','Léopold Sédar Senghor and Aimé Césaire','Frantz Fanon and Albert Memmi','Julius Nyerere and Kenneth Kaunda','B','Négritude was a literary and intellectual movement founded in Paris in the 1930s by Léopold Sédar Senghor (Senegal), Aimé Césaire (Martinique), and Léon-Gontran Damas (French Guiana) — celebrating African cultural identity in resistance to French assimilation.'),

('history','ALL','The "Berlin Conference" of 1884–1885 established which key principle regarding the colonisation of Africa?','European powers must first consult African rulers before claiming territory','The principle of "effective occupation" — a power must actually occupy and administer a territory to have its claim recognised','All of Africa south of the Sahara was allocated to Britain and France','European powers must purchase African territory from its inhabitants','B','The Berlin Conference established "effective occupation" as the criterion for valid territorial claims — requiring a power to demonstrate actual administration (not mere coastal presence) to prevent other European states from contesting the claim.'),

('history','ALL','The Egyptian nationalist revolution of 1952, which ended the monarchy, was led by:','Gamal Abdel Nasser and the Free Officers Movement','King Farouk I','Anwar Sadat alone','The Muslim Brotherhood','A','The Free Officers'' coup of July 1952 (led by Muhammad Naguib with Nasser as the dominant figure) ended King Farouk''s reign. Nasser became President in 1954 and led Egypt''s Arab nationalist revolution.'),

('history','ALL','The "Groundnut Pyramids" of Kano were historically significant because they symbolised:','The failure of agricultural policy in Northern Nigeria','Northern Nigeria''s leading role as a major producer and exporter of groundnuts (peanuts), which dominated the regional economy during the colonial era','The waste of agricultural resources by colonial administrators','A colonial policy of forcing farmers to grow cash crops under threat of punishment','B','Kano''s groundnut pyramids — enormous stacks of sacks awaiting export — were a symbol of Northern Nigeria''s booming groundnut economy during the colonial period, when Nigeria was one of the world''s largest groundnut exporters.'),

('history','ALL','The Nigerian Civil War (1967–1970) was triggered by:','A border dispute between Nigeria and Cameroon over oil resources','The declaration of secession by the Eastern Region as the Republic of Biafra, following inter-ethnic violence and the failure of the Aburi Accord','A military coup by northern officers against an Igbo-led government','A dispute over revenue allocation between the federal government and the Eastern Region','B','After the 1966 coups, massacres of Igbos in the north, and the failure of the Aburi peace accord, Lt. Col. Odumegwu Ojukwu declared the independent Republic of Biafra on 30 May 1967, triggering the 30-month civil war.'),

('history','ALL','Which of the following was a major consequence of the 1884–1885 Berlin Conference for African peoples?','African kingdoms gained formal recognition and representation in European diplomacy','African ethnic groups, kingdoms, and communities were divided arbitrarily by straight-line colonial borders that ignored pre-existing political and social structures','African slave trade was finally abolished across the continent','African rulers were compensated for lands taken by European powers','B','The Berlin partition drew artificial straight-line borders cutting across pre-existing African kingdoms, ethnic communities, and trade networks — creating colonial states that grouped rivals together and divided related peoples, with consequences that persist to the present.'),

('history','ALL','The "Great Trek" (1835–1840) in South African history refers to:','The forced removal of black South Africans from urban areas under apartheid','The migration of thousands of Boer (Afrikaner) settlers from the British Cape Colony into the interior of southern Africa','The British military campaign against the Zulu kingdom','The migration of Xhosa people following the cattle-killing movement','B','The Great Trek was the migration of approximately 10,000–14,000 Voortrekkers (Boer settlers) from the British Cape Colony into the interior (Natal, Transvaal, Orange Free State) to escape British rule and establish independent republics.'),

('history','ALL','The Organisation of African Unity (OAU) was founded in Addis Ababa in:','1960','1963','1966','1969','B','The OAU was established on 25 May 1963 in Addis Ababa, Ethiopia, with 32 founding member states. Its founding principles included sovereignty, non-interference, and liberation of remaining colonised territories. It was succeeded by the African Union in 2002.'),

('history','ALL','The "Negritude movement" represented a cultural and intellectual response primarily to:','British indirect rule in West Africa','French assimilationist colonial policy, which required Africans to adopt French culture to gain rights — Negritude affirmed the value of African culture and identity','The economic exploitation of African labour in mines and plantations','The denial of voting rights to Africans in French West Africa','B','Negritude emerged as a response to French assimilationism — the policy that Africans must shed African culture to become "évolués" (evolved/civilised). Senghor and Césaire revalued African cultural heritage as the foundation of a distinct identity.'),

('history','ALL','The "Aba Women''s Riots" (Ogu Umunwanyi) of 1929 in southeastern Nigeria were provoked by:','A dispute over land between Igbo farmers and colonial administrators','Women''s fear that a British colonial tax was about to be extended to women, leading to mass protests that were violently suppressed','A religious conflict between Christian missionaries and traditionalists','A famine caused by colonial agricultural policies','B','The 1929 Aba Women''s Riots were sparked by rumours that the colonial government planned to tax women. Tens of thousands of Igbo and Ibibio women protested, attacked Native Court buildings; British troops fired on protesters, killing about 50 women.');
