-- 100 Post-UTME Government / Political Science Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('government','ALL','Which of the following best defines "sovereignty" in political science?','The economic wealth of a state','The supreme, absolute, and unqualified power of a state to govern itself without external interference','The geographic size and population of a state','The military strength of a nation','B','Sovereignty is the supreme authority of a state within its territory — the right to self-governance free from external control, a foundational concept of the modern state system.'),

('government','ALL','The concept of "separation of powers" is most closely associated with:','Karl Marx','Jean-Jacques Rousseau','Baron de Montesquieu','Thomas Hobbes','C','Montesquieu, in "The Spirit of the Laws" (1748), articulated the doctrine of separation of powers among executive, legislative, and judicial branches to prevent tyranny.'),

('government','ALL','In a federal system of government, residual powers are:','Powers expressly granted to the federal government','Powers shared concurrently by both federal and state governments','Powers not specifically assigned to any level of government, held by states or the centre depending on the constitution','Powers reserved exclusively for the president','C','Residual powers are those not enumerated in the constitution; in Nigeria they belong to states, while in countries like the USA they also reside with states under the 10th Amendment.'),

('government','ALL','The "social contract theory" as propounded by Thomas Hobbes holds that:','People surrender all rights to a sovereign for protection from the brutal state of nature','Government exists to protect natural rights and can be overthrown if it fails','Men are naturally good and corrupted by society','The state is a natural institution rooted in the family','A','Hobbes (Leviathan, 1651) argued life without government is "solitary, poor, nasty, brutish, and short"; people contract to surrender power to an absolute sovereign for security.'),

('government','ALL','The Nigerian 1999 Constitution (as amended) establishes which type of legislature?','Unicameral — a single House of Representatives','Bicameral — a Senate and House of Representatives','Tricameral — Senate, House of Representatives, and State Houses combined','Unicameral — a Senate only','B','Nigeria operates a bicameral National Assembly comprising the Senate (109 senators) and the House of Representatives (360 members), reflecting its federal structure.'),

('government','ALL','Which of the following correctly describes "judicial review" in constitutional democracies?','The power of the executive to review and amend judicial decisions','The authority of courts to declare laws or executive actions unconstitutional and void','The legislature''s power to reverse court judgments','A periodic assessment of the performance of judges by the government','B','Judicial review is the power of courts (especially supreme/constitutional courts) to examine legislation and executive acts against the constitution and nullify those that conflict with it.'),

('government','ALL','"Checks and balances" in government refers to:','The financial auditing of government accounts','Mechanisms by which each branch of government limits the powers of the other branches','The process of reviewing constitutional amendments','The role of the press in monitoring government activities','B','Checks and balances is a constitutional design where each branch (executive, legislative, judicial) has powers to constrain the others, preventing the concentration of power.'),

('government','ALL','The principle of "federalism" involves:','A single, unitary central government with no division of powers','A division of governmental authority between a central government and constituent units (states/regions)','A confederation with no central authority','A military government controlling all regions','B','Federalism divides sovereign powers between a national (federal) government and sub-national units (states), each having defined areas of authority guaranteed by the constitution.'),

('government','ALL','Which of the following is a feature that distinguishes a unitary state from a federal state?','Constitutional supremacy','Separation of powers','The central government is constitutionally supreme and can alter or abolish sub-national units','An independent judiciary','C','In a unitary state, the central government is constitutionally supreme; local/regional governments exist at the centre''s pleasure and can be restructured or abolished by the central authority.'),

('government','ALL','The "vote of no confidence" in a parliamentary system:','Allows the electorate to recall a sitting president before the end of their term','Enables the legislature to remove a prime minister and cabinet from office','Is a mechanism for rejecting the national budget','Gives the judiciary the power to dissolve parliament','B','In a parliamentary system, the legislature can pass a vote of no confidence to remove the prime minister and cabinet, triggering either a new government or fresh elections.'),

('government','ALL','In Nigeria, the Independent National Electoral Commission (INEC) is established by:','An Act of the National Assembly','The 1999 Constitution (as amended)','An executive order of the President','A resolution of the Council of State','B','INEC is a constitutional body established under Section 153 of the 1999 Constitution (as amended) to organise, conduct, and supervise elections in Nigeria.'),

('government','ALL','Which of the following best defines "totalitarianism"?','A system where authority is dispersed among multiple competing parties','A political system in which the state seeks to control all aspects of public and private life','A democratic system with a powerful executive presidency','Rule by a monarch with ceremonial powers only','B','Totalitarianism (e.g., Nazi Germany, Stalinist USSR) is characterised by a single party controlling all aspects of life — political, economic, social, and cultural — with no toleration of opposition.'),

('government','ALL','The concept of "rule of law" as articulated by A.V. Dicey includes:','The absolute supremacy of parliament over the law','Supremacy of law, equality before the law, and the constitution as a result of ordinary law','The right of the executive to govern without judicial interference','Discretionary powers of the government over citizens','B','Dicey''s three pillars of rule of law: (1) supremacy of regular law over arbitrary power; (2) equality of all persons before the law; (3) constitutional rights derived from ordinary law as interpreted by courts.'),

('government','ALL','The "Westminster model" of government is characterised by:','A directly elected president as both head of state and government','Fusion of executive and legislative powers with the prime minister drawn from the legislature','Strict separation of powers with an independently elected legislature','A constitutional monarchy with an elected president','B','The Westminster (parliamentary) model, originating in Britain, features a prime minister who is leader of the parliamentary majority and a cabinet that is collectively responsible to the legislature.'),

('government','ALL','Which of the following is NOT a function of political parties?','Aggregation and articulation of interests','Recruitment and socialisation of political leaders','Adjudication of electoral disputes (deciding winners)','Formation of government after winning elections','C','Political parties aggregate interests, recruit leaders, formulate policies, contest elections, and form government. Adjudicating electoral disputes is the role of electoral commissions and courts, not parties.'),

('government','ALL','The doctrine of "collective responsibility" in cabinet government means:','Each minister is individually responsible to the legislature for their own ministry only','All cabinet members publicly support government decisions, and the cabinet as a whole is responsible to the legislature','Ministers may publicly dissent from cabinet decisions without resigning','The cabinet is responsible only to the head of state','B','Collective cabinet responsibility requires that all ministers publicly defend and implement cabinet decisions; a minister who disagrees must either accept the decision or resign.'),

('government','ALL','Which of the following was the first written constitution in modern history?','The British Constitution of 1688','The United States Constitution of 1787','The French Declaration of Rights of Man, 1789','The Magna Carta of 1215','B','The United States Constitution (1787, ratified 1788) is considered the first codified, written national constitution that established a republican government and remains in force today.'),

('government','ALL','In Nigeria''s political system, "concurrent legislative list" contains matters on which:','Only the Federal Government can legislate','Only State Governments can legislate','Both Federal and State Governments can legislate, with federal law prevailing in case of conflict','The judiciary has exclusive jurisdiction','C','The concurrent legislative list (Second Schedule, 1999 Constitution) contains items on which both the National Assembly and State Houses of Assembly may legislate; federal law prevails in cases of inconsistency.'),

('government','ALL','The term "bicameralism" refers to a legislature with:','One chamber','Two chambers','Three chambers','No fixed number of chambers','B','Bicameralism means a legislature consisting of two separate chambers or houses — typically an upper house (senate) and a lower house (house of representatives).'),

('government','ALL','Which of the following theories of the state argues that the state is an instrument of class domination?','Pluralist theory','Elite theory','Marxist theory','Functionalist theory','C','Marxist theory holds that the state is an instrument of the ruling bourgeois class, used to maintain and reproduce the conditions of capitalist exploitation of the working class.'),

('government','ALL','The concept of "proportional representation" in electoral systems means:','The candidate with the most votes wins, regardless of majority','Seats in the legislature are allocated in proportion to the share of votes each party receives','A run-off election is held if no candidate wins an outright majority','Only registered party members can vote','B','Proportional representation (PR) allocates legislative seats to parties in proportion to their share of the total votes, making the composition of the legislature mirror voter preferences.'),

('government','ALL','John Locke''s social contract theory differs from Hobbes'' primarily in arguing that:','The state of nature is a state of constant war and misery','People surrender all rights to the sovereign permanently','Government''s legitimacy depends on protecting natural rights (life, liberty, property), and people may rebel if it fails','Only absolute monarchy can maintain order','C','Locke (Two Treatises of Government, 1689) argued people retain natural rights; government is a trustee to protect them. If government violates these rights, people have the right to revolution.'),

('government','ALL','The "electoral college" system in the United States is an example of:','Direct democracy','Indirect democracy (representative electoral system)','Proportional representation','A parliamentary system','B','The US Electoral College is an indirect method of electing the president — voters elect electors who formally elect the president — rather than direct popular election.'),

('government','ALL','Which of the following best describes "pressure groups" or interest groups?','Organisations that contest elections directly to win government control','Organised groups that seek to influence government policy without directly seeking political office','Agencies of the government created to lobby the legislature','Political parties that have failed to win elections','B','Pressure (interest) groups seek to influence public policy, legislation, and government decisions without contesting elections themselves — distinguishing them from political parties.'),

('government','ALL','Under the 1999 Nigerian Constitution, the President can be impeached for:','Losing a vote of no confidence in the Senate','Gross misconduct as defined by the National Assembly','Losing the presidential election while in office','A poor economic performance record','B','Section 143 of the 1999 Constitution provides for presidential removal through impeachment for gross misconduct — a defined legal process requiring a two-thirds majority in both houses.'),

('government','ALL','The concept of "delegated legislation" refers to:','Laws made directly by the legislature','Laws, orders, and regulations made by bodies (executive agencies) under powers granted by the legislature','Decisions made by the judiciary that have the force of law','Constitutional amendments passed by a referendum','B','Delegated (subordinate) legislation consists of rules and regulations made by the executive or its agencies under authority explicitly granted by an Act of the legislature (the "parent act").'),

('government','ALL','Which of the following is an example of a "confederation"?','The United States under the current 1787 Constitution','The United States under the Articles of Confederation (1781–1789)','The United Kingdom of Great Britain','The Federal Republic of Nigeria','B','The Articles of Confederation created a loose union of sovereign states with a very weak central authority — the classic historical example of a confederation, replaced by the federal constitution in 1789.'),

('government','ALL','The "garrison state" concept, developed by Harold Lasswell, describes:','A state governed by military officers with no civilian input','A state dominated by specialists in violence (military), where military values and institutions pervade political life','A fully democratic state with a large military','A state in a permanent state of war with its neighbours','B','Lasswell''s garrison state (1941) warned of a trend toward states increasingly dominated by military-security specialists and values, threatening democratic civil-military relations.'),

('government','ALL','In Nigeria, the principle of "federal character" is intended to:','Ensure that only federal civil servants are appointed to positions','Promote national unity by ensuring government appointments reflect Nigeria''s ethnic and geographic diversity','Restrict the powers of state governments','Give the federal government exclusive control over national resources','B','Section 14(3) of the 1999 Constitution requires the composition of federal government and its agencies to reflect Nigeria''s federal character — ethnic, linguistic, and zonal diversity.'),

('government','ALL','The term "geopolitics" refers to:','Economic policies of multinational corporations','The study of how geography, location, and resources influence a state''s political power and international relations','The science of measuring electoral boundaries','Diplomatic relations between neighbouring countries','B','Geopolitics examines how geographic factors (location, size, natural resources, climate) shape state power, strategic interests, and international relations.'),

('government','ALL','Which of the following best describes "parliamentary sovereignty"?','The power of courts to overturn Acts of Parliament','Parliament is the supreme legal authority and can make or unmake any law','The Prime Minister has ultimate legislative authority','Citizens can veto Acts of Parliament through referenda','B','Parliamentary sovereignty (a UK doctrine) holds that Parliament is the supreme legal authority — it can enact any legislation, and no other body (not even courts) can override its acts.'),

('government','ALL','The Westphalian system of international relations, established in 1648, introduced:','The concept of collective security through international organisations','The principle of state sovereignty and non-interference in the internal affairs of other states','The right of humanitarian intervention in failed states','Mandatory arbitration of disputes by a supranational court','B','The Peace of Westphalia (1648) ended the Thirty Years'' War and established the modern international system based on sovereign equality of states and non-interference in internal affairs.'),

('government','ALL','The "iron law of oligarchy," proposed by Robert Michels, states that:','Oligarchic rule is inevitable in democracies because all organisations, including political parties, are eventually controlled by a small elite','Oligarchy is a superior form of government to democracy','Military officers inevitably dominate all democratic governments','Only wealthy elites can stand for election in democracies','A','Michels (1911) argued that all organisations, even democratic ones, inevitably develop oligarchic leadership — a small group at the top gains control and pursues its own interests.'),

('government','ALL','Which of the following is the primary difference between a "presidential" and a "parliamentary" system of government?','A presidential system has a bicameral legislature; a parliamentary system does not','In a presidential system, the executive is separate from and not dependent on the legislature for survival; in a parliamentary system, the executive is drawn from and responsible to the legislature','A parliamentary system has an elected president; a presidential system does not','A presidential system has stronger judicial review','B','The key difference: in presidential systems, the executive (president) is separately elected and cannot be removed by the legislature through routine votes; in parliamentary systems, the executive is part of and responsible to the legislature.'),

('government','ALL','The concept of "pluralism" in political science argues that:','Power is concentrated in the hands of a single ruling elite','Political power is widely dispersed among many competing groups, none of which dominates all areas','The state is controlled by the military-industrial complex','Democracy inevitably degenerates into oligarchy','B','Pluralism holds that in modern democracies, power is distributed among multiple, competing interest groups; no single elite dominates all decisions — government reflects the bargaining among these groups.'),

('government','ALL','In Nigeria, which body has the power to confirm the appointment of the Chief Justice of Nigeria?','The Federal Executive Council','The National Judicial Council','The Senate','The House of Representatives','C','Section 231 of the 1999 Constitution requires the President to appoint the Chief Justice of Nigeria on the recommendation of the National Judicial Council, subject to confirmation by the Senate.'),

('government','ALL','The "Bretton Woods institutions" established after World War II include:','The United Nations and NATO','The International Monetary Fund (IMF) and the World Bank','The World Trade Organisation and the G7','The African Union and ECOWAS','B','The Bretton Woods Conference (1944) established the IMF (to stabilise exchange rates and provide short-term balance of payments support) and the World Bank (to finance reconstruction and development).'),

('government','ALL','Which of the following correctly defines "political socialisation"?','The process by which the government controls citizens'' political views','The lifelong process by which individuals acquire political attitudes, values, and beliefs through family, school, media, and other agents','The formal civic education conducted in schools only','The process of registering voters before elections','B','Political socialisation is the ongoing process through which people develop their political orientations, shaped by family, peers, education, media, religion, and life experiences.'),

('government','ALL','The concept of "bureaucracy" as an ideal-type, developed by Max Weber, is characterised by:','Personal loyalty to the ruler, informal rules, and hereditary positions','Hierarchical authority, written rules, impersonality, and merit-based appointments','Military control over civilian administration','Rotation of positions among all citizens regardless of qualification','B','Weber''s ideal-type bureaucracy features: fixed jurisdictions, hierarchical authority, written rules, technical expertise (merit), impersonality, and full-time salaried officials — the model of rational-legal administration.'),

('government','ALL','The "domino theory" during the Cold War was the belief that:','Nuclear weapons would eventually be used in a global war','If one country fell to communism, neighbouring countries would follow in turn','Democratic governments would inevitably collapse in developing nations','Economic aid would prevent the spread of authoritarian governments','B','The domino theory, used to justify US Cold War interventions (notably in Vietnam), held that a communist victory in one country would trigger communist takeovers in neighbouring states.'),

('government','ALL','Which of the following is a characteristic of "authoritarian" regimes?','Free and competitive elections with independent media','Multi-party democracy with strong civil liberties','Concentrated power with limited political pluralism, but without total control of private life','Total control of all aspects of public and private life','C','Authoritarianism involves concentrated power and restricted political freedoms, but unlike totalitarianism, it typically does not seek to control all areas of life — some private sphere autonomy remains.'),

('government','ALL','The Universal Declaration of Human Rights (UDHR) was adopted by the United Nations in:','1945','1948','1966','1976','B','The UN General Assembly adopted the Universal Declaration of Human Rights on 10 December 1948, establishing a common standard of fundamental rights for all people.'),

('government','ALL','In Nigerian federalism, the "Exclusive Legislative List" contains subjects on which:','Only State Assemblies can make laws','Both federal and state governments share legislative powers','Only the National Assembly can make laws','The judiciary has exclusive authority','C','The Exclusive Legislative List (First Schedule, Part I of the 1999 Constitution) itemises matters (e.g., defence, foreign affairs, currency) on which only the National Assembly can legislate.'),

('government','ALL','The term "lame duck" in political science refers to:','A politician who has never won an election','An elected official in the final period of their term after a successor has been elected','A politician who lacks party support','An appointed official with no legislative powers','B','A "lame duck" is an official (especially a president) serving out the remainder of their term after their successor has been elected, and therefore has reduced influence and political leverage.'),

('government','ALL','Which of the following best describes "realism" in international relations theory?','States are guided by international law and moral norms in their foreign policy','States are the primary actors, the international system is anarchic, and states pursue power and security above all','International institutions effectively constrain state behaviour','Economic interdependence eliminates the risk of conflict between states','B','Realism (Morgenthau, Waltz) holds that in an anarchic international system, states are the main actors, they pursue national interest defined as power, and conflict is an enduring feature of international politics.'),

('government','ALL','The concept of "devolution" in a unitary state refers to:','The permanent transfer of sovereignty to regional governments','The granting of specified powers to regional or local governments by the central government, which retains sovereignty','The abolition of sub-national governments','The return of powers from the regions to the centre','B','Devolution is the delegation of legislative/executive powers from the central government to subnational bodies, as in Scotland and Wales in the UK — the centre retains ultimate sovereignty and can revoke the powers.'),

('government','ALL','Which of the following is NOT a recognised source of the Nigerian Constitution?','Judicial precedent (case law)','Conventions and customs','Legislation (Acts of the National Assembly)','The personal decrees of the incumbent president','D','The 1999 Constitution derives from: the constitutional document itself, legislation, judicial decisions interpreting it, and constitutional conventions. Personal presidential decrees are NOT a recognised constitutional source.'),

('government','ALL','The "first-past-the-post" (FPTP) electoral system can produce:','Highly proportional results where seats closely match vote shares','"Manufactured majorities" where a party wins a large majority of seats with less than a majority of votes','Coalition governments as the normal outcome','Guaranteed representation for all minority groups','B','FPTP''s single-member plurality system frequently produces disproportionate results — winning parties often secure parliamentary majorities well in excess of their vote share, and many votes are "wasted."'),

('government','ALL','The theory of "élitism" in political sociology argues that:','Political power is widely distributed among ordinary citizens','In all societies, a small, cohesive minority (the elite) dominates political life regardless of formal democratic structures','Economic equality is the basis of political equality','Democratic participation necessarily produces equitable policy outcomes','B','Elite theory (Pareto, Mosca, Mills) holds that political power is always concentrated in a small ruling elite, even in democracies, because of superior organisation, resources, and strategic positions.'),

('government','ALL','The African Union (AU) was established in:','1963, replacing the Organisation of African Unity','2002, replacing the Organisation of African Unity','1991, as the successor to the Economic Community of African States','1980, at the Lagos Plan of Action','B','The African Union was formally established in 2002 (Durban, South Africa), succeeding the Organisation of African Unity (OAU, founded 1963) with a stronger mandate for continental integration and governance.'),

('government','ALL','Which of the following is the primary goal of the Economic Community of West African States (ECOWAS)?','To establish a common military command for West Africa','To promote economic integration and cooperation among West African states','To manage the extraction of natural resources in West Africa','To serve as a peacekeeping force under UN command','B','ECOWAS (established 1975, Treaty of Lagos) aims to promote economic integration — free movement of persons, goods, services, and capital — and cooperate on political and security matters among its 15 member states.'),

('government','ALL','The concept of "veto power" in the UN Security Council means:','Any member state can block Security Council resolutions','Only the five permanent members (P5) can block substantive Security Council resolutions by voting against them','The UN Secretary-General can nullify Security Council decisions','The General Assembly can override Security Council resolutions','B','Each of the five permanent members of the UN Security Council (USA, UK, France, Russia, China) holds veto power — the ability to block any substantive resolution by casting a negative vote.'),

('government','ALL','In Nigeria, the Council of State is chaired by:','The Senate President','The Chief Justice of Nigeria','The President of the Federal Republic','The Vice President','C','Under Section 153 and Part I of the Third Schedule of the 1999 Constitution, the President of the Federal Republic chairs the Council of State.'),

('government','ALL','Which constitutional conference led to Nigeria''s independence in 1960?','The Macpherson Constitution Conference of 1951','The Lyttelton Constitution Conference of 1954','The Lancaster House Conference of 1958','The Richards Constitution Conference of 1946','C','The Lancaster House Conference (London, 1958) settled the final constitutional arrangements for Nigerian independence, which was granted on 1 October 1960 under the Independence Constitution.'),

('government','ALL','The "Second Republic" in Nigeria lasted from:','1963 to 1966','1979 to 1983','1993 to 1998','1999 to the present','B','Nigeria''s Second Republic was the civilian democratic government under the presidential system, from October 1979 (President Shehu Shagari) to December 1983, when it was ended by a military coup.'),

('government','ALL','The principle of "habeas corpus" protects citizens against:','Unlawful and prolonged detention without trial','Excessive taxation by the government','Unfair dismissal from public service','Interference with the right to vote','A','Habeas corpus (Latin: "you have the body") is a legal writ requiring a person under detention to be brought before a court to determine if the detention is lawful — a fundamental protection against arbitrary imprisonment.'),

('government','ALL','In international law, the term "jus cogens" refers to:','Optional norms that states may choose to follow','Peremptory norms of general international law from which no derogation is permitted','Customary law applicable only within a single region','Treaties signed under duress that are automatically void','B','Jus cogens (Latin: "compelling law") are fundamental, non-derogable principles of international law — e.g., prohibition of genocide, slavery, torture — that bind all states regardless of consent.'),

('government','ALL','Which of the following correctly describes "diplomatic immunity"?','The right of a state to conduct espionage on foreign soil','The exemption of diplomatic agents from the jurisdiction of the host state''s laws under international law','A state''s right to expel foreign diplomats at any time','The power of the UN Secretary-General to grant immunity to war criminals','B','Diplomatic immunity, governed by the 1961 Vienna Convention on Diplomatic Relations, exempts diplomats from the criminal and civil jurisdiction of the host country to facilitate free diplomatic functions.'),

('government','ALL','The "spoils system" in political science refers to:','A merit-based civil service recruitment system','The practice of awarding government jobs and contracts to supporters of the winning political party','The process of distributing seized assets of corrupt officials','A system of proportional representation based on party membership','B','The spoils system (winner-takes-all patronage), famously practised in 19th-century US politics, refers to the practice of victorious politicians rewarding their supporters with public offices and contracts.'),

('government','ALL','Which of the following is a characteristic unique to a "federal" constitution as opposed to a "unitary" one?','Existence of an independent judiciary','Separation of powers','Constitutional distribution of powers between central and component governments, each supreme in its own sphere','A bicameral legislature','C','The defining feature of federalism is the constitutional allocation of powers between levels of government — unlike a unitary system, neither level can unilaterally abolish or alter the other''s constitutionally assigned powers.'),

('government','ALL','The "Truman Doctrine" (1947) committed the United States to:','Providing economic aid to war-devastated European economies','Supporting free peoples resisting subjugation by armed minorities or outside pressures (especially communism)','Establishing NATO as a collective defence organisation','Non-intervention in European political affairs','B','The Truman Doctrine (March 1947) marked the US commitment to containment — pledging to support countries threatened by communist takeover, first applied to Greece and Turkey.'),

('government','ALL','The concept of "non-alignment" during the Cold War meant that:','Countries that chose not to join military alliances with either the USA or the USSR','Countries that refused to join the United Nations','Nations that adopted a neutral stance in all international conflicts','Nations that refused all foreign aid','A','The Non-Aligned Movement (NAM), formally established 1961, grouped developing nations that sought to maintain independence from both US and Soviet-led blocs during the Cold War.'),

('government','ALL','Which of the following is NOT a fundamental right guaranteed under Chapter IV of the 1999 Nigerian Constitution?','Right to dignity of human person','Right to fair hearing','Right to free university education','Right to freedom of expression','C','Chapter IV of the 1999 Constitution guarantees rights such as life, dignity, fair hearing, privacy, expression, assembly, and freedom from discrimination. The right to free university education is not included.'),

('government','ALL','The Federal Character Commission in Nigeria was established to:','Oversee the conduct of federal elections','Ensure equitable distribution of positions in federal institutions reflecting Nigeria''s federal character','Regulate the activities of federal corporations','Manage the allocation of oil revenues among states','B','The Federal Character Commission (Section 153, 1999 Constitution) monitors and enforces the constitutional principle of federal character — ensuring equitable representation of diverse groups in federal appointments.'),

('government','ALL','The "Marshall Plan" (1948) was:','A US military strategy for defending Western Europe from Soviet invasion','A US economic aid programme to rebuild war-devastated Western European economies','A NATO plan for collective defence','A Soviet plan for the reconstruction of Eastern Europe','B','The Marshall Plan (European Recovery Programme, 1948–1952) provided over $12 billion in US economic aid to rebuild Western European economies devastated by World War II, also serving to contain the spread of communism.'),

('government','ALL','In presidential systems, "executive privilege" refers to:','The president''s right to appoint Supreme Court justices','The power claimed by the president to withhold information from the legislature or courts when national security or executive confidentiality is at stake','The president''s immunity from all civil and criminal prosecution','The power to declare a state of emergency','B','Executive privilege is the president''s claimed right to maintain the confidentiality of communications within the executive branch, especially regarding national security — a concept tested in US v. Nixon (1974).'),

('government','ALL','Which of the following best describes the "structural-functionalist" approach in political science?','Politics is a struggle for power among competing elite groups','Political systems can be analysed by identifying structures (institutions) and the functions they perform to maintain the system','Political behaviour is best understood through economic incentives','The state is an instrument of class oppression','B','Structural-functionalism (Almond & Powell) analyses political systems by identifying their structures (parties, legislature, bureaucracy) and the functions these perform (socialisation, recruitment, rule-making) to sustain the system.'),

('government','ALL','The concept of "political culture" refers to:','The artistic and cultural policies of a government','The shared attitudes, values, beliefs, and orientations that citizens hold towards the political system','The formal rules and institutions of government','The role of traditional rulers in modern governance','B','Political culture encompasses the deep-seated values, beliefs, and emotional orientations citizens hold about politics and government — influencing political behaviour and system stability (Almond & Verba).'),

('government','ALL','The "Responsibility to Protect" (R2P) doctrine in international relations holds that:','States have an absolute right to sovereignty regardless of how they treat their citizens','The international community has a responsibility to protect populations from genocide, war crimes, ethnic cleansing, and crimes against humanity when their own government fails to do so','Only the UN Security Council can authorise humanitarian intervention','NATO has a permanent mandate to protect civilians worldwide','B','R2P (adopted at the 2005 UN World Summit) holds that sovereignty entails responsibility: if a state fails to protect its citizens from mass atrocity crimes, the international community has a right and duty to intervene.'),

('government','ALL','Which of the following is a feature of a "confederal" system of government?','The central government is sovereign and can override component states','Component states are sovereign; the central body has only delegated, limited powers','The constitution allocates powers equally between centre and states','All legislative powers reside exclusively with the central body','B','In a confederation, the constituent states are sovereign; the central authority derives its limited powers from the states and cannot act directly on individual citizens without state consent.'),

('government','ALL','The concept of "power" as defined by Max Weber is:','The ability to achieve goals through cooperation and consensus alone','The probability that one actor within a social relationship will be in a position to carry out their will despite resistance','The formal authority granted by a constitution or law','Economic wealth that enables political influence','B','Weber defined power (Macht) as the probability of carrying out one''s will even against the resistance of others — distinguishing it from authority (Herrschaft), which is legitimate power.'),

('government','ALL','In Nigeria''s Third Republic (aborted), the transition programme was designed by which military administration?','General Yakubu Gowon','General Muhammadu Buhari','General Ibrahim Babangida','General Sani Abacha','C','General Ibrahim Babangida''s administration (1985–1993) designed the Third Republic transition programme, which culminated in the June 12, 1993 presidential election won by MKO Abiola but controversially annulled.'),

('government','ALL','The concept of "political legitimacy" refers to:','The legal authority of a government to make and enforce laws','The widespread belief among citizens that the government has the right to rule and that its authority is justified','The ability of a government to suppress political opposition','The international recognition of a state by other states','B','Legitimacy is the normative belief among the governed that a government''s authority is rightful and justified — without legitimacy, governments must rely solely on coercion. Weber identified legal-rational, traditional, and charismatic legitimacy.'),

('government','ALL','The "treaty of Rome" (1957) established which major international institution?','The United Nations Economic Commission for Europe','The European Economic Community (EEC), precursor to the European Union','The North Atlantic Treaty Organisation','The International Court of Justice','B','The Treaty of Rome (1957) established the European Economic Community (EEC) among six founding states, creating a common market and laying the groundwork for what became the European Union in 1993.'),

('government','ALL','In political science, "interest articulation" is performed primarily by:','Political parties during election campaigns','Interest groups, social movements, and civil society organisations expressing demands to the political system','Government agencies implementing public policy','Courts adjudicating disputes between citizens and the state','B','Interest articulation is the function of converting individual or group demands into political issues — performed by interest groups, civil society, media, and social movements presenting demands to decision-makers.'),

('government','ALL','The Nigerian Supreme Court derives its powers from:','The National Judicial Council','Sections 230–236 of the 1999 Constitution (as amended)','An Act of the National Assembly on the judiciary','A resolution of the Federal Executive Council','B','The Supreme Court''s jurisdiction, composition, and powers are established in Sections 230–236 of the 1999 Constitution — it is the apex court with final appellate jurisdiction on constitutional matters.'),

('government','ALL','Which of the following best describes "constructivism" in international relations?','States are rational actors that maximise material power and security','National interests and identities are socially constructed through interaction, norms, and ideas rather than fixed material interests','Economic interdependence prevents conflict between states','International institutions are the primary drivers of state behaviour','B','Constructivism (Wendt, Onuf) argues that international reality is socially constructed — state identities, interests, and international norms are not given but emerge through social interaction and shared ideas.'),

('government','ALL','The concept of "civil-military relations" is primarily concerned with:','The role of the military in economic development','The proper balance of authority, accountability, and autonomy between civilian governments and armed forces','Recruitment and training procedures in the military','Military cooperation between allied states','B','Civil-military relations concerns how civilian governments maintain democratic control over the military while ensuring effective defence — including mechanisms of oversight, accountability, and the proper role of the military in politics.'),

('government','ALL','Which of the following is the correct order of precedence for sources of law in Nigeria?','Customary law, common law, statute law, the constitution','The constitution, statute law, common law, customary law','Statute law, the constitution, common law, customary law','Common law, the constitution, statute law, customary law','B','In Nigeria''s legal hierarchy: the 1999 Constitution is supreme (Section 1); below it are statutes (Acts of the National Assembly/State Laws); then received English common law; and finally customary law.'),

('government','ALL','The "June 12" crisis in Nigeria (1993) revolved around:','A military coup that ended the Second Republic','The annulment of a presidential election widely believed to have been won by Chief MKO Abiola','A constitutional crisis over state creation','A border dispute with a neighbouring country','B','On June 12, 1993, Nigerians voted in a presidential election widely adjudged free and fair; General Babangida subsequently annulled the result, sparking a prolonged political crisis and Abiola''s eventual recognition as winner (posthumously in 2018).'),

('government','ALL','The principle of "stare decisis" in judicial practice means:','Courts may overrule any previous decision if they disagree with it','Courts are bound to follow the legal principles established in previous decisions (precedents)','The legislature can direct courts on how to decide cases','The executive has the power to review court judgments','B','Stare decisis (Latin: "to stand by things decided") is the doctrine requiring courts to follow precedent — legal principles established in earlier cases that are binding on lower courts in the same hierarchy.'),

('government','ALL','Which of the following is an example of "negative liberty" as defined by Isaiah Berlin?','The freedom to participate actively in self-governance','Freedom from external interference or coercion by others','The freedom provided by access to economic resources','The liberty granted by the state to pursue specific goals','B','Berlin''s "Two Concepts of Liberty" (1958): negative liberty is freedom from interference by others (absence of constraints); positive liberty is freedom to pursue self-realisation and autonomy.'),

('government','ALL','The "Lome Convention" (and its successor the Cotonou Agreement) governs trade and aid relations between:','The United States and Latin American countries','The European Union and African, Caribbean, and Pacific (ACP) countries','OPEC member states and industrialised nations','The World Trade Organisation and developing countries','B','The Lomé Conventions (1975–2000) and the successor Cotonou Agreement (2000) established a trade and development partnership between the EU and ACP states, providing preferential trade access and development aid.'),

('government','ALL','The concept of "decolonisation" in the post-WWII period primarily refers to:','The economic development of former colonies','The process by which Asian and African territories gained political independence from European colonial powers','The voluntary transfer of colonial assets to indigenous populations','The establishment of colonial administrations in new territories','B','Decolonisation was the political process by which European colonies — especially in Asia and Africa — achieved independence in the decades following World War II, driven by nationalist movements and changed global norms.'),

('government','ALL','In Nigerian constitutional law, "standing" (locus standi) in constitutional cases refers to:','The right of a lawyer to appear before the Supreme Court','The legal right of a person or organisation to bring an action before a court, demonstrating sufficient connection to the matter','The power of the Senate President to stand in for the President','A court''s geographic jurisdiction','B','Locus standi (standing) is the legal capacity of a party to bring a case before a court — the party must demonstrate sufficient interest in the outcome of the matter to be heard.'),

('government','ALL','Which of the following best characterises "guerrilla warfare" as a political-military strategy?','A large conventional army attacking an enemy''s front lines','Small, mobile irregular forces using hit-and-run tactics against a stronger opponent, seeking political goals alongside military ones','A naval blockade strategy to starve an enemy nation','Airpower-centric warfare aimed at destroying an enemy''s infrastructure','B','Guerrilla warfare involves irregular forces using ambushes, sabotage, and hit-and-run tactics to harass a superior conventional force, aiming to erode its will while building political support — associated with Mao Zedong and revolutionary movements.'),

('government','ALL','The "principle of subsidiarity" in governance holds that:','All decisions should be made at the highest possible level of government','Decisions should be made at the lowest possible level of government that is competent to handle them effectively','The central government should control all major policy areas','Local governments should have no independent powers','B','The principle of subsidiarity holds that governance functions should be performed at the most local level capable of handling them effectively — embedded in EU law and federal/decentralised governance theory.'),

('government','ALL','In the context of the Nigerian political system, "zoning" refers to:','The geographic allocation of electoral constituencies','The informal practice of rotating key political offices among Nigeria''s geopolitical zones to ensure regional balance','A constitutional provision for state boundary changes','The allocation of natural resources to producing states','B','Zoning is an informal but politically significant convention in Nigeria''s ruling parties, rotating key executive positions (presidency, governorships) among geopolitical zones to manage ethnic and regional competition.'),

('government','ALL','The concept of "civil disobedience" as articulated by Henry David Thoreau and later Mahatma Gandhi involves:','Armed resistance against an unjust government','The deliberate, public, non-violent refusal to obey unjust laws as a form of moral protest','The use of electoral processes to change unjust policies','The formation of alternative governments to replace unjust regimes','B','Civil disobedience (Thoreau''s "Resistance to Civil Government," 1849; Gandhi''s satyagraha) is the non-violent, conscientious, public refusal to obey laws deemed unjust, accepting legal consequences to appeal to the moral conscience of society.'),

('government','ALL','Which of the following is the main criticism of the "first-past-the-post" electoral system?','It produces too many coalition governments','It often produces disproportionate outcomes — a party can win majority of seats with a minority of votes, and minority party votes are wasted','It is too complex for ordinary voters to understand','It always leads to two-party dominance without exception','B','FPTP''s main criticisms: disproportionality (seats don''t reflect vote shares), wasted votes (votes for losing candidates count for nothing), and potential for a party with a minority of votes to win a large parliamentary majority.'),

('government','ALL','The "dependency theory" in development studies argues that:','Developing nations will catch up with rich nations through free trade and foreign investment','Underdevelopment of the Global South is structurally maintained by its dependent relationship with and exploitation by developed nations','Aid is the most effective mechanism for achieving development','Political instability is the primary cause of underdevelopment','B','Dependency theory (Prebisch, Frank, Cardoso) holds that the global capitalist system structurally disadvantages developing countries — keeping them dependent exporters of raw materials and importers of expensive manufactures, perpetuating underdevelopment.'),

('government','ALL','What was the significance of the "Aburi Accord" (1967) in Nigerian history?','It was the peace agreement that ended the Nigeria-Biafra Civil War','A meeting between the Nigerian military leadership that agreed to a loose confederation arrangement, whose rejection contributed to the outbreak of the Civil War','It established Nigeria''s federal system with 12 states','A regional agreement on resource sharing in the Niger Delta','B','The Aburi (Ghana) meeting of January 1967 produced agreements on a confederation-like arrangement for Nigeria between Gowon and Ojukwu; when Gowon subsequently modified the implementation, Ojukwu declared Biafra''s secession, triggering the civil war.'),

('government','ALL','The concept of "political apathy" refers to:','Active participation in political demonstrations','Widespread lack of interest, enthusiasm, or concern about political affairs among citizens','Extreme partisan loyalty to a single political party','Government suppression of political opposition','B','Political apathy is a condition of indifference among citizens toward political processes — low voter turnout, disengagement from civic life, and lack of interest in political outcomes are its manifestations.'),

('government','ALL','Which of the following is the correct definition of "gerrymander"?','The merger of two political parties before an election','The manipulation of electoral district boundaries to give an unfair advantage to a particular party or group','The illegal purchase of votes by political parties','The unconstitutional removal of an elected official','B','Gerrymandering is the redrawing of electoral district boundaries to favour a particular political party or group — named after Massachusetts Governor Elbridge Gerry, whose administration created a salamander-shaped district in 1812.');
