-- 20 Post-UTME Geography Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('geography','ALL','The theory of "plate tectonics" explains which of the following phenomena?','The formation of ocean trenches by erosion of the ocean floor','The movement of large segments of the Earth''s lithosphere on the asthenosphere, responsible for earthquakes, volcanoes, and mountain building','The distribution of world climatic zones','The formation of river deltas and estuaries','B','Plate tectonics holds that the Earth''s lithosphere is divided into large rigid plates that move on the semi-fluid asthenosphere. Their interaction at boundaries produces earthquakes, volcanoes, ocean ridges, trenches, and mountain ranges.'),

('geography','ALL','Which of the following is the correct definition of "latitude"?','The angular distance of a point east or west of the Prime Meridian','The angular distance of a point north or south of the Equator, measured in degrees from 0° to 90°','The height of a place above sea level','The distance between two points measured along the Earth''s surface','B','Latitude is the angular distance measured north or south of the Equator (0°) to the poles (90°N and 90°S). Lines of latitude are also called parallels.'),

('geography','ALL','The "intertropical convergence zone" (ITCZ) is a belt of low pressure found:','Along the Tropic of Cancer and Tropic of Capricorn','Near the Equator, where northeast and southeast trade winds converge, causing heavy rainfall','At the poles, where cold polar air sinks to create high pressure','Along the 30th parallel north and south, creating hot deserts','B','The ITCZ is a belt of low pressure near the Equator where the trade winds from both hemispheres converge, causing air to rise, cool, and produce heavy convectional rainfall — it shifts north and south seasonally, controlling tropical climates.'),

('geography','ALL','The process of "chemical weathering" involves:','The physical breakdown of rocks by temperature changes, frost action, and abrasion','The decomposition and alteration of rocks through chemical reactions such as oxidation, hydration, and carbonation','The wearing away of rock surfaces by glacial ice','The transportation of weathered material by rivers and wind','B','Chemical weathering decomposes rocks through chemical processes: carbonation (solution of limestone by carbonic acid), oxidation (rusting of iron minerals), hydration (absorption of water), and hydrolysis — changing the mineral composition of rocks.'),

('geography','ALL','A "watershed" in physical geography is:','The area of land drained by a single river and its tributaries','The ridge of high land separating two adjacent drainage basins','The point at which a river enters the sea or a lake','A depression in which a lake or pond forms','B','A watershed (divide) is the elevated ridge or boundary separating two drainage basins — precipitation falling on one side drains to one river system, while precipitation on the other side drains to a different system.'),

('geography','ALL','Which type of rainfall is associated with mountainous areas, where moist air is forced upward along the windward slope, cools, and condenses?','Convectional rainfall','Cyclonic (frontal) rainfall','Orographic (relief) rainfall','Advection fog','C','Orographic (relief) rainfall occurs when prevailing moist winds are forced to rise over mountains (windward side), causing cooling, condensation, and precipitation. The leeward side receives less rain (rain shadow).'),

('geography','ALL','The "greenhouse effect" refers to:','The practice of growing crops in glass houses to extend the growing season','The process by which certain atmospheric gases (CO₂, CH₄, water vapour) trap outgoing longwave radiation from Earth''s surface, warming the planet','The destruction of the ozone layer by chlorofluorocarbons (CFCs)','The phenomenon of acid rain caused by industrial pollution','B','The greenhouse effect: solar shortwave radiation passes through the atmosphere and warms Earth''s surface; the surface emits longwave (infrared) radiation, which is absorbed by greenhouse gases (CO₂, CH₄, N₂O, water vapour) and re-emitted, trapping heat.'),

('geography','ALL','The Sahel region of Africa is best described as:','A dense tropical rainforest zone south of the Sahara','A semi-arid transitional belt between the Sahara Desert to the north and the savanna to the south, characterised by sparse rainfall and periodic drought','A fertile agricultural zone along the West African coast','A plateau region in eastern Africa known for its volcanic soils','B','The Sahel ("shore" in Arabic) is a semi-arid zone stretching across Africa from Senegal to Sudan, marking the transition from Sahara desert to the tropical savanna. It receives 200–600 mm of rain annually and is highly vulnerable to desertification and drought.'),

('geography','ALL','In the context of population geography, "demographic transition model" describes:','The process by which people migrate from rural areas to urban centres','The historical shift in population growth rates as societies move from high birth and death rates (pre-industrial) to low birth and death rates (post-industrial)','The distribution of population across urban, suburban, and rural areas','The patterns of international migration between developing and developed countries','B','The Demographic Transition Model (DTM) describes four stages of population change: Stage 1 (high birth rate, high death rate → stable population), Stage 2 (falling death rates, still high birth rates → rapid growth), Stage 3 (falling birth rates → slowing growth), Stage 4 (low birth and death rates → stable or declining population).'),

('geography','ALL','Which of the following statements correctly describes "continental drift" as proposed by Alfred Wegener?','The continents were always in their present positions and have not moved','All the continents were once joined in a single supercontinent called Pangaea, which broke apart and drifted to their current positions over millions of years','The continents are slowly sinking into the ocean due to the weight of ice caps','Continents move due to tidal forces exerted by the Moon','B','Alfred Wegener (1912) proposed that all continents were once united as Pangaea (~300 million years ago), which fragmented and drifted apart — supported by the fit of continental coastlines, matching fossil records, and geological formations.'),

('geography','ALL','The "Coriolis effect" influences the direction of:','Ocean currents and atmospheric winds, deflecting them to the right in the Northern Hemisphere and to the left in the Southern Hemisphere','The flow of rivers — always towards the nearest coastline','The movement of tectonic plates','The formation of tides in coastal areas','A','The Coriolis effect is an apparent deflection of moving objects (winds, ocean currents) due to Earth''s rotation — rightward in the Northern Hemisphere, leftward in the Southern. It is responsible for the rotation of cyclones (anticlockwise in NH, clockwise in SH).'),

('geography','ALL','A "fjord" is a coastal landform produced by:','Wave erosion cutting deep notches into a rocky coastline','Glacial erosion of a valley, which is subsequently flooded by the sea after the glacier retreats','River deposition building a triangular landform at a river mouth','Wind deposition forming a long coastal sand ridge','B','A fjord is a long, narrow, deep inlet with steep sides, formed when a glacial valley (U-shaped trough) eroded below sea level is subsequently flooded by the sea as glaciers retreat — common in Norway, Greenland, and New Zealand.'),

('geography','ALL','The "ozone layer" is located in which layer of the atmosphere?','Troposphere','Stratosphere','Mesosphere','Thermosphere','B','The ozone layer is concentrated in the lower stratosphere (approximately 15–35 km altitude). It absorbs most of the Sun''s harmful ultraviolet (UV-B and UV-C) radiation, protecting life on Earth.'),

('geography','ALL','Which of the following factors is the PRIMARY cause of the deflection of ocean currents from a straight path?','The temperature difference between the ocean surface and the deep ocean','The Coriolis effect and the configuration of the ocean basins and continents','The gravitational pull of the Moon causing tidal currents','Wind direction at the ocean surface only','B','Surface ocean currents are driven by prevailing winds, but their direction is deflected by the Coriolis effect and constrained by the shape of continents and ocean basins, creating gyres (large circular current systems).'),

('geography','ALL','The "population density" of a country is calculated as:','Total population minus total death rate','Total population divided by the total land area (persons per km²)','Total population multiplied by the birth rate','Total urban population as a percentage of total population','B','Population density = Total Population / Total Land Area (expressed as persons per km² or per square mile). It gives a measure of how crowded a country or region is.'),

('geography','ALL','In geography, "erosion" differs from "weathering" in that:','Erosion involves chemical breakdown while weathering involves physical removal','Weathering breaks down rocks in situ (in place), while erosion involves the removal and transportation of weathered material by agents such as water, wind, or ice','Both processes are identical — the terms are interchangeable','Erosion occurs only in coastal areas while weathering occurs only in deserts','B','Weathering is the in-situ breakdown and decomposition of rock material (no transportation). Erosion is the removal and transportation of that material by a moving agent (river, wind, ice, waves) — the two processes work together in landscape formation.'),

('geography','ALL','The "Niger Delta" in Nigeria is a classic example of which type of coastal landform?','A fjord','A ria coastline','A river delta','A coral atoll','C','A river delta forms at a river''s mouth when the river deposits its sediment load faster than waves and tides can remove it — the Niger Delta, one of the world''s largest, is a classic arcuate/bird''s-foot delta formed by the River Niger.'),

('geography','ALL','Which of the following correctly explains "urbanisation"?','The process of developing agricultural land for crop production','The increasing proportion of a country''s population living in urban areas, accompanied by the physical growth of towns and cities','The decline of rural population due to emigration to other countries','The process of building new infrastructure in rural areas','B','Urbanisation is the process by which an increasing share of a population comes to live in urban areas — driven by rural-urban migration and natural urban population increase — accompanied by physical expansion of urban settlements.'),

('geography','ALL','The "Amazon Basin" in South America is significant geographically because:','It is the world''s driest non-polar desert','It contains the world''s largest tropical rainforest, harbouring the greatest biodiversity of any terrestrial ecosystem','It is the site of the world''s largest freshwater lake by surface area','It is the world''s most densely populated agricultural region','B','The Amazon Basin (Brazil and neighbouring countries) contains the Amazon Rainforest — the world''s largest tropical rainforest (~5.5 million km²), home to an estimated 10% of all species on Earth and playing a critical role in the global carbon cycle.'),

('geography','ALL','Which of the following is the correct sequence of rock formation in the rock cycle?','Metamorphic → Igneous → Sedimentary (only, with no alternatives)','Magma cools to form igneous rock; igneous rock is weathered, transported, and deposited to form sedimentary rock; sedimentary (or igneous) rock subjected to heat and pressure becomes metamorphic rock','Sedimentary rock always forms from metamorphic rock only','Rock formation is a one-way process with no cycle','B','The rock cycle: molten magma solidifies into igneous rock → weathered into sediment → compacted/cemented into sedimentary rock → subject to heat/pressure → metamorphic rock → can be re-melted to magma, completing the cycle.');
