-- 20 Post-UTME Islamic Religious Studies (IRS) Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('irs','ALL','The five pillars of Islam (Arkan al-Islam) are:','Shahada, Salat, Zakat, Sawm, and Hajj','Shahada, Zakat, Sawm, Hajj, and Jihad','Iman, Salat, Zakat, Sawm, and Hajj','Tawhid, Salat, Sawm, Hajj, and Du''a','A','The Five Pillars of Islam are: (1) Shahada (Declaration of faith), (2) Salat (Prayer — five times daily), (3) Zakat (Almsgiving), (4) Sawm (Fasting during Ramadan), and (5) Hajj (Pilgrimage to Makkah — once in a lifetime if able).'),

('irs','ALL','The "Shahada" (Islamic declaration of faith) states:','There is no god but Allah, and Isa (Jesus) is the servant of Allah','There is no god but Allah, and Muhammad is the Messenger of Allah (La ilaha illa Allah, Muhammadun rasulullah)','Allah is One, and the Quran is His eternal word','I bear witness that Muhammad is the Prophet of the last days','B','The Shahada is the first pillar: "Ash-hadu an la ilaha ill-Allah, wa ash-hadu anna Muhammadan rasulullah" — "I bear witness that there is no god but Allah, and I bear witness that Muhammad is the messenger of Allah." Reciting it with sincerity and understanding makes one a Muslim.'),

('irs','ALL','According to Islamic belief, the Quran was first revealed to Prophet Muhammad (SAW) in:','The city of Madinah, during the Hijra','The cave of Hira on Mount Nur, near Makkah, during the month of Ramadan','Jerusalem, during the Night Journey (Isra'' wal Mi''raj)','The Masjid al-Haram in Makkah','B','The first revelation (Surah Al-Alaq 96:1–5) was revealed to Prophet Muhammad in the Cave of Hira on Mount Nur near Makkah in the month of Ramadan, when the Angel Jibreel (Gabriel) came to him and commanded: "Read (Iqra'')!"'),

('irs','ALL','The "Hijra" in Islamic history refers to:','The pilgrimage of Muslims to Makkah','The Prophet Muhammad''s migration from Makkah to Madinah in 622 CE — the event from which the Islamic (Hijri) calendar is calculated','The Night Journey (Isra'') of the Prophet from Makkah to Jerusalem','The Prophet''s first revelation in the Cave of Hira','B','The Hijra (622 CE) was the Prophet''s migration from Makkah (where Muslims faced persecution) to Yathrib (renamed Madinah al-Nabi). It marks the beginning of the Islamic calendar (1 AH) and the establishment of the first Muslim community-state.'),

('irs','ALL','In Islamic jurisprudence (Fiqh), the primary sources of Islamic law (Sharia) are:','Only the Quran and the consensus of scholars (Ijma)','The Quran, the Sunnah (Hadith), Ijma (consensus), and Qiyas (analogical reasoning)','The Quran, the Bible, and the Torah','The Quran and the personal opinions of Muslim rulers','B','The four principal sources of Islamic law (usul al-fiqh) are: (1) Quran (primary), (2) Sunnah/Hadith (Prophet''s sayings and practices), (3) Ijma (scholarly consensus), and (4) Qiyas (analogical reasoning from known cases to new ones).'),

('irs','ALL','The Night Journey (Isra'' wal Mi''raj) is theologically significant in Islam primarily because:','It was when the Prophet received the Quran for the first time','During this journey, the five daily prayers (Salat) were ordained for Muslims, and the Prophet was taken through the heavens, meeting previous prophets','It marked the Prophet''s migration to Madinah','It was when the Prophet defeated the polytheists at the Battle of Badr','B','The Isra'' (night journey from Makkah to Jerusalem) and Mi''raj (ascent through the heavens) — during which the Prophet met previous prophets and Allah prescribed the five daily prayers, initially fifty, reduced to five — is a miraculous event affirming the Prophet''s special status.'),

('irs','ALL','The concept of "Tawhid" in Islamic theology refers to:','The belief in all the prophets and messengers of Allah','The absolute oneness and uniqueness of Allah — the central and most fundamental doctrine of Islam','The belief in the Day of Judgment and resurrection','The practice of regular prayer as the connection between the believer and Allah','B','Tawhid (Divine Unity/Oneness) is the cornerstone of Islamic theology — the uncompromising belief that Allah is One, without partner, associate, offspring, or comparable. Shirk (associating partners with Allah) is the gravest sin in Islam.'),

('irs','ALL','The "Sunnah" of the Prophet Muhammad (SAW) refers to:','The written text of the Quran as compiled by Uthman ibn Affan','The Prophet''s words, actions, approvals, and characteristics — which serve as a model for Muslim life and are the second primary source of Islamic law','The consensus of scholars on matters of Islamic law and practice','The collection of narrations about the Companions (Sahaba) of the Prophet','B','The Sunnah comprises the Prophet''s sayings (Hadith), actions (Af''al), and tacit approvals (Taqrir) as recorded in Hadith collections — it elaborates, explains, and complements the Quran, providing detailed guidance for all aspects of Muslim life.'),

('irs','ALL','Zakat (the third pillar of Islam) is an obligatory annual alms-giving on Muslims who possess:','Any amount of wealth, regardless of how little','Wealth meeting or exceeding the Nisab threshold (minimum taxable amount) for one full lunar year, typically calculated at 2.5% of savings and investments','Only inherited wealth and agricultural produce','Only gold and silver, with no obligation on cash or business assets','B','Zakat is obligatory on Muslims whose wealth (savings, gold, silver, trade goods) exceeds the Nisab (minimum threshold, equivalent to 85g of gold or 595g of silver) for one year — at a rate of 2.5% for most categories of wealth.'),

('irs','ALL','The Battle of Badr (2 AH / 624 CE) was significant in early Islamic history because:','It was the first major military victory of the Muslims over the Quraysh of Makkah, despite being significantly outnumbered — strengthening the Muslim community','It was when Muslims first received permission to engage in armed struggle (Jihad)','It led directly to the conquest of Makkah (Fath Makkah)','It was the last battle fought by the Prophet personally','A','The Battle of Badr (Ramadan, 2 AH): approximately 313 ill-equipped Muslims defeated a well-armed Quraysh force of ~1,000. This decisive victory consolidated the position of the Muslim state in Madinah and is referred to in the Quran (3:123).'),

('irs','ALL','The Quran consists of how many chapters (Surahs) and verses (Ayahs)?','99 Surahs and 4,000 Ayahs','114 Surahs and 6,236 Ayahs','120 Surahs and 6,000 Ayahs','86 Surahs and 5,000 Ayahs','B','The Quran consists of 114 Surahs (chapters) of varying length, containing 6,236 Ayahs (verses). The longest Surah is Al-Baqarah (286 verses); the shortest are Al-Kawthar, Al-Asr, and Al-Nasr (3 verses each).'),

('irs','ALL','In Islamic theology, the "Six Articles of Iman" (Faith) include belief in:','Allah, the Angels, the Books, the Prophets, the Day of Judgment, and Divine Decree (Qadar)','Allah, Muhammad, the Quran, Makkah, Paradise, and the Angels','Tawhid, Salat, Zakat, Sawm, Hajj, and Jihad','Allah, Jibreel, the Quran, the Ka''ba, the Companions, and the Day of Judgment','A','The Six Pillars of Iman (Islamic faith) are belief in: (1) Allah, (2) His Angels, (3) His Books (Quran, Torah, Injeel, Zabur, etc.), (4) His Prophets and Messengers, (5) the Last Day (Yawm al-Qiyama), and (6) Divine Decree (Al-Qadar — both good and bad).'),

('irs','ALL','The "Hajj" pilgrimage is obligatory for every Muslim who is:','A practising Muslim regardless of financial or physical ability','Physically and financially able to undertake the journey — it is required once in a lifetime','A male Muslim who has reached the age of majority','Any Muslim who has performed Umrah at least twice','B','Hajj (the annual pilgrimage to Makkah in the month of Dhul Hijjah) is obligatory once in a lifetime for every Muslim who is physically able (in health) and financially capable (can afford the journey without incurring debt), male or female.'),

('irs','ALL','The "Rightly Guided Caliphs" (Khulafa'' al-Rashidun) in correct historical order were:','Umar, Abu Bakr, Uthman, Ali','Abu Bakr, Umar, Uthman, Ali ibn Abi Talib','Ali, Abu Bakr, Umar, Uthman','Uthman, Umar, Abu Bakr, Ali','B','The four Rightly Guided Caliphs who succeeded the Prophet (in order): (1) Abu Bakr al-Siddiq (632–634 CE), (2) Umar ibn al-Khattab (634–644 CE), (3) Uthman ibn Affan (644–656 CE), and (4) Ali ibn Abi Talib (656–661 CE).'),

('irs','ALL','The term "Ijma" in Islamic jurisprudence refers to:','The analogical reasoning used to derive rulings from the Quran and Sunnah','The consensus of qualified Islamic scholars (Ulama) on a legal or theological matter — the third source of Islamic law','Personal independent legal reasoning (ijtihad) by a qualified jurist','A specific Hadith narrated by multiple companions of the Prophet','B','Ijma is the unanimous consensus of qualified Muslim scholars (Ulama) of a particular era on a specific legal ruling — constituting the third source of Islamic law. A matter on which Ijma has been established carries significant legal authority.'),

('irs','ALL','The Umayyad Caliphate (661–750 CE) is historically notable for:','Being the first Islamic state, established immediately after the Prophet''s death','Expanding the Islamic empire to its greatest extent — from Spain and North Africa in the west to Central Asia and the borders of China and India in the east','Compiling the Quran into a standard written text','Being a period of theological scholarship and the codification of Islamic law','B','Under the Umayyads (capital: Damascus), the Islamic empire reached its greatest geographical extent — Spain (711 CE), North Africa, Persia, Central Asia. This was a period of rapid military expansion, though also of political controversy and the Sunni-Shia split.'),

('irs','ALL','The "Abbasid Caliphate" (750–1258 CE) is particularly associated with:','Military conquest and expansion of the Islamic world','The Golden Age of Islamic civilisation — a period of remarkable achievements in science, medicine, mathematics, philosophy, and the arts','The establishment of the Hajj route and pilgrimage infrastructure','The codification and enforcement of strict Sharia law across the empire','B','The Abbasid era (capital: Baghdad) is known as the Golden Age of Islam — scholars like Al-Khwarizmi (algebra), Ibn Sina/Avicenna (medicine), Al-Biruni (astronomy), and Al-Ghazali (theology) produced works that profoundly influenced world civilisation.'),

('irs','ALL','In Islamic ethics, the concept of "Khalifa" (Vicegerency/Stewardship) holds that human beings:','Are the supreme masters of the Earth with no obligations to other creatures','Are Allah''s trustees/stewards on Earth, accountable for how they use and manage its resources — with obligations to preserve the environment and act justly','Have the right to exploit all natural resources for maximum economic benefit','Are spiritually superior to all creation and exempt from natural laws','B','The Quranic concept of Khalifa (2:30) — "I will create a vicegerent on Earth" — establishes that humans are Allah''s trustees (stewards), accountable for how they manage the Earth and its resources, implying environmental and social responsibility.'),

('irs','ALL','The "Hudud" punishments in Islamic criminal law are:','Discretionary punishments determined by the judge based on circumstances','Fixed punishments prescribed in the Quran and authentic Hadith for specific crimes (e.g., theft, adultery, false accusation) — carrying the highest level of certainty and fixed nature','Punishments for apostasy determined by the Caliph','Financial compensation (Diyya) paid to victims or their families','B','Hudud (singular: Hadd) are fixed penalties prescribed in the Quran and Sunnah for specified major crimes — including theft (amputation), adultery (flogging/stoning), false accusation (flogging), highway robbery, and apostasy. They require very high evidentiary standards.'),

('irs','ALL','Sufi Islam (Tasawwuf) is best described as:','A Shia sect that emphasises the authority of the Imam','The mystical dimension of Islam that emphasises inner spiritual development, the purification of the soul, and direct personal experience of Allah''s presence — through practices such as dhikr (remembrance), meditation, and spiritual discipline','A reformist movement that rejects all innovations (bid''a) in Islamic practice','A political movement seeking to establish a caliphate based on strict Sharia law','B','Sufism (Tasawwuf) is the inner, esoteric dimension of Islam focused on the spiritual path (tariqah) toward ma''rifa (gnosis/knowledge of Allah). Sufi orders (Tariqa, e.g., Qadiriyya, Tijaniyya) have been highly influential in spreading Islam across West Africa.');
