-- 100 Post-UTME Economics Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('economics','ALL','Which of the following best explains the concept of opportunity cost?','The monetary price of a good or service','The cost of the next best alternative foregone when a choice is made','The total cost of producing all units of a good','The sunk cost incurred in previous decisions','B','Opportunity cost is the value of the next best alternative sacrificed when a decision is made. It is a fundamental concept in economics.'),

('economics','ALL','In a perfectly competitive market, a firm is a price taker because:','It produces a unique product with no substitutes','It sells a homogeneous product among many sellers and buyers','The government fixes its price','It has significant market power','B','In perfect competition, firms produce identical (homogeneous) products; no single firm can influence market price, making each firm a price taker.'),

('economics','ALL','The income elasticity of demand for an inferior good is:','Positive and greater than 1','Positive and less than 1','Zero','Negative','D','For inferior goods, demand falls as income rises, giving a negative income elasticity of demand.'),

('economics','ALL','If the price elasticity of demand for a good is -0.4, the demand is described as:','Perfectly elastic','Elastic','Inelastic','Unit elastic','C','When |PED| < 1 (here 0.4), demand is inelastic — quantity demanded is relatively unresponsive to price changes.'),

('economics','ALL','The law of diminishing marginal utility states that:','Total utility falls as consumption increases','Marginal utility increases as more units are consumed','As more units of a good are consumed, each additional unit yields less satisfaction','Utility is constant across all units consumed','C','Diminishing marginal utility: each successive unit of a good consumed adds less utility than the previous unit, holding other things constant.'),

('economics','ALL','Which market structure is characterised by many firms selling differentiated products?','Perfect competition','Monopoly','Oligopoly','Monopolistic competition','D','Monopolistic competition features many firms, easy entry/exit, and differentiated (not homogeneous) products — e.g., restaurants, clothing brands.'),

('economics','ALL','A budget deficit occurs when:','Government revenue exceeds government expenditure','Government expenditure exceeds government revenue','Exports exceed imports','The money supply grows faster than output','B','A budget deficit arises when a government spends more than it collects in revenue in a given period.'),

('economics','ALL','The multiplier effect in Keynesian economics refers to:','The proportional increase in taxes following an increase in income','The process by which an initial change in spending leads to a larger final change in national income','The reduction in private investment caused by higher government borrowing','The rate at which the central bank creates money','B','The Keynesian multiplier shows that an initial injection of spending ripples through the economy, increasing national income by a multiple of the original injection.'),

('economics','ALL','What is the primary function of a commercial bank?','To print currency and control money supply','To accept deposits and grant loans to individuals and businesses','To regulate other financial institutions','To manage government accounts exclusively','B','Commercial banks primarily mobilise savings by accepting deposits and channel those funds to borrowers through loans, facilitating financial intermediation.'),

('economics','ALL','Under which condition will a monopolist maximise profit?','Where Average Revenue equals Average Cost','Where Marginal Revenue equals Marginal Cost','Where Total Revenue is maximised','Where price equals Marginal Cost','B','All profit-maximising firms — including monopolists — produce where MR = MC, the condition that equates the cost and benefit of the last unit produced.'),

('economics','ALL','The concept of "economies of scale" refers to:','Rising average costs as output increases','Falling average costs as output increases','The diseconomies arising from large firms','Constant returns to scale in the long run','B','Economies of scale occur when increasing output leads to a fall in long-run average cost, making larger production more efficient.'),

('economics','ALL','Which of the following is NOT a component of the current account in the balance of payments?','Trade in goods (visible trade)','Trade in services (invisible trade)','Foreign direct investment flows','Current transfers (e.g. remittances)','C','Foreign direct investment flows are recorded in the capital/financial account, not the current account of the balance of payments.'),

('economics','ALL','Stagflation is best described as:','A period of rapid economic growth with low inflation','High inflation occurring alongside high unemployment and low growth','A temporary fall in prices during a boom','Deflation caused by falling aggregate demand','B','Stagflation (stagnation + inflation) occurs when an economy faces simultaneously high inflation, high unemployment, and stagnant output — famously experienced in the 1970s.'),

('economics','ALL','The Phillips Curve illustrates a short-run trade-off between:','Inflation and economic growth','Unemployment and inflation','Interest rates and investment','Wages and productivity','B','The original Phillips Curve showed an inverse relationship between unemployment and inflation: lower unemployment tended to be associated with higher inflation and vice versa.'),

('economics','ALL','If the cross-price elasticity of demand between goods X and Y is positive, the goods are:','Complements','Substitutes','Independent goods','Giffen goods','B','Positive cross-price elasticity means when the price of Y rises, demand for X rises — the goods are substitutes (e.g., butter and margarine).'),

('economics','ALL','Which of the following best describes "consumer surplus"?','The profit earned by producers above their minimum supply price','The difference between the price a consumer is willing to pay and the price actually paid','The subsidy received by consumers from the government','The excess demand existing at a price below equilibrium','B','Consumer surplus is the welfare gain to buyers: the difference between their maximum willingness to pay and the actual market price they pay.'),

('economics','ALL','In national income accounting, GDP measured by the expenditure approach is:','C + I + G + (X - M)','C + S + T','W + R + I + P','C + I + G - (X + M)','A','GDP (expenditure approach) = Consumption (C) + Investment (I) + Government expenditure (G) + Net exports (X − M, i.e., exports minus imports).'),

('economics','ALL','A regressive tax is one in which:','The tax rate increases as income rises','The tax rate decreases as income rises','Every taxpayer pays the same absolute amount','The tax rate is proportional to income','B','A regressive tax takes a larger percentage of income from low-income earners than from high-income earners — e.g., flat-rate sales taxes.'),

('economics','ALL','The quantity theory of money is expressed as:','MV = PT','Y = C + I + G','AD = AS','S = I','A','The Fisher equation of exchange MV = PT (or MV = PY) states that the money supply (M) times velocity (V) equals the price level (P) times real output (T/Y).'),

('economics','ALL','Which of the following is an automatic stabiliser in fiscal policy?','Discretionary public works spending','Unemployment benefits and progressive income taxes','Central bank open market operations','Government capital budgets','B','Automatic stabilisers — like unemployment benefits and progressive taxes — automatically dampen economic fluctuations without deliberate policy action.'),

('economics','ALL','Absolute advantage in international trade means a country:','Produces a good at a lower opportunity cost than its trading partner','Can produce more of a good with the same resources than another country','Has a lower price level for all goods','Is self-sufficient in all traded goods','B','Absolute advantage (Adam Smith) means a country can produce a larger quantity of a good with the same inputs compared to another country.'),

('economics','ALL','Comparative advantage in trade theory was developed by:','Adam Smith','John Maynard Keynes','David Ricardo','Alfred Marshall','C','David Ricardo developed the theory of comparative advantage, showing that mutually beneficial trade is possible even when one country is absolutely better at producing everything.'),

('economics','ALL','The term "liquidity preference" in Keynesian theory refers to:','The desire of firms to hold physical capital','The preference of people to hold wealth in the form of money','A bank''s willingness to lend','The central bank''s preference for low interest rates','B','Keynes''s liquidity preference theory argues that people prefer to hold money (liquid asset) for transactions, precautionary, and speculative motives, which determines the interest rate.'),

('economics','ALL','Which of the following correctly defines "elasticity of supply"?','The degree to which quantity supplied changes in response to a change in consumer income','The responsiveness of quantity supplied to a change in the price of the good','The time it takes producers to respond to a price change','The cost of increasing output by one unit','B','Price elasticity of supply measures the percentage change in quantity supplied divided by the percentage change in price.'),

('economics','ALL','A production possibility frontier (PPF) that is concave to the origin illustrates:','Constant opportunity costs','Decreasing opportunity costs','Increasing opportunity costs','Zero opportunity costs','C','A concave (bowed-out) PPF reflects the law of increasing opportunity costs: as more of one good is produced, increasingly larger amounts of the other must be sacrificed.'),

('economics','ALL','Which of the following is the best definition of "inflation"?','A one-time rise in the price of a single commodity','A sustained and general increase in the price level over time','A fall in the purchasing power of foreign currency','A temporary shortage of goods in the market','B','Inflation is a persistent, economy-wide increase in the general price level, resulting in a decline in the purchasing power of money.'),

('economics','ALL','The "invisible hand" concept, introduced by Adam Smith, refers to:','Government intervention that guides market outcomes','The self-regulating nature of free markets in allocating resources efficiently','A hidden tax on market transactions','The role of multinational corporations in price setting','B','Adam Smith''s "invisible hand" metaphor describes how individuals pursuing their own self-interest in free markets unintentionally promote the economic well-being of society.'),

('economics','ALL','Which type of unemployment is associated with workers transitioning between jobs?','Structural unemployment','Cyclical unemployment','Frictional unemployment','Seasonal unemployment','C','Frictional unemployment occurs when workers are temporarily between jobs — searching for new employment or waiting to start a new position.'),

('economics','ALL','If the government imposes a price ceiling below the equilibrium price, the result is:','A surplus of the good','A shortage of the good','No change in the quantity demanded','An increase in producer surplus','B','A price ceiling set below equilibrium reduces quantity supplied and increases quantity demanded, creating a persistent shortage (excess demand).'),

('economics','ALL','The "crowding out" effect in economics refers to:','Private investment falling as government borrowing raises interest rates','Exports falling due to domestic inflation','Consumer spending rising when taxes are cut','The displacement of informal sector workers by formal sector growth','A','Crowding out occurs when government borrowing to finance a deficit pushes up interest rates, reducing private sector investment spending.'),

('economics','ALL','Which of the following is a characteristic of public goods?','Rivalry and excludability','Non-rivalry and non-excludability','High private profitability','Easily provided by the free market alone','B','Public goods are non-rival (one person''s use doesn''t reduce availability for others) and non-excludable (no one can be prevented from using them) — e.g., national defence.'),

('economics','ALL','In economics, a "merit good" is one that:','Is overproduced by the market due to positive externalities','The government believes is under-consumed at free market levels and therefore subsidises or provides','Is provided only to merit-based scholarship recipients','Has no external effects on third parties','B','Merit goods (e.g., education, healthcare) are deemed socially desirable; the market under-provides them because individuals undervalue their benefits, justifying government intervention.'),

('economics','ALL','The concept of "moral hazard" in economics refers to:','The ethical obligations of firms to society','The tendency for people to take greater risks when protected from the consequences','Market failure caused by asymmetric information before a transaction','Deliberate mispricing of goods by monopolists','B','Moral hazard arises when one party takes on more risk because they do not bear the full costs — e.g., insured drivers driving less carefully.'),

('economics','ALL','A monopsony is a market in which there is:','Only one seller','Only one buyer','A few dominant sellers','Many buyers competing with one seller','B','A monopsony is a market with a single buyer who has significant market power over sellers — e.g., a large company as the sole employer in a region.'),

('economics','ALL','Which of the following best describes "adverse selection"?','The process by which poorly managed firms are driven out of competitive markets','A problem of asymmetric information before a transaction, where one party has hidden information','Risk-taking encouraged by insurance coverage','The tendency for cartels to break down over time','B','Adverse selection occurs before a transaction when one party has private information the other lacks — e.g., high-risk individuals being more likely to buy insurance.'),

('economics','ALL','"Structural adjustment programmes" (SAPs) in developing countries typically include:','Increased government subsidies and trade barriers','Currency devaluation, privatisation, and removal of subsidies','Nationalisation of key industries','Expansion of public employment','B','SAPs, promoted by IMF/World Bank, involve devaluing the currency, privatising state enterprises, cutting subsidies, and liberalising trade to stabilise economies.'),

('economics','ALL','The term "Dutch Disease" in economics refers to:','An epidemic that disrupts agricultural production','The negative impact on other sectors of an economy caused by a boom in the natural resource sector','A disease affecting the Dutch banking system in the 1970s','Persistent deflation in a small open economy','B','Dutch Disease describes how a resource boom (e.g., oil discovery) appreciates the real exchange rate, making other export sectors (manufacturing, agriculture) less competitive.'),

('economics','ALL','Which of the following is NOT a function of money?','Medium of exchange','Store of value','Unit of account','Factor of production','D','The standard functions of money are: medium of exchange, store of value, unit of account, and standard of deferred payment. Money is not itself a factor of production.'),

('economics','ALL','In game theory, a "Nash Equilibrium" occurs when:','All players cooperate to maximise joint profits','Each player''s strategy is the best response to the strategies of all other players','One dominant player dictates the outcome to others','The government intervenes to stabilise the market','B','A Nash Equilibrium is a set of strategies where no player can benefit by unilaterally changing their strategy, given the strategies of all other players (named after John Nash).'),

('economics','ALL','The "Laffer Curve" illustrates the relationship between:','Unemployment and inflation','Tax rates and tax revenue','Money supply and inflation','Government spending and GDP growth','B','The Laffer Curve shows that both a 0% and a 100% tax rate yield zero revenue, implying there is an optimal tax rate that maximises revenue — the basis for supply-side tax cut arguments.'),

('economics','ALL','Which of the following best defines "economic rent"?','The payment for the use of land only','A payment to a factor of production above its transfer earnings (opportunity cost)','The profit earned by firms in monopolistic markets','Interest paid on borrowed capital','B','Economic rent is any payment to a factor of production exceeding its minimum supply price (transfer earnings / opportunity cost). It applies to any factor, not just land.'),

('economics','ALL','If the marginal propensity to consume (MPC) is 0.8, the value of the Keynesian multiplier is:','2','4','5','8','C','Multiplier = 1 / (1 − MPC) = 1 / (1 − 0.8) = 1 / 0.2 = 5.'),

('economics','ALL','The "accelerator theory" in macroeconomics states that:','Investment depends on changes in the level of national income','Consumption depends on the level of permanent income','Savings determine the long-run rate of economic growth','Higher interest rates accelerate investment','A','The accelerator principle suggests that net investment is proportional to the change in output (national income) — i.e., faster economic growth generates higher investment demand.'),

('economics','ALL','Which of the following is the correct definition of the "terms of trade"?','The legal terms governing international trade agreements','The ratio of a country''s export price index to its import price index','The tariff rates imposed on goods at the border','The difference between exports and imports in value terms','B','The terms of trade = (Export price index / Import price index) × 100. An improvement means exports buy more imports; a deterioration means they buy fewer.'),

('economics','ALL','Hyperinflation is most commonly caused by:','Excessive money supply growth, often to finance government deficits','A sudden rise in import prices','Slow economic growth combined with low unemployment','Tight monetary policy maintained for too long','A','Hyperinflation (very rapid price increases) is typically caused by governments printing excessive money to finance large deficits, dramatically reducing money''s value.'),

('economics','ALL','Under a fixed exchange rate system, a country with a balance of payments deficit must:','Allow its currency to depreciate freely','Use foreign reserves or adjust domestic policies to maintain the fixed rate','Increase tariffs on all imports','Default on its international debt obligations','B','With a fixed exchange rate, the central bank must intervene — selling foreign reserves or adjusting interest rates — to prevent the currency from depreciating below the fixed rate.'),

('economics','ALL','The "Gini coefficient" measures:','The rate of economic growth in a country','The degree of income or wealth inequality within a population','The level of government debt relative to GDP','The efficiency of tax collection','B','The Gini coefficient ranges from 0 (perfect equality) to 1 (maximum inequality) and is the most widely used measure of income distribution inequality.'),

('economics','ALL','Which of the following is an example of a negative production externality?','A beekeeper whose bees pollinate neighbouring farms','A factory releasing untreated effluent into a river','A new road that benefits surrounding property values','A firm training workers who later work for competitors','B','A negative production externality occurs when production imposes costs on third parties not involved in the transaction — e.g., industrial pollution affecting communities downstream.'),

('economics','ALL','The concept of "price discrimination" requires:','A perfectly competitive market with many sellers','Market power, the ability to separate markets, and no arbitrage between them','Government regulation fixing different prices for different groups','Identical elasticities of demand in all market segments','B','Price discrimination requires the seller to have market power, be able to identify and separate groups with different demand elasticities, and prevent resale between groups.'),

('economics','ALL','In the long run, a perfectly competitive firm earns:','Supernormal (economic) profit','Normal profit only (zero economic profit)','Losses due to price competition','Profit determined by government regulation','B','In long-run competitive equilibrium, free entry eliminates supernormal profits and free exit eliminates losses until all firms earn exactly normal profit (P = LAC).'),

('economics','ALL','Which theory of wages argues that workers are paid the value of their marginal product?','The wages fund theory','The iron law of wages','The marginal productivity theory of wages','The efficiency wage theory','C','Marginal productivity theory: in competitive markets, profit-maximising firms hire workers up to the point where the wage equals the value of the marginal product of labour.'),

('economics','ALL','The "cobweb model" in economics is used to explain price and quantity fluctuations in markets where:','Demand responds immediately to price changes but supply responds with a lag','Both supply and demand adjust instantly to price changes','Government price controls prevent market clearing','Firms collude to stabilise prices over time','A','The cobweb theorem applies to agricultural markets where supply decisions (planting) are made based on last period''s prices, causing cyclical price and quantity oscillations.'),

('economics','ALL','Which of the following statements about oligopoly is correct?','Firms in oligopoly act independently without regard to rivals','There is a high degree of interdependence among the few dominant firms','Entry is completely free and easy','Price equals marginal cost in equilibrium','B','Oligopoly is defined by the strategic interdependence of a few large firms — each firm must consider the likely reactions of rivals when making pricing and output decisions.'),

('economics','ALL','The "natural rate of unemployment" consists of:','Only seasonal unemployment','Frictional and structural unemployment','Cyclical and demand-deficient unemployment','Zero unemployment in the long run','B','The natural rate of unemployment (NAIRU) is the level consistent with stable inflation, comprising frictional (job search) and structural (skills mismatch) unemployment.'),

('economics','ALL','A "deflationary gap" exists when:','Aggregate demand exceeds the full employment level of output','Aggregate demand falls short of the full employment level of output','The price level is falling persistently','Government spending exceeds tax revenue','B','A deflationary (recessionary) gap occurs when actual aggregate demand is below the level needed to achieve full employment output, leaving the economy operating below capacity.'),

('economics','ALL','Which of the following would shift the aggregate demand curve to the right?','An increase in personal income taxes','A fall in consumer confidence','An increase in government expenditure','A rise in interest rates','C','An increase in government spending directly increases aggregate demand, shifting the AD curve rightward and raising output and the price level (assuming spare capacity).'),

('economics','ALL','The Solow growth model attributes long-run economic growth (per capita) primarily to:','Capital accumulation alone','Technological progress (total factor productivity)','Increases in labour force participation','Government investment in infrastructure','B','In the Solow model, capital accumulation faces diminishing returns. Only technological progress (exogenous) can sustain long-run per capita growth.'),

('economics','ALL','"Purchasing Power Parity" (PPP) theory states that:','Exchange rates adjust to equalise the prices of identical goods across countries','Interest rates equalise across countries in the long run','Trade balances determine exchange rates','The real exchange rate is always constant','A','PPP holds that in the long run, exchange rates adjust so that identical goods cost the same in different countries when expressed in a common currency — the "law of one price" applied globally.'),

('economics','ALL','Which of the following best defines "derived demand"?','Demand that arises from consumers'' desire for luxury goods','Demand for a factor of production that arises from the demand for the good it helps produce','Demand created by government subsidies','Demand that is independent of price changes','B','Derived demand refers to factor demand that stems from the demand for final goods and services — e.g., demand for steel is derived from demand for cars and construction.'),

('economics','ALL','A country''s Human Development Index (HDI) is primarily based on:','Per capita GDP alone','Life expectancy, education, and standard of living (GNI per capita)','Trade openness and foreign investment','Inflation and unemployment rates','B','The HDI, developed by UNDP, combines three dimensions: health (life expectancy), education (years of schooling), and standard of living (GNI per capita).'),

('economics','ALL','The "Permanent Income Hypothesis" was developed by:','John Maynard Keynes','Franco Modigliani','Milton Friedman','Robert Solow','C','Milton Friedman''s Permanent Income Hypothesis argues that consumption is based on expected long-run average (permanent) income, not current income, making the MPC out of transitory income small.'),

('economics','ALL','Which of the following is a consequence of a tariff imposed on imports?','Domestic consumers benefit from lower prices','Domestic producers are harmed by cheaper foreign competition','Government collects revenue and domestic producers gain, but consumers pay more','The balance of trade worsens automatically','C','A tariff raises the price of imports: domestic consumers face higher prices (welfare loss), domestic producers gain market share, and government earns tariff revenue.'),

('economics','ALL','"Creative destruction," a concept associated with Joseph Schumpeter, refers to:','Government spending that destroys inefficient firms','The process by which innovation continuously displaces old industries and firms with new ones','Environmental damage caused by industrial growth','The dismantling of state-owned enterprises','B','Schumpeter''s creative destruction describes capitalism''s dynamic process: new innovations (products, processes) constantly displace existing firms and industries, driving long-run growth.'),

('economics','ALL','In a two-sector economy (households and firms), the circular flow of income shows that:','Savings always exceed investment','National income equals national output equals national expenditure','Government spending is the primary driver of growth','Trade deficits reduce national income to zero','B','In the circular flow model, income generated in production (output) is paid to households (income) who spend it on goods (expenditure) — the three measures of GDP are equivalent.'),

('economics','ALL','The concept of "factor mobility" refers to:','The ease with which factors of production can be moved between uses or locations','The transport costs of moving goods across borders','The flexibility of exchange rates in the short run','The speed at which firms enter and exit markets','A','Factor mobility describes how readily land, labour, and capital can switch between industries, occupations, or geographic locations — high mobility improves economic efficiency.'),

('economics','ALL','Which of the following would most likely cause cost-push inflation?','An increase in consumer spending','A significant rise in oil prices','A reduction in interest rates','An increase in government transfer payments','B','Cost-push inflation is driven by rising production costs (e.g., oil price shocks, wage increases) that shift aggregate supply leftward, raising prices and reducing output simultaneously.'),

('economics','ALL','The "infant industry argument" for trade protection states that:','Old, declining industries need permanent tariffs to survive','New domestic industries may need temporary protection until they achieve scale economies and become competitive','All domestic industries are inherently more efficient than foreign ones','Trade restrictions should be permanent to maintain self-sufficiency','B','The infant industry argument justifies temporary tariffs or subsidies for newly established industries that need time to grow, achieve economies of scale, and become internationally competitive.'),

('economics','ALL','In the IS-LM model, the IS curve represents:','Equilibrium in the money market','The combinations of income and interest rate at which the goods market is in equilibrium','The long-run aggregate supply curve','Monetary policy effects on inflation','B','The IS curve (Investment-Savings) shows all combinations of interest rates and income (output) at which planned expenditure equals income — i.e., the goods market clears.'),

('economics','ALL','If nominal GDP grows by 8% and the GDP deflator rises by 5%, real GDP growth is approximately:','13%','3%','5%','2.86%','B','Real GDP growth ≈ Nominal GDP growth − Inflation = 8% − 5% = 3% (using the approximation method).'),

('economics','ALL','Which of the following is an instrument of monetary policy in Nigeria?','The annual budget','The monetary policy rate (MPR)','The tariff schedule','Corporate tax rates','B','The Central Bank of Nigeria (CBN) uses the Monetary Policy Rate (MPR) — the benchmark interest rate — as a primary instrument of monetary policy to influence credit, money supply, and inflation.'),

('economics','ALL','The "velocity of money" is defined as:','The speed at which the central bank prints new currency','The number of times a unit of money changes hands in an economy in a given period','The rate at which ATMs dispense cash','The annual growth rate of the money supply','B','Velocity of money (V) = Nominal GDP / Money Supply. It indicates how quickly money circulates through the economy, completing transactions.'),

('economics','ALL','Which of the following best describes "economic development"?','A short-term increase in real GDP','A sustained improvement in the standard of living, reduction in poverty, and structural transformation of an economy','A temporary boost in export revenues','Annual growth in the money supply','B','Economic development is a broader concept than growth, encompassing improvements in health, education, poverty reduction, inequality, and structural transformation alongside GDP increases.'),

('economics','ALL','A leftward shift of the supply curve, all else equal, results in:','Lower price and higher quantity','Higher price and lower quantity','Higher price and higher quantity','Lower price and lower quantity','B','A decrease in supply (leftward shift) reduces quantity supplied at every price; equilibrium moves to a higher price and lower quantity traded.'),

('economics','ALL','The "paradox of thrift" in Keynesian economics states that:','Higher saving by individuals leads to higher national saving and investment','When all households increase saving simultaneously, total savings and income in the economy may fall','Thrift is always beneficial to the long-run growth of an economy','Firms always invest more when households save more','B','The paradox of thrift: while saving is virtuous individually, if everyone saves more simultaneously, aggregate demand falls, reducing income and output, potentially leaving total savings unchanged or lower.'),

('economics','ALL','Which of the following is the most appropriate definition of "economic growth"?','An increase in government spending in an economy','A sustained increase in an economy''s productive capacity and real output over time','A temporary rise in the price of export commodities','An improvement in income distribution','B','Economic growth refers to a sustained increase in real GDP (or real GDP per capita) over time, reflecting an expansion in an economy''s productive capacity.'),

('economics','ALL','"Engel''s Law" in economics states that as income rises:','The proportion of income spent on luxury goods falls','The proportion of income spent on food tends to fall','The saving rate always increases proportionally','The demand for all goods increases at the same rate','B','Engel''s Law (Ernst Engel, 19th century) observes that as household income rises, the proportion of income spent on food declines, even if absolute food expenditure increases.'),

('economics','ALL','Which of the following actions by the Central Bank of Nigeria would reduce the money supply?','Buying government securities in the open market','Reducing the monetary policy rate','Increasing the cash reserve ratio (CRR)','Reducing the liquidity ratio','C','Increasing the CRR requires banks to hold more reserves, reducing the funds available for lending and thus contracting the money supply through the credit multiplier.'),

('economics','ALL','The "saving-investment identity" in a closed economy (no government) states that:','Savings always exceed investment','National saving always equals national investment in equilibrium','Investment is always greater than saving','Saving and investment are independent of each other','B','In a closed economy, the national income identity Y = C + I means that S = Y − C = I: all saving must be channelled into investment, so they are always equal ex post.'),

('economics','ALL','Which of the following is NOT a barrier to entry in a monopoly market?','Patent protection','Control over a key input','Large economies of scale enjoyed by the incumbent','Perfectly elastic demand for the product','D','Barriers to entry in monopoly include patents, control of essential resources, and significant cost advantages. A perfectly elastic demand curve is characteristic of perfect competition, not monopoly.'),

('economics','ALL','In the context of the Nigerian economy, "Dutch Disease" is most associated with:','Excessive imports of Dutch manufactured goods','The dominance of oil revenues crowding out non-oil sectors','Health epidemics reducing agricultural labour supply','Dutch foreign direct investment in manufacturing','B','Nigeria exhibits classic Dutch Disease: oil revenue dominance has led to an overvalued exchange rate and neglect of agriculture and manufacturing, weakening non-oil export competitiveness.'),

('economics','ALL','The "marginal rate of transformation" (MRT) on a PPF represents:','The rate at which consumers substitute one good for another','The opportunity cost of producing one more unit of a good in terms of the other good foregone','The ratio of prices in international trade','The slope of the indifference curve','B','The MRT on the PPF is the slope (rate at which one good must be sacrificed to gain one more unit of the other) — it equals the opportunity cost of production.'),

('economics','ALL','Which of the following is the main cause of market failure?','Government intervention in prices','The existence of externalities, public goods, information asymmetry, and market power','Perfect competition among many firms','Stable and well-defined property rights','B','Market failure arises when the free market fails to allocate resources efficiently, caused by externalities, public goods (non-excludable/non-rival), information failures, and monopoly power.'),

('economics','ALL','According to the "theory of second best," when one distortion exists in an economy:','Removing all other distortions always improves welfare','The best policy is to address the original distortion alone','Removing other distortions may or may not improve welfare','Free trade always restores efficiency','C','The theory of second best (Lipsey & Lancaster) shows that in the presence of one distortion, removing other distortions does not necessarily improve overall welfare — it may worsen it.'),

('economics','ALL','The "Heckscher-Ohlin theorem" predicts that countries export goods that:','Have the highest world market prices','Intensively use the factor of production with which the country is abundantly endowed','Are produced using the most advanced technology','Have the lowest domestic production costs in absolute terms','B','The Heckscher-Ohlin (H-O) theorem: countries export goods that use their abundant factor intensively (e.g., a labour-abundant country exports labour-intensive goods).'),

('economics','ALL','Which of the following correctly describes the "accelerator-multiplier interaction" in business cycle theory?','Government spending creates a multiplied increase in income with no investment effect','Changes in income generate investment (accelerator) which in turn is multiplied, amplifying economic fluctuations','Lower interest rates slow investment and reduce the multiplier','High unemployment reduces the multiplier but increases the accelerator','B','The interaction of the multiplier (spending increase → income increase) and accelerator (income increase → investment increase) can amplify business cycle booms and recessions.'),

('economics','ALL','The concept of "regulatory capture" refers to:','A government''s successful regulation of a dominant firm','The process by which a regulatory agency comes to serve the interests of the industry it regulates rather than the public','Environmental regulation that captures pollution externalities effectively','Market competition that displaces monopoly firms','B','Regulatory capture occurs when the regulated industry gains disproportionate influence over its regulator, causing it to act in the industry''s interest rather than the public interest.'),

('economics','ALL','Which of the following is a characteristic of a freely floating exchange rate system?','The central bank fixes the exchange rate and defends it with reserves','The exchange rate is determined solely by supply and demand in the foreign exchange market','Exchange rates adjust by small amounts within a government-set band','A common currency is shared by multiple countries','B','Under a freely floating (flexible) exchange rate system, market forces of supply and demand determine exchange rates with no government or central bank intervention.'),

('economics','ALL','"Transfer payments" in national income accounting are:','Payments for goods and services included in GDP','Government payments (e.g., pensions, unemployment benefits) for which no current productive activity is received','Payments between countries for trade in services','Interest payments made by firms to their lenders','B','Transfer payments (welfare benefits, pensions, subsidies to individuals) are excluded from GDP because they do not represent production of goods or services — they merely redistribute income.'),

('economics','ALL','According to the "Stolper-Samuelson theorem," opening to free trade:','Benefits all factors of production in all trading countries','Benefits the abundant factor and harms the scarce factor in each country','Has no distributional consequences within countries','Raises wages in all sectors simultaneously','B','The Stolper-Samuelson theorem (derived from H-O): free trade raises the real return to the abundant factor and reduces the real return to the scarce factor in each country.'),

('economics','ALL','Which of the following correctly defines "seigniorage"?','The profit earned by the government from issuing currency (face value minus printing cost)','The tax levied on imported luxury goods','The fee charged by commercial banks for banking services','The interest earned on foreign exchange reserves','A','Seigniorage is the revenue a government earns by issuing money — the difference between the face value of currency and the cost of producing it, effectively a tax on money holders.'),

('economics','ALL','In welfare economics, the "Pareto improvement" criterion states that a change is beneficial if:','Total national income increases even if some individuals are worse off','At least one person is made better off without making anyone else worse off','The majority of the population gains, regardless of losses to others','GDP per capita rises above the previous level','B','A Pareto improvement is a reallocation that makes at least one person better off without harming anyone. Pareto optimality is reached when no further Pareto improvements are possible.'),

('economics','ALL','The "J-curve effect" in international economics describes:','The relationship between income and consumption over time','The initial worsening of a trade balance following currency depreciation, before it improves','The impact of rising interest rates on investment spending','The time lag between investment and economic growth','B','After a currency depreciation, the trade balance initially worsens (import costs rise before export volumes adjust) then improves as trade volumes respond — tracing a J-shaped path over time.'),

('economics','ALL','Which of the following best describes "financial crowding out"?','The displacement of private investment by higher government borrowing, raising interest rates','Monopoly banks restricting credit to small firms','The government buying out failing private companies','Commercial banks diverting funds to foreign investment','A','Financial crowding out: when the government borrows heavily to fund deficits, it competes with the private sector for loanable funds, driving up interest rates and reducing private investment.');
