-- 20 Post-UTME Literature in English Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('literature','ALL','In Chinua Achebe''s "Things Fall Apart," the title is derived from a poem by:','William Shakespeare','William Butler Yeats','T.S. Eliot','John Keats','B','The title "Things Fall Apart" is taken from W.B. Yeats'' poem "The Second Coming" (1919): "Things fall apart; the centre cannot hold; / Mere anarchy is loosed upon the world."'),

('literature','ALL','Which literary device is used when a writer addresses an absent or imaginary person or a personified abstract quality directly?','Alliteration','Apostrophe','Anaphora','Allusion','B','Apostrophe is the rhetorical device of directly addressing someone absent or dead, or a personified quality — e.g., "O Death, where is thy sting?" (1 Corinthians 15:55; also used in poetry).'),

('literature','ALL','The protagonist of Wole Soyinka''s play "Death and the King''s Horseman" is:','Elesin Oba','Pilkings','Iyaloja','Olunde','A','Elesin Oba, the king''s horseman, is the protagonist — he is expected to die ritually after the king, but his failure to do so is the central conflict of the play.'),

('literature','ALL','A "Petrarchan sonnet" differs from a "Shakespearean sonnet" primarily in its:','Number of lines','Rhyme scheme and division (octave + sestet vs. three quatrains + couplet)','Use of iambic pentameter','Subject matter, which must be religious','B','The Petrarchan sonnet has an octave (8 lines, rhyming abbaabba) and a sestet (6 lines). The Shakespearean sonnet has three quatrains (abab cdcd efef) and a concluding couplet (gg).'),

('literature','ALL','The narrative technique in which a story is told from the perspective of a character who has incomplete or unreliable knowledge is called:','Omniscient narration','Third-person limited narration','Unreliable narration','Stream of consciousness','C','An unreliable narrator is one whose credibility is compromised — the reader cannot fully trust their account, often revealing gaps between what the narrator says and what the story shows.'),

('literature','ALL','In Ngugi wa Thiong''o''s "A Grain of Wheat," the novel''s structure is shaped primarily by:','Linear chronology from pre-colonial to post-independence Kenya','A series of flashbacks centred on the period around Kenya''s independence (Uhuru) in 1963','The journey of a single hero from village to city','A mythological framework based on Gikuyu oral tradition','B','Ngugi structures the novel around Kenya''s independence day, using complex flashbacks to reveal characters'' roles during the Mau Mau Emergency — themes of betrayal, heroism, and guilt dominate.'),

('literature','ALL','The term "dramatic irony" occurs when:','The audience shares the same knowledge as all characters on stage','The audience knows something crucial that one or more characters do not','A character says the opposite of what they mean','The playwright uses comedy to address a serious theme','B','Dramatic irony is when the audience possesses information that a character lacks — creating tension, pathos, or humour from the gap between what the character believes and what the audience knows.'),

('literature','ALL','Which of the following is an example of "in medias res" as a narrative technique?','Beginning the story with the birth of the protagonist','Opening the story in the middle of the action, with earlier events revealed through flashback','Concluding the story before the central conflict is resolved','Introducing all characters before the plot begins','B','In medias res (Latin: "in the middle of things") is the technique of beginning a narrative at a dramatic mid-point, with backstory introduced later — used in Homer''s Iliad and Odyssey.'),

('literature','ALL','In J.P. Clark''s poem "Night Rain," the dominant mood is:','Terror and desolation','Warmth, security, and the intimacy of family life during a tropical rainstorm','Anger at the destructive power of nature','Nostalgia for a lost childhood','B','Clark''s "Night Rain" evokes the warm security of a family sheltering together during a tropical rainstorm in the Niger Delta — a lyrical, sensory poem of domestic intimacy and the rhythms of nature.'),

('literature','ALL','The term "catharsis" as used by Aristotle in his "Poetics" refers to:','The moment of highest tension in a tragic play','The purging or purification of emotions of pity and fear in the audience through witnessing tragedy','The moral lesson that a play teaches the audience','The final resolution of all conflicts at the end of a drama','B','Aristotle (Poetics, c.335 BC) argued tragedy achieves catharsis — the emotional purging or purgation of pity and terror in the audience — as a key aesthetic and psychological function of tragic drama.'),

('literature','ALL','Flora Nwapa''s "Efuru" is significant in African literature primarily because:','It was the first Nigerian novel written in the English language','It was the first novel published by an African woman writer in English, centering the experience of an Igbo woman','It introduced the stream-of-consciousness technique to African fiction','It won the Nobel Prize for Literature','B','Flora Nwapa''s Efuru (1966, Heinemann) is widely considered the first novel published by an African woman in English, focusing on a strong, independent Igbo woman — pioneering women-centred African fiction.'),

('literature','ALL','A "foil" character in drama or fiction is one who:','Is the main antagonist opposing the hero','Contrasts with another character (usually the protagonist) to highlight certain qualities','Provides comic relief in a tragic play','Represents the voice and values of the author','B','A foil is a character whose contrasting traits (personality, values, appearance) serve to highlight the qualities of another character — often the protagonist — by direct contrast (e.g., Laertes as a foil to Hamlet).'),

('literature','ALL','The literary movement known as "magical realism" is most closely associated with:','The realistic depiction of urban poverty in industrial England','The seamless blending of magical or fantastical elements into an otherwise realistic narrative world','Pure fantasy with no realistic elements','The documentary style of reporting real events as fiction','B','Magical realism (associated with Gabriel García Márquez, Chinua Achebe in some works, Ben Okri) integrates magical elements into an otherwise realistic setting as though they are normal — a hallmark of much postcolonial African and Latin American fiction.'),

('literature','ALL','In Shakespeare''s "Hamlet," the famous soliloquy beginning "To be, or not to be" is a meditation on:','Hamlet''s plan to avenge his father''s murder','The question of whether to endure suffering or end one''s life, and the fear of what comes after death','Hamlet''s love for Ophelia','The corruption of the Danish court','B','"To be, or not to be" (Act III, Scene 1) is Hamlet''s contemplation of whether existence (enduring life''s suffering) or non-existence (death) is preferable — halted by uncertainty about what death brings.'),

('literature','ALL','The narrative style called "stream of consciousness" is best described as:','A first-person narrator recounting events in strict chronological order','A technique that attempts to capture the continuous, unedited flow of a character''s thoughts, perceptions, and feelings','A third-person omniscient narrator who comments on all characters','A technique where each chapter is narrated by a different character','B','Stream of consciousness (associated with James Joyce, Virginia Woolf) attempts to render the continuous, associative flow of a character''s inner mental life — unfiltered, non-linear, and often impressionistic.'),

('literature','ALL','Ola Rotimi''s play "The Gods Are Not to Blame" is an adaptation of:','Wole Soyinka''s "Death and the King''s Horseman"','Sophocles'' "Oedipus Rex," set in a Yoruba context','Shakespeare''s "King Lear"','Chinua Achebe''s "Things Fall Apart"','B','Ola Rotimi transposed Sophocles'' Oedipus Rex into a Yoruba setting in "The Gods Are Not to Blame" (1971), exploring themes of fate, prophecy, and free will through an African cultural lens.'),

('literature','ALL','Which of the following best defines "theme" in literature?','The sequence of events that make up the plot of a story','The central idea, message, or insight about human life that a literary work explores','The setting (time and place) in which a story unfolds','The perspective from which a story is narrated','B','Theme is the underlying central idea or message of a literary work — the abstract concept (e.g., love, betrayal, power, identity) that the author explores through the characters, plot, and imagery.'),

('literature','ALL','In poetry, "enjambment" refers to:','A pause at the end of a line of verse, completing a grammatical unit','The continuation of a sentence or phrase beyond the end of a line without a pause, running into the next line','The repetition of vowel sounds within a line of poetry','The use of a dash to create a sudden break in thought','B','Enjambment (French: "straddling") occurs when a sentence runs past the end of a line (and sometimes a stanza) without a grammatical pause, creating momentum and a sense of continuation.'),

('literature','ALL','The setting of Cyprian Ekwensi''s novel "Jagua Nana" is primarily:','Rural eastern Nigeria during the colonial period','Urban Lagos in the 1950s, focusing on the underworld, prostitution, and city life','The northern savannah during the pre-colonial era','The Niger Delta during the oil boom','B','Ekwensi''s Jagua Nana (1961) is set in Lagos''s lively, seedy underworld of the 1950s, following the free-spirited Jagua through bars, politics, and romance — a classic of African urban fiction.'),

('literature','ALL','The concept of "the willing suspension of disbelief," coined by Samuel Taylor Coleridge, refers to:','A reader''s demand that all fiction be entirely realistic','The reader''s temporary acceptance of impossible or fantastical elements in a literary work in order to engage with and enjoy it','The author''s technique of disguising fantasy as reality','The critical practice of rejecting all supernatural elements in literature','B','Coleridge (Biographia Literaria, 1817) coined the phrase to describe the aesthetic contract by which readers willingly set aside disbelief in impossible events to engage imaginatively with a literary work.');
