-- 20 Post-UTME Commerce Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('commerce','ALL','Commerce can best be defined as all activities concerned with:','The production of goods in a factory','The buying and selling of goods and services, and all activities that facilitate such exchange (trade and aids to trade)','The transportation of goods from one country to another','The banking and financial services sector only','B','Commerce encompasses trade (buying and selling) and all aids to trade — banking, insurance, warehousing, transportation, advertising, and communication — that facilitate the exchange of goods and services.'),

('commerce','ALL','The term "chain of distribution" refers to:','The process of manufacturing a product from raw materials to finished goods','The path through which goods move from the producer to the final consumer, through various intermediaries','The network of banks that finance trade transactions','The sequence of quality checks in a production process','B','The chain (channel) of distribution is the route goods take from producer → wholesaler → retailer → consumer. It includes all the intermediaries (middlemen) involved in moving goods from producers to consumers.'),

('commerce','ALL','A "bill of exchange" in international trade is best described as:','A government document certifying the quality of exported goods','An unconditional written order by one party (drawer) directing another (drawee) to pay a specified sum to a named payee on a fixed future date','An insurance policy covering goods in transit','A document issued by a shipping company confirming receipt of goods for shipment','B','A bill of exchange is a negotiable instrument: an unconditional written order requiring the drawee to pay a fixed sum to the payee either on demand or on a specified future date — widely used in trade credit.'),

('commerce','ALL','The primary function of a "wholesaler" in the chain of distribution is to:','Sell goods directly to final consumers in small quantities','Buy goods in bulk from manufacturers and sell in smaller quantities to retailers, breaking bulk and providing storage','Manufacture goods and distribute them directly to consumers','Provide credit and banking services to producers','B','Wholesalers buy in bulk from manufacturers (gaining economies of scale), break bulk into smaller lots, store goods, extend credit to retailers, and provide market information — serving as the critical link between producer and retailer.'),

('commerce','ALL','An "entrepôt" trade centre is one that:','Manufactures goods for export only','Imports goods for the purpose of re-exporting them, often with little or no processing, serving as a trading hub','Provides only banking and financial services to traders','Is a free trade zone where no customs duties are charged on domestic sales','B','An entrepôt is a port or trading centre that imports goods primarily to re-export them — acting as a regional trade hub. Historical examples include Singapore, Hong Kong, and Rotterdam.'),

('commerce','ALL','The "letter of credit" (L/C) in international trade primarily functions to:','Certify that a shipment has been inspected and meets quality standards','Provide a guarantee from the importer''s bank to pay the exporter when specified documents proving shipment are presented','Insure goods against loss or damage during transit','Authorise a customs broker to clear goods on behalf of the importer','B','A letter of credit is a bank-issued guarantee: the importer''s bank undertakes to pay the exporter the agreed amount upon presentation of specified shipping documents — reducing the risk of non-payment in international trade.'),

('commerce','ALL','Which of the following is an example of "invisible trade" in international commerce?','Export of crude oil','Import of machinery','Tourism earnings and insurance services received from abroad','Import of food commodities','C','Invisible trade (trade in services) includes tourism, financial services, insurance, shipping, and remittances — non-physical transactions that generate foreign exchange earnings or outflows, as opposed to visible trade in physical goods.'),

('commerce','ALL','A "sole proprietorship" as a form of business organisation is characterised by:','Limited liability for the owner and perpetual succession','Ownership and management by one person, with unlimited personal liability for all business debts','Ownership shared equally among at least two directors','Shares freely traded on the stock exchange','B','A sole trader (sole proprietorship) is owned and controlled by one person who has unlimited liability — personal assets can be seized to settle business debts. It is the simplest and most common form of business organisation.'),

('commerce','ALL','The "memorandum of association" of a company sets out:','The internal rules governing the management of the company (meetings, voting, etc.)','The company''s name, registered address, objects (purpose), and the extent of shareholders'' liability — its constitution in relation to the outside world','The salaries and benefits of company directors','The conditions under which the company may be dissolved','B','The Memorandum of Association is the constitutional document defining a company''s relationship with the outside world: its name, registered office, objects clause, liability clause, and capital clause — now simplified under modern company law.'),

('commerce','ALL','The term "e-commerce" refers to:','The use of computers for managing company accounts and payroll only','The buying, selling, and exchange of goods, services, and information over electronic networks, primarily the internet','Electronic banking services provided by commercial banks','The use of electronic mail for business communication','B','E-commerce (electronic commerce) encompasses all commercial transactions conducted electronically over the internet — including B2C (e.g., Jumia, Amazon), B2B, C2C (e.g., eBay), and digital service delivery.'),

('commerce','ALL','Which of the following is NOT a function of the Central Bank of Nigeria (CBN)?','Issuing currency (legal tender)','Acting as the government''s banker and lender of last resort','Accepting deposits and making loans directly to the general public','Regulating and supervising the banking system','C','The CBN is the apex monetary authority — it issues currency, manages monetary policy, supervises banks, and acts as banker to the government. Accepting deposits and making loans to the general public is the function of commercial banks, not the central bank.'),

('commerce','ALL','The "articles of association" of a company govern:','The company''s external objects and purposes','The internal management rules — covering meetings, voting rights, appointment of directors, dividends, and shares','The conditions for the winding up of the company by the courts','The terms of employment of company employees','B','The Articles of Association contain the internal regulations governing the company''s management — covering general meetings, voting procedures, directors'' powers, dividend policy, and share transfer rules.'),

('commerce','ALL','"Factoring" as a financial service involves:','A manufacturer outsourcing production to a third-party contractor','A business selling its trade receivables (debtors) to a factor (financial institution) at a discount in exchange for immediate cash','A bank providing a mortgage loan secured on business property','An insurer guaranteeing payment in the event of debtor default','B','Factoring: a business sells its accounts receivable (invoices) to a factoring company at a discount, receiving immediate cash. The factor then collects payment from the debtors — improving the business''s cash flow.'),

('commerce','ALL','The "terms of trade" in commerce refer to:','The legal contract governing a transaction between a buyer and seller','The ratio of export prices to import prices, indicating the purchasing power of exports in terms of imports','The standard payment terms (e.g., 30 days credit) extended to buyers','The terms and conditions printed on a commercial invoice','B','Terms of trade = (Export Price Index / Import Price Index) × 100. An improvement means a country can import more with the same export revenue; a deterioration means exports buy fewer imports.'),

('commerce','ALL','Which of the following best describes a "cooperative society"?','A business formed to earn maximum profit for its shareholders','An autonomous association of persons voluntarily united to meet common economic, social, and cultural needs through a jointly owned and democratically controlled enterprise','A government-owned corporation established by Act of Parliament','A partnership of professionals such as lawyers or doctors','B','A cooperative society is a member-owned enterprise governed democratically (one member, one vote) — formed to serve members'' economic needs (purchasing, production, credit, marketing) rather than to maximise profit for external shareholders.'),

('commerce','ALL','A "public limited company" (PLC) differs from a "private limited company" in that:','A PLC has unlimited liability while a private company has limited liability','A PLC may offer its shares to the general public on a stock exchange, while a private company may not','A PLC is owned by the government while a private company is owned by individuals','A PLC has no minimum capital requirement while a private company does','B','A PLC (Public Limited Company) can invite the general public to subscribe for its shares through a stock exchange — requiring higher transparency and regulatory compliance. A private limited company restricts share transfer and cannot make public offers.'),

('commerce','ALL','The role of "insurance" as an aid to trade is primarily to:','Provide financing for the purchase of goods on credit','Transfer and spread the financial risk of loss (from fire, theft, accident, etc.) from the insured to the insurer, enabling businesses to operate with greater confidence','Facilitate the storage of goods until they are needed','Provide market intelligence and price information to traders','B','Insurance enables businesses to transfer the financial risk of potential losses to an insurer in exchange for a premium — protecting against fire, theft, transit damage, and liability, thus making trade and investment less risky.'),

('commerce','ALL','A "debenture" is best described as:','A share in the ownership of a company carrying voting rights','A long-term loan instrument issued by a company, acknowledging debt and promising to pay fixed interest regardless of profit, often secured on company assets','A government bond issued to finance public expenditure','A form of short-term bank overdraft','B','A debenture is a fixed-interest loan certificate issued by a company to raise long-term debt capital. Debenture holders are creditors (not owners), receive fixed interest regardless of profit, and are repaid before shareholders on liquidation.'),

('commerce','ALL','The "consumer price index" (CPI) is used primarily to measure:','The total output (GDP) of an economy in a given year','The average change in prices paid by consumers for a basket of goods and services over time — a key indicator of inflation','The total value of goods exported by a country in a year','The productivity of workers in the manufacturing sector','B','The CPI measures inflation from the consumer''s perspective by tracking price changes of a fixed "basket" of goods and services representative of typical household expenditure — used to adjust wages, pensions, and government benefits.'),

('commerce','ALL','In commerce, "hire purchase" (HP) differs from outright credit purchase in that:','The buyer takes immediate full ownership of the goods upon signing the HP agreement','Ownership of the goods passes to the buyer only after the final instalment is paid — the seller retains title until then','The buyer pays no interest on the deferred amount','Hire purchase is available only for industrial machinery','B','Under hire purchase, the buyer takes immediate possession but ownership (title) remains with the seller until the final instalment is paid. If the buyer defaults, the seller can repossess the goods — unlike a straightforward credit sale where title passes immediately.');
