-- 100 Post-UTME Christian Religious Studies Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('crs','ALL','According to Genesis 1, on which day did God create the sun, moon, and stars?','First day','Third day','Fourth day','Sixth day','C','Genesis 1:14–19 records that God created the lights in the firmament — the sun, moon, and stars — on the fourth day of creation.'),

('crs','ALL','What was the sin of Adam and Eve in the Garden of Eden, as described in Genesis 3?','They worshipped a false god','They ate the forbidden fruit from the tree of the knowledge of good and evil','They murdered each other','They disobeyed God by leaving the Garden','B','Genesis 3:6 records that Eve took fruit from the tree of the knowledge of good and evil (which God had forbidden in 2:17) and ate it, giving some also to Adam — the original act of disobedience.'),

('crs','ALL','Who was the first son of Adam and Eve mentioned in the Bible?','Abel','Seth','Cain','Enoch','C','Genesis 4:1 records Cain as the firstborn son of Adam and Eve. Abel was the second (Genesis 4:2), and Seth was born later after Cain killed Abel (Genesis 4:25).'),

('crs','ALL','What was the sign of the covenant God made with Noah after the flood?','Circumcision','A burning torch','A rainbow','A pillar of cloud','C','Genesis 9:13–17 records that God set a rainbow in the clouds as the sign of the covenant (promise never again to destroy all life by a flood) between God and all living creatures.'),

('crs','ALL','According to Genesis 12, what was the primary command God gave to Abraham when He called him?','To build an altar on Mount Moriah','To leave his country, his people, and his father''s household and go to the land God would show him','To circumcise all males in his household','To offer his son as a burnt offering','B','Genesis 12:1 records God''s call: "Go from your country, your people and your father''s household to the land I will show you." God promised to make Abraham a great nation and bless all peoples through him.'),

('crs','ALL','The sign of the covenant between God and Abraham was:','The Sabbath rest','A rainbow in the sky','Circumcision','The Passover meal','C','Genesis 17:10–11 records God instituting circumcision as the sign of the covenant between Himself and Abraham and his descendants — every male was to be circumcised as a sign of the covenant.'),

('crs','ALL','In Genesis 22, God tested Abraham by commanding him to:','Sacrifice his son Isaac on Mount Moriah','Leave Canaan and go to Egypt','Build an altar at Bethel','Drive out Hagar and Ishmael','A','Genesis 22:1–2 records God commanding Abraham: "Take your son, your only son, whom you love — Isaac — and go to the region of Moriah. Sacrifice him there as a burnt offering." God intervened before the sacrifice and provided a ram.'),

('crs','ALL','How did Jacob obtain Esau''s birthright, according to Genesis 25?','He fought Esau in a wrestling match','He persuaded Esau to sell it for a meal of bread and lentil stew','He stole it while Esau slept','His mother Rebekah arranged a legal transfer','B','Genesis 25:29–34 records that Esau, famished after returning from the field, sold his birthright to Jacob for bread and a bowl of lentil stew, despising his birthright.'),

('crs','ALL','The burning bush episode in Exodus 3 was significant because:','It demonstrated God''s power to destroy Egypt','God revealed His name "I AM WHO I AM" and commissioned Moses to deliver Israel from Egypt','Moses received the Ten Commandments in the bush','God destroyed the Egyptian army with fire','B','Exodus 3:1–14 records God appearing to Moses in the burning bush, revealing His name YHWH ("I AM WHO I AM"), and commissioning Moses to lead Israel out of Egyptian slavery.'),

('crs','ALL','Which of the following was NOT one of the Ten Plagues of Egypt?','Locusts','Darkness','Earthquake','Death of the firstborn','C','The ten plagues (Exodus 7–12) were: blood, frogs, gnats/lice, flies, livestock disease, boils, hail, locusts, darkness, and death of the firstborn. An earthquake was not among them.'),

('crs','ALL','The Passover meal in Exodus 12 was instituted primarily to:','Celebrate Israel''s military victory over Egypt','Commemorate God''s deliverance of Israel from Egyptian slavery and the sparing of their firstborn','Mark the anniversary of Abraham''s covenant','Celebrate the building of the tabernacle','B','Exodus 12:14 establishes the Passover as a lasting ordinance to commemorate God passing over the Israelite houses (marked with blood) while striking down the firstborn of Egypt, the final plague that led to Israel''s release.'),

('crs','ALL','The Ten Commandments were given to Moses on:','Mount Carmel','Mount Sinai (Horeb)','Mount Zion','Mount Moriah','B','Exodus 19–20 records that God gave the Ten Commandments to Moses on Mount Sinai (also called Horeb in Deuteronomy), accompanied by thunder, lightning, and a thick cloud.'),

('crs','ALL','According to Deuteronomy 6:4–5, the greatest commandment in the Law was:','"You shall not murder"','Love the LORD your God with all your heart, soul, and strength','Keep the Sabbath holy','Honour your father and mother','B','The Shema (Deuteronomy 6:4–5): "Hear, O Israel: The LORD our God, the LORD is one. Love the LORD your God with all your heart and with all your soul and with all your strength." Jesus also cited this as the greatest commandment (Mark 12:30).'),

('crs','ALL','The Book of Joshua records the conquest of which city as the first major victory in Canaan?','Jerusalem','Ai','Jericho','Hebron','C','Joshua 6 records the miraculous fall of Jericho — the city walls collapsed after the Israelites marched around them for seven days, making it Israel''s first major conquest in Canaan.'),

('crs','ALL','According to the Book of Judges, what was Samson''s source of supernatural strength?','A divine oil poured on him','His long hair, which was never to be cut as part of his Nazirite vow','A special breastplate given by God','His faith in God alone','B','Judges 13:5 records that Samson was set apart as a Nazirite from birth; his hair was never to be cut. Judges 16:17 records that when his hair was shaved (by Delilah), his strength left him.'),

('crs','ALL','In the Book of Ruth, what was the significance of Boaz redeeming Ruth?','It fulfilled a prophecy about the Messiah''s birth','As a kinsman-redeemer (go''el), he married Ruth and preserved the family line of her deceased husband Elimelech, eventually leading to the lineage of David and Jesus','It established the institution of marriage in Israel','It made Ruth the first foreign convert to Judaism','B','Ruth 4 records Boaz acting as kinsman-redeemer (go''el) — buying back Elimelech''s land and marrying Ruth to preserve the family name. Ruth and Boaz became great-grandparents of David, placing Ruth in the Messianic lineage (Matthew 1:5).'),

('crs','ALL','What was King Saul''s major sin that led to God rejecting him as king, according to 1 Samuel 15?','Marrying a foreign woman','Failing to completely destroy the Amalekites as commanded by God, sparing King Agag and the best livestock','Worshipping idols at Bethel','Killing 85 priests at Nob','B','1 Samuel 15:8–9 records Saul sparing Agag and the best animals after God commanded total destruction of the Amalekites. Samuel rebuked him: "To obey is better than sacrifice" (v.22), and God rejected Saul as king.'),

('crs','ALL','According to 2 Samuel 11, David''s great sin involved:','Worshipping the Baals','Committing adultery with Bathsheba and arranging the death of her husband Uriah the Hittite','Refusing to build the Temple','Killing his brother Absalom','B','2 Samuel 11 records David committing adultery with Bathsheba (wife of Uriah) and then arranging Uriah''s death in battle to conceal the sin. Nathan the prophet later confronted David (2 Samuel 12).'),

('crs','ALL','The prophet Elijah challenged the prophets of Baal to a contest on:','Mount Sinai','Mount Zion','Mount Carmel','Mount Hermon','C','1 Kings 18:19–40 records Elijah''s contest with 450 prophets of Baal on Mount Carmel, where God sent fire to consume Elijah''s water-drenched sacrifice while Baal failed to respond, demonstrating the LORD is God.'),

('crs','ALL','According to Isaiah 7:14, which sign did God give to King Ahaz?','A pillar of fire would guide Israel','A virgin would conceive and give birth to a son called Immanuel','The armies of Assyria would be destroyed in one night','A star would appear in the east','B','Isaiah 7:14: "Therefore the Lord himself will give you a sign: The virgin will conceive and give birth to a son, and will call him Immanuel." Christians interpret this as a prophecy of the virgin birth of Jesus (Matthew 1:22–23).'),

('crs','ALL','The "Suffering Servant" passage in Isaiah 53 describes a servant who:','Would lead Israel to military victory over its enemies','Would be pierced for human transgressions, crushed for iniquities, and bear the sins of many','Would establish a political kingdom in Jerusalem','Would call the nations to worship at Mount Zion','B','Isaiah 53:4–12 describes the suffering servant who was "pierced for our transgressions, crushed for our iniquities" and bore the sins of many. Christians interpret this as a prophecy fulfilled in Jesus Christ.'),

('crs','ALL','In the Book of Jeremiah, what was the "New Covenant" God promised?','A covenant based on stricter observance of the Mosaic Law','A covenant written on the hearts of people, where God would be their God and they would know Him personally, and sins would be forgiven','A covenant requiring the rebuilding of the Temple','A military covenant to destroy Israel''s enemies','B','Jeremiah 31:31–34 records God''s promise of a new covenant — not like the Sinai covenant (which Israel broke) — to be written on their hearts; God would forgive their wickedness and remember their sins no more. The New Testament sees this fulfilled in Christ.'),

('crs','ALL','Ezekiel''s vision of the valley of dry bones (Ezekiel 37) symbolised:','The resurrection of individual believers at the end of time','The restoration of the nation of Israel from exile — spiritual and national renewal','The coming judgment on the nations surrounding Israel','The creation of a new earth after the old passes away','B','Ezekiel 37:1–14 records the vision of the valley of dry bones coming to life — God explicitly interprets it (v.11–14) as symbolising the restoration of Israel from Babylonian exile, bringing the nation back to its land.'),

('crs','ALL','The Book of Daniel is set primarily during:','The Assyrian captivity of the northern kingdom','The Babylonian and subsequent Persian captivity of Judah','The Egyptian bondage of Israel','The Hellenistic period under Alexander the Great','B','The Book of Daniel is set during the reign of Nebuchadnezzar of Babylon (from 605 BC) and continues through the Medo-Persian period, recording Daniel''s experiences from youth in Babylon to old age under Persia.'),

('crs','ALL','According to the New Testament, the annunciation — the announcement of Jesus'' birth — was made to Mary by:','The prophet Simeon','The angel Gabriel','John the Baptist','The Holy Spirit in a dream','B','Luke 1:26–38 records the archangel Gabriel visiting Mary in Nazareth to announce she would conceive and bear the Son of God, to be named Jesus. Mary''s response was: "I am the Lord''s servant."'),

('crs','ALL','The Sermon on the Mount in Matthew 5–7 begins with the Beatitudes. According to Matthew 5:3, who will inherit the kingdom of heaven?','The peacemakers','The merciful','The poor in spirit','The pure in heart','C','Matthew 5:3 (the first Beatitude): "Blessed are the poor in spirit, for theirs is the kingdom of heaven." The poor in spirit are those who recognise their spiritual bankruptcy and dependence on God.'),

('crs','ALL','In John 3:16, what is described as God''s motive for sending His Son into the world?','To judge and condemn the sinful world','Because He so loved the world that He gave His only Son, so that whoever believes in Him will not perish but have eternal life','To establish the Jewish people as rulers of all nations','To fulfil the covenant made with Abraham','B','John 3:16: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life." This verse is considered the most concise summary of the gospel.'),

('crs','ALL','According to Luke 15, the parable of the Prodigal Son teaches primarily about:','The danger of wasteful spending','God''s unconditional, joyful love and forgiveness for repentant sinners who return to Him','The importance of working hard and saving money','The need for older siblings to be more obedient','B','The parable (Luke 15:11–32) illustrates God''s extravagant love: the father (representing God) runs to meet his returning wayward son, restoring him — a picture of divine forgiveness and joyful restoration of the repentant.'),

('crs','ALL','The Transfiguration of Jesus (Matthew 17:1–9) was witnessed by:','All twelve apostles','Peter, James, and John','Mary Magdalene, Mary the mother of Jesus, and John','Peter, Andrew, and Philip','B','Matthew 17:1–2 records that Jesus took Peter, James, and John up a high mountain where He was transfigured before them — His face shone like the sun and His clothes became dazzling white. Moses and Elijah appeared with Him.'),

('crs','ALL','The Last Supper, as recorded in Luke 22, was celebrated by Jesus and His disciples during:','The Feast of Tabernacles','The Feast of Dedication (Hanukkah)','The Passover meal','The Feast of Pentecost','C','Luke 22:7–20 records the Last Supper as a Passover meal — Jesus instituted the Lord''s Supper (Eucharist) with bread and wine at this Passover celebration the night before His crucifixion.'),

('crs','ALL','According to John 19:17–18, where was Jesus crucified?','Mount of Olives','Gethsemane','Golgotha (The Place of the Skull)','Mount Moriah','C','John 19:17: "Carrying his own cross, he went out to the place of the Skull (which in Aramaic is called Golgotha). There they crucified him." The name "Calvary" is the Latin equivalent of Golgotha.'),

('crs','ALL','Which woman was the first to witness the risen Jesus according to John 20?','Mary, the mother of Jesus','Joanna','Mary Magdalene','Salome','C','John 20:14–18 records that Mary Magdalene, who remained at the empty tomb weeping, was the first to encounter the risen Jesus. He called her by name and she recognised Him, becoming the first witness of the resurrection.'),

('crs','ALL','The Day of Pentecost (Acts 2) was significant in early Christian history because:','Jesus ascended to heaven in the presence of 500 disciples','The Holy Spirit was poured out on the disciples, empowering them to witness and resulting in 3,000 conversions','Paul converted on the road to Damascus','Peter was imprisoned and miraculously freed by an angel','B','Acts 2:1–41 records the outpouring of the Holy Spirit at Pentecost — disciples spoke in tongues, Peter preached, and about 3,000 people were baptised, marking the birth of the Christian church.'),

('crs','ALL','According to Acts 9, Paul''s (Saul''s) conversion experience occurred:','While he was praying in the Temple in Jerusalem','On the road to Damascus, when a light from heaven flashed around him and he heard the voice of Jesus','During a vision he had while fasting for three days','When Ananias laid hands on him and prayed for him','B','Acts 9:3–6 records Saul''s conversion: a light from heaven flashed and he fell to the ground, hearing Jesus say, "Saul, Saul, why do you persecute me?" He was blinded for three days until Ananias came to him.'),

('crs','ALL','In Paul''s letter to the Romans, the doctrine of "justification by faith" means:','A person is made righteous before God through good deeds and moral living','A person is declared righteous before God not by works of the Law but by faith in Jesus Christ','The Law of Moses is still binding on all Christians','Only those who observe all Jewish laws can be saved','B','Romans 3:21–22, 28 records Paul''s central argument: righteousness before God comes through faith in Jesus Christ to all who believe, not by observing the law — the foundational doctrine of Protestant Christianity.'),

('crs','ALL','The "fruit of the Spirit" listed in Galatians 5:22–23 does NOT include:','Love, joy, peace','Faithfulness, gentleness, self-control','Boldness, courage, and zeal','Patience, kindness, goodness','C','Galatians 5:22–23 lists nine fruits of the Spirit: love, joy, peace, forbearance (patience), kindness, goodness, faithfulness, gentleness, and self-control. Boldness, courage, and zeal are not in this list.'),

('crs','ALL','According to 1 Corinthians 13, which is the greatest of faith, hope, and love?','Faith','Hope','Love','All are equally great','C','1 Corinthians 13:13: "And now these three remain: faith, hope and love. But the greatest of these is love." Paul argues love is the greatest because it never fails and is the foundation of all Christian virtues.'),

('crs','ALL','The "armour of God" described in Ephesians 6:14–17 does NOT include:','The belt of truth','The sword of the Spirit (the word of God)','The shield of perseverance','The helmet of salvation','C','Ephesians 6:14–17 lists: belt of truth, breastplate of righteousness, feet fitted with readiness (gospel of peace), shield of faith, helmet of salvation, and sword of the Spirit (word of God). "Shield of perseverance" is not listed.'),

('crs','ALL','In Philippians 4:11, Paul states he has learned:','To be content in all circumstances regardless of his situation','That riches are necessary for ministry effectiveness','To complain to God about his sufferings','To avoid all material possessions','A','Philippians 4:11: "I have learned to be content whatever the circumstances." Paul says he has learned the secret of contentment — in plenty or in want — through Christ who strengthens him (v.13).'),

('crs','ALL','The Book of Revelation was addressed to how many churches in Asia Minor?','Three','Five','Seven','Twelve','C','Revelation 1:4 and chapters 2–3 address letters to seven churches in Asia Minor: Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia, and Laodicea.'),

('crs','ALL','According to Matthew 28:19–20 (the Great Commission), Jesus commanded His disciples to:','Remain in Jerusalem and wait for His return','Go and make disciples of all nations, baptising them and teaching them to obey all He commanded','Build churches in every major city','Only preach to the lost sheep of Israel','B','The Great Commission (Matthew 28:19–20): "Go and make disciples of all nations, baptising them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you."'),

('crs','ALL','Which Old Testament book contains the famous phrase "I am that I am" (YHWH) as God''s self-revelation?','Genesis','Leviticus','Exodus','Deuteronomy','C','Exodus 3:14 records God''s reply to Moses: "I AM WHO I AM" (Ehyeh asher Ehyeh; Hebrew YHWH) — God''s self-revelation of His eternal, self-existent nature as He commissioned Moses to deliver Israel.'),

('crs','ALL','The Book of Psalms is attributed primarily to:','Moses','Solomon','David (with other contributors)','Asaph alone','C','While 73 psalms bear David''s name in their superscriptions, the Psalter is a collection with multiple authors including Moses (Psalm 90), Solomon (Psalms 72, 127), Asaph, the sons of Korah, and others.'),

('crs','ALL','In the parable of the Sower (Matthew 13), the seed that fell on good soil represents:','People who hear the word and immediately respond with emotion but fall away when trouble comes','People who hear the word but it is choked by the worries of life and deceitfulness of wealth','People who hear the word, understand it, and produce a crop — yielding a hundredfold','Those who never hear the gospel at all','C','Matthew 13:23: "But the seed falling on good soil refers to someone who hears the word and understands it. This is the one who produces a crop, yielding a hundred, sixty or thirty times what was sown."'),

('crs','ALL','The Book of Job primarily addresses the theological question of:','Why God chose Israel as His people','Why righteous people suffer (theodicy) — the problem of innocent suffering','The nature of life after death','The proper way to worship God','B','The Book of Job wrestles with the problem of theodicy (innocent suffering): Job, a righteous man, suffers devastating losses, raising questions about God''s justice and the nature of suffering — Job is vindicated; his friends'' simplistic theology is rejected.'),

('crs','ALL','Which of the following is NOT among the twelve minor prophets?','Amos','Habakkuk','Ezekiel','Zechariah','C','The twelve minor prophets (the Twelve) are: Hosea, Joel, Amos, Obadiah, Jonah, Micah, Nahum, Habakkuk, Zephaniah, Haggai, Zechariah, and Malachi. Ezekiel is a major prophet, not one of the Twelve.'),

('crs','ALL','The "I AM" sayings of Jesus in the Gospel of John (e.g., "I am the bread of life," "I am the light of the world") are theologically significant because:','They are metaphors with no claim to divinity','They deliberately echo God''s self-revelation as "I AM" in Exodus 3:14, asserting Jesus'' divine identity','They were adopted from Greek philosophy','They were later additions to John''s original text','B','Jesus'' "I AM" (Greek: ego eimi) statements in John deliberately recall God''s self-revelation as YHWH (Exodus 3:14), making a profound claim to divine identity — reinforced in John 8:58: "Before Abraham was born, I am!"'),

('crs','ALL','According to Matthew 5:17, Jesus'' relationship to the Law and the Prophets was:','He came to abolish the Law and replace it with new commandments','He came not to abolish but to fulfil the Law and the Prophets','He rejected the Old Testament as no longer relevant','He came to enforce a stricter interpretation of every Mosaic law','B','Matthew 5:17: "Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfil them." Jesus presented Himself as the fulfilment of the Old Testament revelation.'),

('crs','ALL','The concept of "sanctification" in Christian theology refers to:','The initial declaration that a believer is righteous before God (justification)','The ongoing process of being made holy and conformed to the character of Christ throughout the Christian life','The final glorification of believers at the resurrection','The public dedication of a church building','B','Sanctification is the progressive, lifelong work of the Holy Spirit making believers increasingly holy and Christlike in character and conduct — distinct from justification (the initial declaration of righteousness).'),

('crs','ALL','In Acts 15, the Jerusalem Council was convened primarily to resolve the question of:','The leadership succession after the death of James','Whether Gentile (non-Jewish) believers needed to be circumcised and keep the Mosaic Law for salvation','The appointment of deacons in the Jerusalem church','The proper form of baptism for new converts','B','Acts 15:1–29 records the Jerusalem Council convened to settle the dispute over whether Gentile converts must be circumcised and keep the Mosaic Law. The council decided they did not, establishing salvation by grace through faith.'),

('crs','ALL','The prophet Hosea''s marriage to an unfaithful wife (Gomer) was used by God as a symbol of:','The sin of idolatry as worse than adultery','God''s faithful, steadfast love for Israel despite Israel''s unfaithfulness and idolatry (spiritual adultery)','The need for strict divorce laws in Israel','The punishment awaiting the northern kingdom of Israel','B','Hosea''s marriage to the unfaithful Gomer (Hosea 1–3) served as a living parable of God''s covenant relationship with Israel: as Hosea loved and restored an unfaithful wife, so God''s steadfast love (hesed) persists despite Israel''s spiritual unfaithfulness.'),

('crs','ALL','According to John 14:6, Jesus'' claim about Himself was:','He is one of many ways to God','He is the way, the truth, and the life — no one comes to the Father except through Him','Eternal life is available to all who sincerely seek any god','He is the best but not the only path to salvation','B','John 14:6: "Jesus answered, ''I am the way and the truth and the life. No one comes to the Father except through me.''" This is one of the most exclusive and definitive claims Jesus made about His uniqueness.'),

('crs','ALL','The "golden rule" as stated by Jesus in Matthew 7:12 is:','Love God with all your heart, soul, and mind','Do to others what you would have them do to you','Love your neighbour and hate your enemy','Blessed are the poor in spirit','B','Matthew 7:12: "So in everything, do to others what you would have them do to you, for this sums up the Law and the Prophets." This positive formulation of the golden rule summarises ethical conduct.'),

('crs','ALL','In Romans 8:28, Paul asserts that:','Christians will never face suffering or hardship','In all things God works for the good of those who love Him and are called according to His purpose','God is the author of evil as well as good','Faith alone guarantees a comfortable life','B','Romans 8:28: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose." Paul affirms God''s sovereignty over all circumstances for believers'' ultimate good.'),

('crs','ALL','The concept of "atonement" in Christian theology refers to:','The eternal pre-existence of Christ before creation','The reconciliation of humanity to God through the sacrificial death of Jesus Christ, making amends for human sin','The teaching that all humans are saved automatically regardless of faith','The doctrine that humans can earn their way to God through moral effort','B','Atonement (at-one-ment) is the theological doctrine that Christ''s death on the cross satisfied divine justice, reconciled sinful humanity to God, and secured forgiveness — the central event of Christian salvation.'),

('crs','ALL','Which Old Testament figure is described as a "man after God''s own heart"?','Solomon','Moses','Abraham','David','D','1 Samuel 13:14 and Acts 13:22 describe David as "a man after God''s own heart" — despite his sins, his repentant heart and devotion to God distinguished him.'),

('crs','ALL','The Book of Proverbs 9:10 states that "the fear of the LORD is":','The beginning of foolishness','The path to worldly success and riches','The beginning of wisdom','The end of all human striving','C','Proverbs 9:10: "The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding." The reverential awe of God is presented as the foundation of all true wisdom in the Hebrew wisdom tradition.'),

('crs','ALL','According to Luke 1:46–55, the "Magnificat" was the prayer of praise sung by:','Elizabeth upon hearing Mary''s greeting','Mary, upon visiting her cousin Elizabeth','Anna the prophetess in the Temple','The angel Gabriel after the annunciation','B','Luke 1:46: "And Mary said: ''My soul glorifies the Lord and my spirit rejoices in God my Saviour''" — the Magnificat (from the Latin "magnifies") is Mary''s hymn of praise after Elizabeth''s Spirit-filled greeting.'),

('crs','ALL','The concept of the "Trinity" in Christian theology holds that:','There are three separate and distinct gods in Christianity','God is one Being existing eternally in three co-equal, co-eternal Persons: Father, Son, and Holy Spirit','The Father is supreme, the Son is subordinate, and the Spirit is the least','The Trinity was a doctrine invented at the Council of Nicaea with no biblical basis','B','The doctrine of the Trinity (classical Christianity) holds that the one God subsists in three distinct Persons — Father, Son, and Holy Spirit — coequal and coeternal, each fully God yet distinct in Person. Biblical foundations include Matthew 28:19 and 2 Corinthians 13:14.'),

('crs','ALL','In 2 Kings 2, how was the prophet Elijah taken to heaven?','He died peacefully and was carried by angels','He was taken up to heaven in a whirlwind, as a chariot of fire and horses appeared','He was translated bodily like Enoch','He was buried by God, as was Moses','B','2 Kings 2:11: "As they were walking along and talking together, suddenly a chariot of fire and horses of fire appeared and separated the two of them, and Elijah went up to heaven in a whirlwind." Elisha was present and received Elijah''s double portion of his spirit.'),

('crs','ALL','The story of Naaman the Syrian (2 Kings 5) illustrates:','The superiority of the God of Israel over the gods of Syria','God''s healing grace extending beyond Israel to Gentiles — Naaman was healed of leprosy through faith and obedience','The failure of the prophets to help foreign nations','The importance of expensive offerings to secure God''s favour','B','2 Kings 5 records the Syrian commander Naaman coming to the prophet Elisha and being healed of leprosy after dipping seven times in the Jordan — an extension of God''s healing to a Gentile who humbled himself in faith and obedience.'),

('crs','ALL','The concept of "grace" in the New Testament (Greek: charis) primarily means:','The moral effort of a person to please God','God''s unmerited, undeserved favour and goodwill toward humanity, expressed ultimately in the gift of salvation through Christ','A formal blessing pronounced by a priest','Obedience to the commands of Jesus','B','Grace (charis) is the unearned, freely given favour of God toward sinners — Ephesians 2:8–9: "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast."'),

('crs','ALL','According to Mark 2:27, Jesus stated that the Sabbath was:','The most important of all the commandments','The unique sign of the Mosaic covenant not to be altered','Made for man, not man for the Sabbath','To be observed strictly without any exception','C','Mark 2:27: "The Sabbath was made for man, not man for the Sabbath." Jesus affirmed the Sabbath''s purpose — it was God''s gift for human rest and renewal — while challenging the legalistic interpretation of the Pharisees.'),

('crs','ALL','The "Abrahamic covenant" is distinct from the "Mosaic covenant" in that:','The Abrahamic covenant required circumcision as its sign but the Mosaic covenant required Sabbath observance','The Abrahamic covenant was unconditional (based on God''s promise alone) while the Mosaic covenant was conditional on Israel''s obedience to the Law','The Abrahamic covenant applied only to Abraham''s biological descendants while the Mosaic covenant applied to all humanity','Both covenants were identical in their terms and conditions','B','The Abrahamic covenant (Genesis 15, 17) is widely regarded as unconditional — God''s sovereign promise to Abraham and his seed. The Mosaic covenant (Exodus 19–24) included blessings for obedience and curses for disobedience, making it conditional.'),

('crs','ALL','In the parable of the Good Samaritan (Luke 10:25–37), the Samaritan was used as the hero to teach:','That Samaritans are morally superior to Jews','That love for neighbour transcends ethnic and religious boundaries — true neighbour-love is shown in action, not restricted by ethnicity','That the Levitical priests were wicked','That religious leaders are always hypocrites','B','The parable (Luke 10:30–37) uses a despised Samaritan (enemy of Jews) as the example of true neighbourly love — challenging a lawyer who wanted to limit the definition of "neighbour" — showing that love crosses all boundaries.'),

('crs','ALL','According to Acts 2:38, Peter''s response to the crowd''s question "What shall we do?" included:','Baptism alone is sufficient for salvation','Repentance and baptism in the name of Jesus Christ for the forgiveness of sins, after which they would receive the gift of the Holy Spirit','Prayer and fasting for forty days','Attending Temple worship every day','B','Acts 2:38: "Peter replied, ''Repent and be baptised, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.''"'),

('crs','ALL','The concept of "eschatology" in Christian theology refers to:','The study of the origins of the universe','The branch of theology concerned with the last things — death, judgment, heaven, hell, and the return of Christ','The proper interpretation of Scripture','The study of the nature and attributes of God','B','Eschatology (Greek: eschatos = last, logos = study) is the area of Christian theology dealing with the end times: Christ''s second coming, resurrection of the dead, final judgment, heaven, and hell.'),

('crs','ALL','The phrase "sola scriptura" associated with the Protestant Reformation means:','Scripture and tradition are equal authorities','Scripture alone is the supreme and final authority for Christian faith and practice','Salvation is by faith alone','Only Latin translations of the Bible are authoritative','B','Sola scriptura ("Scripture alone") was a foundational principle of the Protestant Reformation (Luther, Calvin), asserting that the Bible alone — not church tradition or papal authority — is the supreme, final authority for Christian doctrine and practice.'),

('crs','ALL','According to Revelation 3:16, God''s warning to the church in Laodicea was:','They would be given the crown of life for their endurance','Because they were neither hot nor cold (lukewarm), He was about to spit them out of His mouth','They were spiritually rich and lacking nothing','Their deeds of service were fully pleasing to God','B','Revelation 3:15–16: "I know your deeds, that you are neither cold nor hot... Because you are lukewarm — neither hot nor cold — I am about to spit you out of my mouth." The wealthy Laodicean church was spiritually complacent.'),

('crs','ALL','The prophet Micah 6:8 summarised God''s requirements for humanity as:','Sacrifices of burnt offerings and first-fruits','To act justly, to love mercy, and to walk humbly with God','Strict observance of all 613 commandments of the Law','To build the Temple and keep the feasts','B','Micah 6:8: "He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God." This verse is considered one of the finest ethical summaries in the Old Testament.'),

('crs','ALL','The theological significance of the resurrection of Jesus in Christian faith, as stated in 1 Corinthians 15:17, is that:','The resurrection proved Jesus was a great teacher but not necessarily divine','If Christ has not been raised, our faith is futile and we are still in our sins','The resurrection is an optional belief for Christians','Only the spiritual resurrection of believers matters, not the bodily resurrection of Christ','B','1 Corinthians 15:17: "And if Christ has not been raised, your faith is futile; you are still in your sins." Paul argues the bodily resurrection of Christ is the indispensable foundation of Christian faith and hope.'),

('crs','ALL','The Nicene Creed (325/381 AD) was primarily formulated to address the heresy of:','Gnosticism, which denied the physical creation','Arianism, which denied the full divinity of the Son (Jesus Christ)','Donatism, which rejected sacraments performed by sinful priests','Pelagianism, which denied original sin','B','The Council of Nicaea (325 AD) and the revised Nicene Creed (381 AD) were convened primarily to refute Arianism — Arius''s teaching that the Son was a created being ("there was a time when he was not"), subordinate to and less than the Father.'),

('crs','ALL','In Christian baptism theology, "infant baptism" (paedobaptism) is practised by churches that hold:','Baptism is purely a symbolic ordinance with no saving significance','Baptism should only be administered to those who personally profess faith','Baptism is a sign of covenant grace that applies to the children of believing parents, analogous to circumcision in the Old Covenant','Baptism must be performed by full immersion','C','Paedobaptist churches (Catholic, Reformed, Lutheran, Anglican) baptise infants of believers on the basis that baptism is the New Covenant sign analogous to circumcision, administered to members of the covenant community including their children.'),

('crs','ALL','The parable of the ten virgins (Matthew 25:1–13) teaches about:','The importance of generosity and sharing resources with others','The need for spiritual preparedness and readiness for the return of Christ, who may come at an unexpected hour','The danger of excessive concern for material goods','The role of women in the early church','B','Matthew 25:1–13 — the parable of the ten virgins (five wise, five foolish) — warns believers to be spiritually prepared and watchful for Christ''s return, as no one knows the hour. The foolish virgins were unprepared and excluded from the feast.'),

('crs','ALL','Which of the following best describes the Old Testament concept of "hesed" (also translated "steadfast love" or "lovingkindness")?','God''s righteous judgment that punishes sin without exception','God''s loyal, covenant love — faithful, enduring, and characterised by mercy beyond what is strictly required','The love between human beings based on mutual benefit','The emotional feeling of love that God sometimes extends to those who deserve it','B','Hesed (Hebrew: חֶסֶד) is one of the most theologically rich words in the OT — God''s steadfast, faithful, covenant love that goes beyond obligation. It is the basis of God''s relationship with Israel and is foundational to OT theology (Exodus 34:6–7).'),

('crs','ALL','The "kenosis" theory in Christology is based on Philippians 2:7 and suggests that in the incarnation, Christ:','Fully possessed and displayed all divine attributes throughout His earthly ministry','Emptied Himself (Greek: kenoo), voluntarily limiting the exercise of certain divine attributes to become truly human','Was not fully divine but only became divine after the resurrection','Took on human appearance only, without becoming genuinely human','B','Kenosis theory (from Greek kenoo, "to empty") is based on Philippians 2:6–7 — Christ "did not consider equality with God something to be used to his own advantage; rather, he made himself nothing" — raising questions about which divine attributes were voluntarily limited in the incarnation.'),

('crs','ALL','The "Day of Atonement" (Yom Kippur) in the Old Testament (Leviticus 16) involved:','A weekly Sabbath rest for all Israelites','The high priest entering the Most Holy Place to make atonement for the sins of the nation, including the release of a scapegoat bearing the people''s sins','Daily sacrifices of grain and drink offerings at the altar','A public reading of the entire Law every seven years','B','Leviticus 16 prescribes Yom Kippur rituals: the high priest, after careful purification, entered the Most Holy Place with incense and blood to atone for his own and the nation''s sins, and a goat was symbolically laden with Israel''s sins and sent into the wilderness (scapegoat).'),

('crs','ALL','According to John 1:1–3, the Word (Logos) is presented as:','A created being brought into existence before the physical world','Having existed eternally with God, being Himself God, and being the agent of all creation','A divine messenger distinct from and subordinate to God','An impersonal force or principle of divine wisdom','B','John 1:1–3: "In the beginning was the Word, and the Word was with God, and the Word was God. He was with God in the beginning. Through him all things were made; without him nothing was made that has been made." This affirms Christ''s eternal pre-existence, divine nature, and creative agency.'),

('crs','ALL','The Protestant doctrine of "sola fide" (faith alone) as articulated by Martin Luther holds that:','Faith must be accompanied by good works to secure salvation','A person is justified (declared righteous) before God by faith alone, apart from works of the Law','Both faith and sacramental participation are equally necessary for salvation','Salvation can be achieved through moral effort and sincere religious devotion','B','Sola fide ("by faith alone") was Luther''s central reformation insight from Romans 1:17 and 3:28 — a person is justified before God solely through trust in Jesus Christ, not by meritorious works, challenging the Catholic doctrine of merit.'),

('crs','ALL','The Book of Ecclesiastes''s recurring phrase "vanity of vanities, all is vanity" (Hebrew: hebel) expresses:','Nihilism — that life has absolutely no meaning','The Teacher''s reflections on the transience and apparent futility of earthly pursuits apart from God, concluding that fearing God and keeping His commandments is the whole duty of humanity','A rejection of the existence of God','An endorsement of material pleasure as life''s highest goal','B','Ecclesiastes (Qohelet) wrestles with the meaninglessness of life "under the sun" (apart from God): wealth, wisdom, and pleasure fail to provide lasting meaning. The conclusion (12:13–14) is to fear God and keep His commandments — the foundation of true human purpose.'),

('crs','ALL','In Christian theology, "propitiation" as used in 1 John 2:2 and Romans 3:25 means:','God''s failure to judge sin in order to show love','Christ''s sacrifice as the atoning sacrifice that satisfies God''s righteous wrath against sin, turning away His judgment from the sinner','A general forgiveness extended to all humanity without conditions','The human act of making amends to God through moral improvement','B','Propitiation (Greek: hilasmos) refers to Christ''s sacrifice satisfying God''s righteous wrath against sin — Romans 3:25: God presented Christ "as a propitiation through faith in his blood." It involves the turning away of divine wrath through the atoning sacrifice.'),

('crs','ALL','The "Beatific Vision" in Christian theology (especially Catholic and Eastern Orthodox traditions) refers to:','The vision of heaven granted to prophets during Old Testament times','The direct, immediate experience of seeing God as He is — the ultimate blessedness of the redeemed in eternal life','A spiritual vision granted to all believers during prayer','The sight of the transfigured Christ as experienced by Peter, James, and John','B','The Beatific Vision is the eschatological direct, unmediated knowledge and vision of God experienced by the redeemed in heaven — 1 John 3:2: "we shall see him as he is"; 1 Corinthians 13:12: "then we shall see face to face."'),

('crs','ALL','The story of Joseph in Genesis 37–50 is theologically significant primarily because:','It explains the origins of the twelve tribes of Israel','It demonstrates God''s providential sovereignty over human betrayal and suffering — Joseph''s statement "You intended to harm me, but God intended it for good" (Genesis 50:20) shows divine purpose within human evil','It records the first case of slavery in the Bible','It establishes Egypt as the primary nation of God''s blessing','B','Genesis 50:20 — Joseph''s statement to his brothers — is the theological climax: God sovereignly worked through betrayal, slavery, and imprisonment to bring Joseph to a position where he could save many lives, illustrating divine providence over human evil.'),

('crs','ALL','Which of the following best describes the "covenant of grace" in Reformed (Calvinist) theology?','An agreement between God and Adam conditioned on perfect obedience, broken by the Fall','God''s unconditional promise, after the Fall, to save sinners through Christ — offered to the elect through faith','A formal treaty between God and Israel at Sinai requiring full obedience to the Law','The covenant between the Father, Son, and Spirit in eternity to accomplish redemption','B','The covenant of grace (Reformed covenant theology) is God''s post-Fall promise to redeem fallen humanity through Christ — administered through successive covenants (Abrahamic, Mosaic, Davidic, New Covenant) until its fulfilment in Christ.'),

('crs','ALL','According to Acts 17:16–34, when Paul preached in Athens at the Areopagus, he used as a starting point:','A quotation from the prophet Isaiah','The inscription on an altar: "TO AN UNKNOWN GOD," arguing that the God they ignorantly worship is the Creator who raised Jesus from the dead','A miracle of healing that drew the crowd''s attention','A direct quotation of the Septuagint (Greek Old Testament)','B','Acts 17:22–23: Paul addressed the Athenians by referencing the altar inscribed "TO AN UNKNOWN GOD," using it as a bridge to proclaim the God of creation, resurrection, and judgment — a classic example of contextualised apologetics.'),

('crs','ALL','The concept of "prevenient grace" in Wesleyan-Arminian theology holds that:','Grace is irresistibly applied to the elect alone','God''s grace precedes and enables every person''s free response to the gospel — it is given to all people, enabling them to respond to God if they choose','Grace is given only after a person first seeks God on their own','Salvation is entirely the result of human free will without divine assistance','B','Prevenient grace (going-before grace) in Arminian theology: the Holy Spirit''s universal, preceding work that overcomes the effects of sin enough to enable a genuine free response to the gospel — distinct from Reformed irresistible grace applied only to the elect.'),

('crs','ALL','The vision of the New Jerusalem in Revelation 21–22 symbolises:','A literal city that will physically descend from space','The ultimate eschatological hope of the people of God — the perfect community of God dwelling with redeemed humanity in a renewed creation, where death, mourning, and sin are no more','The rebuilding of the historical Jerusalem after 70 AD','A heavenly city where only the 144,000 will live','B','Revelation 21:1–4 presents the New Jerusalem as the consummation of God''s redemptive plan: "God''s dwelling place is now among the people... There will be no more death or mourning or crying or pain." It symbolises the perfect union of God and His redeemed people in the renewed creation.'),

('crs','ALL','Which of the following accounts in Acts demonstrates the inclusion of Gentiles in the early church through Peter''s ministry?','The conversion of the Ethiopian eunuch (Acts 8)','The conversion of Cornelius, a Roman centurion, through Peter''s ministry after a vision (Acts 10)','Paul''s preaching at the Areopagus in Athens (Acts 17)','The Pentecost event where Jews from many nations were present (Acts 2)','B','Acts 10 records Peter''s vision of the clean and unclean animals and his subsequent visit to Cornelius''s household — the first clear Gentile conversion under Peter''s ministry — demonstrating that "God does not show favouritism" (Acts 10:34) and the gospel is for all nations.'),

('crs','ALL','The theological concept of "imputation" in Reformed soteriology refers to:','The gradual moral improvement of believers through the Holy Spirit''s work (sanctification)','The legal crediting or reckoning of Christ''s righteousness to the believer''s account before God, and the believer''s sin being charged to Christ''s account on the cross','The impartation of divine nature to believers through the sacraments','The believer''s gradual attainment of perfect righteousness','B','Imputation (Latin: imputatio): in justification, Christ''s perfect righteousness is legally credited to the believer (Romans 4:3–8; 2 Corinthians 5:21), while the believer''s sin was charged to Christ on the cross — the great exchange at the heart of Reformed soteriology.');
