-- 20 Post-UTME Agricultural Science Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('agric','ALL','The process by which leguminous plants improve soil fertility is known as:','Denitrification','Biological nitrogen fixation','Ammonification','Nitrification','B','Legumes (e.g., cowpea, soybean, groundnut) host symbiotic nitrogen-fixing bacteria (Rhizobium) in root nodules that convert atmospheric nitrogen (N₂) into ammonia/ammonium, enriching the soil with available nitrogen.'),

('agric','ALL','Which of the following soil types has the highest water-holding capacity?','Sandy soil','Loamy soil','Clay soil','Silty soil','C','Clay soil has the highest water-holding capacity because its particles are extremely fine and have a large surface area, with very small pores that hold water by capillarity — but it is also prone to waterlogging and compaction.'),

('agric','ALL','The term "photosynthesis" in plant biology refers to:','The process by which plants break down sugars for energy during the night','The process by which green plants use sunlight, water, and CO₂ to manufacture glucose and oxygen','The absorption of water and mineral nutrients by plant roots from the soil','The process of pollination and fertilisation in flowering plants','B','Photosynthesis: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. Chlorophyll in plant cells captures solar energy to convert CO₂ and water into glucose (food) and release oxygen.'),

('agric','ALL','The correct order of soil profile horizons from the surface downward is:','B horizon → A horizon → C horizon → Bedrock','A horizon (topsoil) → B horizon (subsoil) → C horizon (parent material) → Bedrock','C horizon → B horizon → A horizon → Bedrock','O horizon → C horizon → A horizon → Bedrock','B','A standard soil profile: O horizon (organic litter) → A horizon (topsoil, rich in humus) → B horizon (subsoil, leached minerals accumulate) → C horizon (weathered parent material) → R horizon (bedrock).'),

('agric','ALL','Which of the following is the primary cause of soil erosion in the tropics?','Low rainfall and drought','The impact of heavy tropical rainfall on bare, unprotected soil surfaces','Excessive use of chemical fertilisers','Deep ploughing during land preparation','B','In tropical areas, the high intensity of rainfall (large raindrop size and kinetic energy) detaches and splashes soil particles (splash erosion), while surface runoff carries them away — especially on bare, unprotected slopes.'),

('agric','ALL','The process of "crop rotation" involves:','Planting the same crop on the same land every season to maintain soil conditions','Alternating different types of crops on the same piece of land in successive seasons to maintain soil fertility and break pest cycles','Growing two or more crops simultaneously on the same piece of land','Planting crops in strips across a slope to control erosion','B','Crop rotation prevents depletion of specific nutrients (different crops have different nutritional needs), breaks pest and disease cycles, and when legumes are included, replenishes soil nitrogen — a key practice in sustainable farming.'),

('agric','ALL','In animal husbandry, "ruminants" are animals that:','Have a simple single-chambered stomach like pigs and poultry','Have a complex four-chambered stomach (rumen, reticulum, omasum, abomasum) that allows them to digest cellulose-rich plant material through microbial fermentation','Feed only on grains and seeds','Are strictly carnivorous animals','B','Ruminants (cattle, goat, sheep, camel) have a four-chambered stomach enabling them to regurgitate and rechew partially digested food (cud) and use microbial fermentation in the rumen to digest cellulose from grass and hay.'),

('agric','ALL','The term "NPK" on a fertiliser bag refers to the proportions of:','Nitrogen, Phosphorus, and Potassium in the fertiliser','Nitrates, Proteins, and Ketones in the soil','Nitrogen, Potash, and Kelp as fertiliser ingredients','Natural, Processed, and Kilned nutrients','A','NPK stands for Nitrogen (N), Phosphorus (P), and Potassium (K) — the three primary macronutrients required by plants for growth. Their ratios on fertiliser bags (e.g., 15:15:15) indicate the percentage of each nutrient.'),

('agric','ALL','Which of the following is the correct definition of "mixed farming"?','Growing only one crop (monoculture) on a large scale','A system of farming that combines the growing of crops and the rearing of livestock on the same farm','Farming using a mix of traditional and modern methods simultaneously','Growing several different crops on the same land at the same time','B','Mixed farming integrates both crop production and livestock rearing on the same farm — animals provide manure for crops, while crop residues feed livestock, creating complementary and sustainable land use.'),

('agric','ALL','The function of "stomata" in plant physiology is to:','Anchor the plant in the soil and absorb water','Regulate gas exchange (CO₂ and O₂) and water vapour (transpiration) between the plant and atmosphere','Convert sunlight into chemical energy through photosynthesis','Transport water and minerals from roots to leaves','B','Stomata are microscopic pores, mainly on the leaf underside, surrounded by guard cells. They open for gas exchange (CO₂ in for photosynthesis, O₂ out) and close to reduce water loss (transpiration) — regulating plant water balance.'),

('agric','ALL','The term "monoculture" in agriculture refers to:','Growing diverse crops together to maximise yields','The cultivation of a single crop species on a large area over successive seasons','Farming using only organic (no synthetic) inputs','The practice of leaving land fallow for one growing season','B','Monoculture is the cultivation of one crop species over a large area — common in commercial agriculture (e.g., oil palm, sugarcane plantations). It allows mechanisation and economies of scale but increases vulnerability to pests, diseases, and soil degradation.'),

('agric','ALL','The primary purpose of "liming" agricultural soils is to:','Add nitrogen to soil for crop growth','Neutralise soil acidity (raise pH) to improve nutrient availability and microbial activity','Improve the physical texture of sandy soils','Kill soil pests and nematodes','B','Agricultural lime (calcium carbonate or calcium hydroxide) is applied to acid soils to raise pH — increasing the availability of nutrients (especially phosphorus), improving microbial activity, and reducing the toxicity of aluminium and manganese.'),

('agric','ALL','Which of the following is a feature of "sustainable agriculture"?','Maximising current yields regardless of the impact on future productivity','Using farming practices that maintain long-term productivity, protect the environment, and ensure economic viability for farmers — without depleting natural resources','Exclusively using chemical inputs to maximise production','Abandoning traditional farming methods entirely in favour of mechanisation','B','Sustainable agriculture meets present food needs without compromising the ability of future generations to meet theirs — integrating environmental stewardship, economic profitability, and social equity through practices like organic farming, agroforestry, and IPM.'),

('agric','ALL','In poultry production, the term "broiler" refers to:','A hen kept for egg production','A chicken specifically bred and raised for meat production, typically slaughtered at 6–8 weeks','Any female chicken under one year of age','A male chicken (cockerel) used for breeding','B','Broilers are chickens genetically selected for rapid growth and efficient feed conversion, raised specifically for meat production. They reach market weight (1.8–2.5 kg) in approximately 6–8 weeks under intensive production.'),

('agric','ALL','The "Green Revolution" of the 1960s–1970s was characterised by:','A global movement towards organic farming and the rejection of synthetic inputs','The introduction of high-yielding varieties (HYV) of crops (especially wheat and rice), combined with irrigation, chemical fertilisers, and pesticides — dramatically increasing food production in developing countries','The global adoption of genetic engineering and GMO crops','A shift from commercial to subsistence farming in Asia and Africa','B','The Green Revolution (Norman Borlaug, IRRI, CIMMYT) involved developing semi-dwarf, high-yielding wheat and rice varieties responsive to fertiliser — combined with irrigation and inputs, tripling cereal production in Asia and Latin America between 1960–1990.'),

('agric','ALL','Which of the following is NOT a method of controlling weeds in crop production?','Mechanical cultivation (hoeing and ploughing)','Application of herbicides','Application of fungicides','Mulching','C','Weeds are controlled by mechanical methods (hoeing), herbicides (chemical), mulching (physical barrier), crop rotation, and biological methods. Fungicides control fungal diseases — not weeds.'),

('agric','ALL','The term "humus" in soil science refers to:','The total mineral content of the soil','The dark, partially decomposed organic matter in the soil derived from dead plants and animals — improving soil structure, water retention, and fertility','The layer of clay immediately beneath the topsoil','Chemically altered weathered rock forming the parent material of soil','B','Humus is stable, well-decomposed organic matter — the end product of microbial decomposition of plant and animal residues. It improves soil structure (aggregation), water-holding capacity, CEC (cation exchange capacity), and nutrient availability.'),

('agric','ALL','Which of the following best describes "intensive farming"?','Farming large areas of land with minimal inputs and low yields per hectare','Farming that aims to maximise output from a relatively small area through high inputs of labour, capital, fertilisers, and technology per unit area','Farming exclusively without any synthetic inputs','Leaving land uncultivated to restore natural vegetation','B','Intensive farming maximises productivity per unit area through heavy inputs of capital, labour, fertilisers, and technology — characteristic of commercial horticulture, poultry units, and dairy farms. Contrasted with extensive farming (large area, low inputs per hectare).'),

('agric','ALL','The process of "irrigation" in agriculture is best defined as:','The natural supply of water to crops through rainfall','The artificial application of water to crops to supplement natural rainfall and ensure adequate moisture for plant growth','The drainage of waterlogged soils to make them suitable for cultivation','The storage of rainwater in dams for domestic use','B','Irrigation is the controlled application of water to agricultural land through canals, pipes, sprinklers, or drip systems — extending the growing season, enabling farming in arid areas, and supplementing inadequate rainfall.'),

('agric','ALL','In animal nutrition, "roughage" (fibre) is important in the diet of ruminants because:','It provides the highest energy content per unit mass','It provides the essential amino acids needed for muscle growth','It provides the bulk (cellulose) that stimulates rumen fermentation and gut motility, and ruminants can digest cellulose through microbial action','It is the primary source of vitamins and minerals','C','Roughage (grass, hay, silage) forms the basis of ruminant diets. The high cellulose content is fermented by rumen microorganisms to produce volatile fatty acids (the main energy source for ruminants), and fibre promotes normal digestive function.');
