-- 20 Post-UTME Accounting Questions (University-Standard, OAU/UNILAG level)
-- Run this in your Post-UTME Supabase SQL Editor (zrkkurxfadlilwezqnxf)

INSERT INTO question_bank (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES

('accounting','ALL','The accounting equation that forms the basis of double-entry bookkeeping is:','Revenue − Expenses = Profit','Assets = Liabilities + Owner''s Equity','Assets + Expenses = Liabilities + Revenue','Cash = Assets − Liabilities','B','The fundamental accounting equation is Assets = Liabilities + Owner''s Equity (Capital). It reflects that all assets are financed either by creditors (liabilities) or by the owners (equity).'),

('accounting','ALL','Which of the following best describes the "accrual basis" of accounting?','Revenue and expenses are recorded only when cash is received or paid','Revenue is recognised when earned and expenses when incurred, regardless of when cash changes hands','Only cash transactions are recorded in the ledger','Expenses are recorded in advance of being incurred','B','Under the accrual basis (matching principle), revenue is recognised when earned and expenses when incurred — not necessarily when cash is received or paid — giving a more accurate picture of financial performance.'),

('accounting','ALL','The "going concern" concept in accounting assumes that:','A business will close operations at the end of the financial year','A business will continue to operate indefinitely into the foreseeable future','All assets must be valued at their current market price','The owner and the business are the same legal entity','B','The going concern concept holds that a business is assumed to continue operating for the foreseeable future — this justifies carrying assets at historical cost rather than liquidation (break-up) value.'),

('accounting','ALL','Depreciation is charged on fixed assets primarily to:','Reduce the tax payable by the business each year','Spread the cost of a fixed asset over its useful life in accordance with the matching principle','Replace the asset at the end of its useful life','Show the current market value of the asset in the balance sheet','B','Depreciation allocates the cost of a tangible fixed asset systematically over its useful economic life, matching the expense of using the asset against the revenue it helps generate (matching principle).'),

('accounting','ALL','Which of the following is a "current asset"?','Land and buildings','Machinery and equipment','Trade receivables (debtors)','Long-term investments','C','Current assets are assets expected to be converted to cash or used within one year — including cash, inventory, trade receivables, and prepayments. Land, machinery, and long-term investments are non-current (fixed) assets.'),

('accounting','ALL','The "prudence" (conservatism) concept in accounting requires that:','Profits and assets should be overstated to attract investors','Losses and liabilities should be recognised as soon as they are anticipated, while revenues should only be recognised when realised','All transactions should be recorded at historical cost','The same accounting methods should be applied consistently each year','B','Prudence (conservatism): anticipate all possible losses and recognise them immediately, but do not recognise revenue until it is reasonably certain. This prevents overstatement of profits and assets.'),

('accounting','ALL','A trial balance is prepared to:','Verify that total debits equal total credits in the ledger, thus checking arithmetic accuracy','Prepare the final accounts (income statement and balance sheet)','Record all business transactions for the year','Show the profit or loss made by the business','A','A trial balance lists all ledger account balances to verify that total debits equal total credits — checking for arithmetic errors in the double-entry system. It does not itself prove accounts are correct.'),

('accounting','ALL','If a business has assets of ₦500,000 and liabilities of ₦180,000, the owner''s equity is:','₦280,000','₦320,000','₦380,000','₦420,000','B','Owner''s Equity = Assets − Liabilities = ₦500,000 − ₦180,000 = ₦320,000.'),

('accounting','ALL','The "straight-line method" of depreciation is calculated as:','(Cost − Residual Value) / Useful Life in Years','Cost × Depreciation Rate%','Net Book Value × Depreciation Rate%','(Cost + Residual Value) / Useful Life','A','Straight-line depreciation = (Cost − Residual/Scrap Value) ÷ Estimated Useful Life. This produces a constant annual depreciation charge throughout the asset''s life.'),

('accounting','ALL','A "credit note" is issued by a seller to a buyer when:','The buyer pays an invoice early and earns a discount','Goods are returned by the buyer or an overcharge has been made, reducing the amount owed','The buyer requests an extension of the credit period','A new credit account is opened for the buyer','B','A credit note is issued by the seller to the buyer to cancel or reduce a previously issued invoice — e.g., when goods are returned, found defective, or an overcharge occurred. It reduces the buyer''s debt.'),

('accounting','ALL','Which financial statement shows the financial position (assets, liabilities, and equity) of a business at a specific point in time?','Income statement (profit and loss account)','Cash flow statement','Balance sheet (statement of financial position)','Statement of changes in equity','C','The balance sheet (statement of financial position) is a snapshot of a business''s financial position at a specific date, showing what it owns (assets), what it owes (liabilities), and the residual interest of owners (equity).'),

('accounting','ALL','The "double-entry" principle states that every business transaction:','Must be recorded only in the cash book','Affects only one account in the ledger','Must be recorded as both a debit entry in one account and a corresponding credit entry in another account','Is first recorded in the journal, then in the cash book only','C','Double-entry bookkeeping (Luca Pacioli, 1494) requires every transaction to be recorded twice — as a debit in one account and an equal credit in another — so that the accounting equation always remains in balance.'),

('accounting','ALL','"Goodwill" in accounting is best described as:','The physical assets of a business beyond their book value','An intangible asset representing the excess of the purchase price of a business over the fair value of its net identifiable assets — arising from reputation, customer relationships, and brand','Cash reserves held by a business for unforeseen expenses','The market value of a company''s shares on the stock exchange','B','Goodwill is an intangible asset recorded when a business is acquired for more than the fair value of its net identifiable assets — representing factors like brand reputation, customer loyalty, and established relationships.'),

('accounting','ALL','The "consistency" concept in accounting requires that:','A business must change its accounting policies each year to reflect current standards','Once an accounting method is adopted, it should be applied consistently from one period to the next to allow meaningful comparison','All businesses in an industry must use identical accounting methods','Financial statements must be consistent with management''s expectations','B','The consistency concept requires the same accounting methods (e.g., depreciation method, inventory valuation) to be used period after period, enabling meaningful comparison of financial statements over time.'),

('accounting','ALL','In a sole trader''s accounts, "drawings" refers to:','Salaries paid to employees during the year','Amounts withdrawn from the business by the owner for personal use, reducing capital','Loans taken by the business from a bank','Purchases of fixed assets for the business','B','Drawings are amounts taken out of the business by the owner (cash or goods) for personal use. They are not an expense but reduce the owner''s capital/equity in the business.'),

('accounting','ALL','Which of the following would be recorded in the "sales day book" (sales journal)?','Cash sales made over the counter','Credit sales made to customers on account','Goods returned by customers','Payments received from debtors','B','The sales day book (sales journal) records credit sales only — transactions where goods are sold on credit to customers. Cash sales are recorded in the cash book; returns go in the returns inward (sales returns) journal.'),

('accounting','ALL','Closing stock (ending inventory) appearing in the trial balance is shown in the:','Trading account as a credit and in the balance sheet as a current asset','Profit and loss account as a debit','Balance sheet only as a non-current asset','Cash flow statement as an operating activity','A','Closing stock reduces cost of goods sold (cost of sales) in the trading account (credit side) and appears as a current asset in the balance sheet — it appears in both financial statements.'),

('accounting','ALL','The "realisation" concept in accounting holds that:','Revenue should be recognised when cash is actually received','Revenue should be recognised when it is earned — typically when goods are delivered or services performed, regardless of when payment is received','All assets must be revalued to current market prices at year end','Expenses should be recorded only when paid','B','The realisation concept states that revenue is recognised when it is earned (the risk and rewards of ownership have transferred) — not when cash is received, forming the basis of accrual accounting.'),

('accounting','ALL','A business purchases goods on credit for ₦40,000. The correct double-entry is:','Debit Cash, Credit Purchases','Debit Purchases, Credit Creditors (Accounts Payable)','Debit Creditors, Credit Purchases','Debit Sales, Credit Cash','B','Purchasing goods on credit: Debit Purchases (expense increases) ₦40,000; Credit Creditors/Accounts Payable (liability increases) ₦40,000 — the business has goods but owes the supplier.'),

('accounting','ALL','The purpose of a "bank reconciliation statement" is to:','Record all transactions that have passed through the bank account','Reconcile (explain) the difference between the cash book balance and the bank statement balance at a given date','Prepare the final income statement from the cash book','Detect fraud by comparing the cash book with the petty cash box','B','A bank reconciliation statement identifies and explains discrepancies between the company''s cash book balance and the bank statement balance — caused by unpresented cheques, outstanding deposits, bank charges, and errors.');
