-- ============================================================
--  QUESTION BANK SEED  –  5 hard questions per subject
--  Subjects: english, mathematics, physics, chemistry, biology,
--             economics, government, literature, commerce,
--             accounting, geography, history, agric,
--             further_maths, irs, crs, aptitude
--  university = 'ALL'  →  available to all universities
-- ============================================================

INSERT INTO public.question_bank
    (subject, university, question, option_a, option_b, option_c, option_d, correct_answer, explanation)
VALUES

-- ═══════════════════════════ USE OF ENGLISH ═══════════════════════════

('english', 'ALL',
 'Which sentence correctly employs the subjunctive mood in a contrary-to-fact condition?',
 'If he was here, he would help us.',
 'If he were here, he would help us.',
 'If he is here, he will help us.',
 'If he had been here, he helped us.',
 'B',
 'The subjunctive mood requires "were" (not "was") in contrary-to-fact conditional clauses introduced by "if". Option B is the only grammatically correct use of the past subjunctive.'),

('english', 'ALL',
 'The rhetorical device in the expression "The pen is mightier than the sword" is:',
 'Oxymoron',
 'Synecdoche',
 'Metonymy',
 'Zeugma',
 'C',
 '"Pen" stands for intellectual/writing power and "sword" stands for military force. This is metonymy — an associated concept substitutes for the thing itself. Synecdoche uses a PART for the whole; metonymy uses an ASSOCIATED idea.'),

('english', 'ALL',
 'Which sentence contains a dangling modifier?',
 'Running quickly, she caught the bus.',
 'Having finished the assignment, the television was turned on.',
 'After eating lunch, John took a nap.',
 'While driving to work, he listened to music.',
 'B',
 '"Having finished the assignment" must logically modify the subject of the main clause, but the subject is "the television" — which cannot finish assignments. This makes it a dangling modifier. In A, C, and D, the modifying phrases correctly refer to the sentence subjects.'),

('english', 'ALL',
 'Which of the following is the best example of "chiasmus" as a rhetorical device?',
 'To be or not to be, that is the question.',
 'Ask not what your country can do for you; ask what you can do for your country.',
 'I came, I saw, I conquered.',
 'It was the best of times, it was the worst of times.',
 'B',
 'Chiasmus is a rhetorical reversal of grammatical structures: "what your country can do FOR YOU" is inverted to "what YOU can do for your country." The syntactic elements are mirrored in reverse order — the classic A-B / B-A pattern.'),

('english', 'ALL',
 'The word "pleonasm" in English grammar refers to:',
 'A figure of speech based on deliberate exaggeration.',
 'The use of more words than necessary to convey a meaning, e.g. "free gift".',
 'A statement that contradicts itself within a single expression.',
 'The repetition of initial consonant sounds in adjacent words.',
 'B',
 '"Pleonasm" is the use of redundant or superfluous words. "Free gift," "close proximity," and "future plans" are all pleonasms. Option A is hyperbole, C is oxymoron/paradox, and D is alliteration.'),

-- ═══════════════════════════ MATHEMATICS ═══════════════════════════

('mathematics', 'ALL',
 'If z = 3 + 4i is a complex number, what is |z²|?',
 '7',
 '25',
 '50',
 '5',
 'B',
 '|z| = √(3²+4²) = √25 = 5. Since |z²| = |z|² = 25. Verification: z² = (3+4i)² = 9+24i−16 = −7+24i, and |−7+24i| = √(49+576) = √625 = 25.'),

('mathematics', 'ALL',
 'What is the sum of the infinite geometric series 1 − 1/3 + 1/9 − 1/27 + …?',
 '2/3',
 '3/4',
 '1/2',
 '4/3',
 'B',
 'First term a = 1, common ratio r = −1/3. Since |r| < 1, sum S = a/(1−r) = 1/(1−(−1/3)) = 1/(4/3) = 3/4.'),

('mathematics', 'ALL',
 'Evaluate the definite integral ∫₀¹ x·eˣ dx.',
 '1',
 'e − 1',
 'e',
 '2 − e',
 'A',
 'Integration by parts: let u = x, dv = eˣ dx → ∫x·eˣ dx = eˣ(x−1) + C. Evaluating from 0 to 1: [e¹(1−1)] − [e⁰(0−1)] = 0 − (−1) = 1.'),

('mathematics', 'ALL',
 'The number of distinct arrangements of all the letters in the word MATHEMATICS is:',
 '4,989,600',
 '39,916,800',
 '9,979,200',
 '3,326,400',
 'A',
 'MATHEMATICS has 11 letters: M(×2), A(×2), T(×2), H, E, I, C, S. Distinct arrangements = 11! ÷ (2!×2!×2!) = 39,916,800 ÷ 8 = 4,989,600.'),

('mathematics', 'ALL',
 'If α and β are roots of 2x² − 5x + 3 = 0, find α³ + β³.',
 '35/8',
 '125/8',
 '7/4',
 '5/2',
 'A',
 'By Vieta''s formulas: α+β = 5/2, αβ = 3/2. Then α²+β² = (5/2)²−2(3/2) = 25/4−3 = 13/4. Finally α³+β³ = (α+β)(α²−αβ+β²) = (5/2)(13/4−3/2) = (5/2)(7/4) = 35/8.'),

-- ═══════════════════════════ PHYSICS ═══════════════════════════

('physics', 'ALL',
 'A photon has wavelength 400 nm. What is its energy? (h = 6.63×10⁻³⁴ J·s, c = 3×10⁸ m/s, 1 eV = 1.6×10⁻¹⁹ J)',
 '3.1 eV',
 '2.5 eV',
 '1.8 eV',
 '4.1 eV',
 'A',
 'E = hc/λ = (6.63×10⁻³⁴ × 3×10⁸) / (400×10⁻⁹) = 4.97×10⁻¹⁹ J. Converting: 4.97×10⁻¹⁹ ÷ 1.6×10⁻¹⁹ ≈ 3.1 eV.'),

('physics', 'ALL',
 'A Carnot heat engine operates between a hot reservoir at 600 K and a cold reservoir at 300 K. Its maximum efficiency is:',
 '25%',
 '50%',
 '33%',
 '75%',
 'B',
 'Carnot efficiency η = 1 − T_cold/T_hot = 1 − 300/600 = 0.5 = 50%. This is the theoretical maximum for any engine operating between those two temperatures.'),

('physics', 'ALL',
 'In Young''s double-slit experiment, slit separation = 0.5 mm, screen distance = 2 m, wavelength = 600 nm. The fringe width β is:',
 '1.2 mm',
 '2.4 mm',
 '0.6 mm',
 '4.8 mm',
 'B',
 'β = λD/d = (600×10⁻⁹ × 2) / (0.5×10⁻³) = 1.2×10⁻⁶ / 5×10⁻⁴ = 2.4×10⁻³ m = 2.4 mm.'),

('physics', 'ALL',
 'The de Broglie wavelength of an electron moving at 2×10⁶ m/s is: (h = 6.63×10⁻³⁴ J·s, mₑ = 9.11×10⁻³¹ kg)',
 '0.364 nm',
 '0.155 nm',
 '1.22 nm',
 '0.728 nm',
 'A',
 'λ = h/mv = 6.63×10⁻³⁴ / (9.11×10⁻³¹ × 2×10⁶) = 6.63×10⁻³⁴ / 1.822×10⁻²⁴ ≈ 3.64×10⁻¹⁰ m = 0.364 nm.'),

('physics', 'ALL',
 'An RLC series circuit has R = 10 Ω, L = 0.1 H, C = 100 μF. At resonance, the impedance of the circuit is:',
 '0 Ω',
 '10 Ω',
 '100 Ω',
 'Approximately 141 Ω',
 'B',
 'At resonance, inductive reactance XL equals capacitive reactance XC, so they cancel. Impedance Z = √(R²+(XL−XC)²) = √(R²+0) = R = 10 Ω. The circuit behaves as a purely resistive circuit.'),

-- ═══════════════════════════ CHEMISTRY ═══════════════════════════

('chemistry', 'ALL',
 'In 2H₂O₂ → 2H₂O + O₂, if the rate of decomposition of H₂O₂ is 0.02 mol/L/s, the rate of O₂ formation is:',
 '0.04 mol/L/s',
 '0.02 mol/L/s',
 '0.01 mol/L/s',
 '0.005 mol/L/s',
 'C',
 'From stoichiometry, 2 mol H₂O₂ produces 1 mol O₂. Rate of O₂ = ½ × rate of H₂O₂ decomposition = ½ × 0.02 = 0.01 mol/L/s.'),

('chemistry', 'ALL',
 'Which of the following ionic compounds has the highest lattice energy?',
 'NaF',
 'KCl',
 'MgO',
 'RbBr',
 'C',
 'Lattice energy is proportional to ionic charges and inversely proportional to ionic radii. MgO has doubly-charged ions (Mg²⁺, O²⁻) and small ionic radii, giving it by far the highest lattice energy of the listed options.'),

('chemistry', 'ALL',
 'When excess concentrated NaOH is added to aluminium hydroxide Al(OH)₃, the product formed is:',
 'Al₂O₃ and water',
 'Tetrahydroxoaluminate ion [Al(OH)₄]⁻',
 'AlO⁻ and water',
 'Boehmite (AlOOH)',
 'B',
 'Al(OH)₃ is amphoteric — it acts as an acid with strong bases. Al(OH)₃ + NaOH → Na[Al(OH)₄], containing the aluminate ion [Al(OH)₄]⁻. This dissolves the white precipitate.'),

('chemistry', 'ALL',
 'For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), ΔH = −92 kJ/mol. Which conditions maximise the yield of NH₃?',
 'High temperature, low pressure',
 'Low temperature, high pressure',
 'High temperature, high pressure',
 'Catalyst only, at high temperature',
 'B',
 'Le Chatelier''s principle: the forward reaction is exothermic, so low temperature favours NH₃. Since 4 mol gas → 2 mol gas, high pressure shifts equilibrium rightward. Therefore low temperature + high pressure maximises yield.'),

('chemistry', 'ALL',
 'The hybridisation of carbon atoms in benzene (C₆H₆) is:',
 'sp³',
 'sp²',
 'sp',
 'sp³d',
 'B',
 'Each carbon in benzene forms 3 sigma bonds (2 C–C and 1 C–H) using sp² hybrid orbitals arranged at 120° in a plane. The remaining unhybridised p-orbital on each carbon contributes to the delocalised π system above and below the ring.'),

-- ═══════════════════════════ BIOLOGY ═══════════════════════════

('biology', 'ALL',
 'During meiosis, crossing over (genetic recombination between homologous chromosomes) occurs during:',
 'Metaphase I',
 'Prophase I',
 'Anaphase II',
 'Telophase I',
 'B',
 'During Prophase I, homologous chromosomes pair up (synapsis) to form bivalents. Non-sister chromatids exchange segments at points called chiasmata — this is crossing over. It occurs specifically at the pachytene sub-stage of Prophase I.'),

('biology', 'ALL',
 'Which enzyme removes RNA primers and replaces them with DNA during prokaryotic DNA replication?',
 'DNA Polymerase I',
 'DNA Polymerase III',
 'Primase',
 'Helicase',
 'A',
 'DNA Polymerase III is the main replicative enzyme. DNA Polymerase I (Pol I) has 5''→3'' exonuclease activity that removes RNA primers laid down by Primase, simultaneously filling the gap with DNA. Helicase unwinds the double helix.'),

('biology', 'ALL',
 'Which description of the sodium-potassium (Na⁺/K⁺) ATPase pump is correct?',
 'Passive transport; moves 3Na⁺ in and 2K⁺ out per cycle.',
 'Active transport; moves 3Na⁺ out and 2K⁺ in per cycle.',
 'Active transport; moves 2Na⁺ out and 3K⁺ in per cycle.',
 'Facilitated diffusion; moves Na⁺ and K⁺ down their gradients.',
 'B',
 'The Na⁺/K⁺-ATPase uses ATP hydrolysis (active transport) to pump 3 Na⁺ OUT and 2 K⁺ IN per cycle. This maintains the electrochemical gradients essential for nerve impulse transmission and cell volume regulation.'),

('biology', 'ALL',
 'In a dihybrid cross AaBb × AaBb, what proportion of offspring will be homozygous recessive for both traits (aabb)?',
 '1/16',
 '1/4',
 '9/16',
 '3/16',
 'A',
 'Probability of aa = 1/4; probability of bb = 1/4. Since the traits assort independently (Mendel''s Law of Independent Assortment), P(aabb) = 1/4 × 1/4 = 1/16. Only 1 out of 16 offspring in the classic 9:3:3:1 ratio is aabb.'),

('biology', 'ALL',
 'The Calvin cycle (carbon fixation / dark reactions) of photosynthesis occurs in the:',
 'Thylakoid membrane',
 'Stroma of the chloroplast',
 'Grana (stacked thylakoids)',
 'Outer chloroplast membrane',
 'B',
 'Light-dependent reactions occur in the thylakoid membranes (grana), generating ATP and NADPH. The Calvin cycle uses these products to fix CO₂ into glucose via RuBisCO, and takes place in the stroma of the chloroplast.'),

-- ═══════════════════════════ ECONOMICS ═══════════════════════════

('economics', 'ALL',
 'In the IS-LM model, simultaneous expansionary fiscal policy and contractionary monetary policy results in:',
 'Higher income and unambiguously lower interest rates.',
 'Higher interest rates and ambiguous change in income.',
 'Lower interest rates and higher income.',
 'No change in income but higher interest rates.',
 'B',
 'Expansionary fiscal (IS right → higher Y, higher r). Contractionary monetary (LM left → lower Y, higher r). Interest rate RISES unambiguously. Income effect is ambiguous — the two policies have opposing effects on output.'),

('economics', 'ALL',
 'The price elasticity of demand for a good is −2.5. If the price increases by 10%, what happens to total revenue?',
 'Total revenue increases by 25%.',
 'Total revenue decreases.',
 'Total revenue remains unchanged.',
 'Total revenue increases by 10%.',
 'B',
 'Since |PED| = 2.5 > 1, demand is elastic. For elastic goods, a price INCREASE causes a proportionally larger decrease in quantity demanded, so Total Revenue (P × Q) FALLS. TR is unchanged only when |PED| = 1 (unit elastic).'),

('economics', 'ALL',
 'In perfect competition, the long-run equilibrium condition for the representative firm is:',
 'P > MR = MC, with positive economic profit.',
 'P = MR = MC = minimum Average Total Cost (ATC).',
 'P = MC, where P exceeds minimum ATC.',
 'MR = MC, but price is below ATC.',
 'B',
 'In long-run perfect competition, free entry/exit drives economic profit to zero — possible only when P = minimum ATC. Combined with profit maximisation (P = MR = MC in perfect competition), the full condition is P = MR = MC = min ATC.'),

('economics', 'ALL',
 'The Laffer Curve illustrates the relationship between:',
 'Inflation rate and unemployment rate.',
 'Tax rates and total tax revenue collected.',
 'Government spending and GDP growth (multiplier effect).',
 'Interest rates and planned investment.',
 'B',
 'The Laffer Curve shows that tax revenue is zero at both 0% and 100% tax rates, with a maximum in between. Beyond a certain tax rate, raising taxes further REDUCES total revenue — a key supply-side economics argument used to justify tax cuts.'),

('economics', 'ALL',
 'If nominal GDP is ₦50 trillion and the GDP deflator is 125 (base year = 100), what is real GDP?',
 '₦62.5 trillion',
 '₦40 trillion',
 '₦45 trillion',
 '₦37.5 trillion',
 'B',
 'Real GDP = (Nominal GDP / GDP Deflator) × 100 = (50 / 125) × 100 = ₦40 trillion. The GDP deflator removes the effect of price changes, expressing output in base-year prices.'),

-- ═══════════════════════════ GOVERNMENT ═══════════════════════════

('government', 'ALL',
 'The doctrine of judicial review in Nigeria empowers the courts to:',
 'Initiate and enact legislation on constitutional matters.',
 'Declare any law inconsistent with the Constitution null and void.',
 'Remove a sitting President for gross misconduct.',
 'Directly overrule resolutions of the National Assembly.',
 'B',
 'Section 1(3) of Nigeria''s 1999 Constitution establishes constitutional supremacy. Judicial review allows courts (ultimately the Supreme Court) to declare any law or executive action inconsistent with the Constitution null and void ab initio.'),

('government', 'ALL',
 'Under Nigeria''s 1999 Constitution, the Federal Character Principle is primarily enshrined in:',
 'Section 4',
 'Section 14(3) and (4)',
 'Section 153',
 'Section 251',
 'B',
 'Section 14(3) and (4) establishes the Federal Character Principle, requiring that appointments to public offices reflect the federal character of Nigeria. Section 153 establishes the Federal Character Commission to implement it.'),

('government', 'ALL',
 'Montesquieu''s doctrine of separation of powers was primarily designed to:',
 'Ensure efficient administration of the modern state.',
 'Prevent tyranny by distributing power among separate institutions with checks and balances.',
 'Promote democratic elections at regular intervals.',
 'Establish a federal system with autonomous sub-national units.',
 'B',
 'Montesquieu observed that liberty is at risk when the same person/body holds legislative, executive, and judicial power simultaneously. His solution — distributing power among separate institutions — became the foundation of modern constitutional government.'),

('government', 'ALL',
 'In the Westminster parliamentary system, the Prime Minister remains in office primarily as long as they:',
 'Win a general election at least once every five years.',
 'Retain the confidence of the lower house of parliament.',
 'Maintain the personal support of the constitutional monarch.',
 'Command a two-thirds majority in the legislature.',
 'B',
 'The Westminster convention of responsible government requires the executive to maintain the confidence of the elected lower house (e.g. House of Commons). A formal vote of no confidence forces the PM to resign or call elections.'),

('government', 'ALL',
 'The concept of "sovereignty of parliament" in the British constitutional tradition means that:',
 'Parliament can only legislate within limits set by a written constitution.',
 'Parliament can make or unmake any law, and no institution can override an Act of Parliament.',
 'The monarch holds supreme legal authority as head of parliament.',
 'Parliament shares supreme authority equally with the judiciary.',
 'B',
 'A.V. Dicey articulated parliamentary sovereignty as the cornerstone of the UK constitution: Parliament can make any law; courts cannot question the validity of an Act of Parliament; and no Parliament can bind its successors. This differs from constitutional supremacy found in Nigeria.'),

-- ═══════════════════════════ LITERATURE ═══════════════════════════

('literature', 'ALL',
 'The narrative technique "stream of consciousness" — depicting a character''s unfiltered thoughts as they occur — is most associated with:',
 'Chinua Achebe',
 'James Joyce',
 'Wole Soyinka',
 'D.H. Lawrence',
 'B',
 '"Ulysses" (1922) by James Joyce is the defining example of stream of consciousness. Virginia Woolf also used it extensively. The technique renders the continuous flow of thoughts and perceptions of a character''s mind without conventional narrative structure.'),

('literature', 'ALL',
 'In Wole Soyinka''s "Death and the King''s Horseman," the central dramatic conflict arises primarily from:',
 'A political struggle between two colonial administrators.',
 'The clash between Yoruba ritual obligation and colonial interference.',
 'A love triangle involving Elesin, his new bride, and Iyaloja.',
 'Economic exploitation of the Oyo kingdom by British merchants.',
 'B',
 'Soyinka described the play as being about the failure of Elesin''s will. Structurally, the conflict is between Elesin''s sacred duty to follow his king in death (Yoruba metaphysical obligation) and Pilkings'' colonial intervention — a "clash of two worlds."'),

('literature', 'ALL',
 'In T.S. Eliot''s "The Waste Land" (1922), the dominant technique that shaped literary modernism is:',
 'Stream-of-consciousness first-person narration.',
 'Extensive allusion and deliberate fragmentation of form.',
 'Romantic lyricism celebrating nature and individual emotion.',
 'Naturalist description of urban industrial conditions.',
 'B',
 '"The Waste Land" is characterised by fragmented structure, multiple voices, dense literary and mythological allusions (Dante, Shakespeare, Upanishads), and juxtaposition of past grandeur with post-WWI emptiness. This fragmentation became the defining feature of high literary modernism.'),

('literature', 'ALL',
 'Aristotle''s concept of "catharsis" in the Poetics refers to:',
 'The moment of highest tension (climax) in a tragic drama.',
 'The emotional purgation or purification experienced by the audience through pity and fear.',
 'The tragic flaw (hamartia) that causes the protagonist''s downfall.',
 'The resolution (denouement) that restores order after the tragedy.',
 'B',
 'Aristotle defined tragedy as achieving catharsis — a purging or clarification of pity (eleos) and fear (phobos) in the audience. Scholars debate whether it means purgation (release) or clarification (intellectual understanding). Hamartia is option C''s concept.'),

('literature', 'ALL',
 'In Chinua Achebe''s "Arrow of God," the narrative mode where the narrator''s language blends with a character''s thoughts without explicit attribution is:',
 'First-person unreliable narration.',
 'Free indirect discourse (style indirect libre).',
 'Omniscient third-person narration.',
 'Second-person experimental narration.',
 'B',
 'Free indirect discourse allows a third-person narrator to inhabit a character''s consciousness — the narrator''s voice and the character''s thoughts merge seamlessly. Achebe uses this masterfully in "Arrow of God" to render Ezeulu''s worldview from the inside while maintaining narrative distance.'),

-- ═══════════════════════════ COMMERCE ═══════════════════════════

('commerce', 'ALL',
 'A Bill of Lading in international trade serves all the following functions EXCEPT:',
 'A receipt for goods shipped by the carrier.',
 'A certificate of marine insurance covering the goods.',
 'A document of title allowing the holder to claim the goods.',
 'Evidence of the contract of carriage between shipper and carrier.',
 'B',
 'A Bill of Lading: (1) acts as receipt for goods, (2) is a document of title (negotiable), and (3) evidences the contract of carriage. It does NOT function as insurance — that is the Marine Insurance Certificate, a separate document issued by the insurer.'),

('commerce', 'ALL',
 'Under the insurance principle of subrogation, which description is correct?',
 'The insurer may charge a higher premium after a claim is made.',
 'After paying the insured''s claim, the insurer acquires the insured''s right to recover from the liable third party.',
 'The insured may claim from several insurers for the same loss.',
 'The insurance policy may be transferred to another person without the insurer''s consent.',
 'B',
 'Subrogation prevents the insured from profiting from a loss. After the insurer pays compensation, it acquires the insured''s legal right to sue the negligent third party. This enforces the principle of indemnity and allows insurers to recoup payments.'),

('commerce', 'ALL',
 'A country''s terms of trade improve when:',
 'The volume of exports increases relative to imports.',
 'Export prices rise relative to import prices — each unit of export buys more imports.',
 'Its balance of trade deficit narrows due to import substitution.',
 'The exchange rate depreciates, making exports cheaper.',
 'B',
 'Terms of Trade (ToT) = (Index of Export Prices / Index of Import Prices) × 100. An improvement means ToT rises — each unit of export fetches more imports. This is distinct from trade volume or balance. A depreciation typically WORSENS ToT by raising import prices.'),

('commerce', 'ALL',
 'In a hire purchase agreement, legal ownership (title) of the goods passes to the buyer:',
 'Immediately upon signing the hire purchase agreement.',
 'After payment of the first instalment.',
 'Only after the final instalment is paid and the option to purchase is exercised.',
 'Upon taking physical possession of the goods.',
 'C',
 'Hire purchase is legally a bailment with an option to purchase. The hirer only RENTS the goods during the repayment period. Title passes only when ALL instalments are paid and the option to purchase is exercised — protecting the seller''s ownership if the hirer defaults.'),

('commerce', 'ALL',
 'A debenture holder in a limited liability company is best described as:',
 'A part-owner of the company with voting rights at the AGM.',
 'A creditor of the company entitled to fixed interest payments, repayable before shareholders.',
 'A preference shareholder with priority over ordinary dividends.',
 'A beneficial owner with residual claims on company assets.',
 'B',
 'Debentures are long-term debt instruments. Debenture holders are CREDITORS, not owners — no voting rights. They receive fixed interest (a charge on profits, payable even without profit) and are repaid before any shareholder in liquidation — safer but with no equity upside.'),

-- ═══════════════════════════ ACCOUNTING ═══════════════════════════

('accounting', 'ALL',
 'Under the double-entry system, the purchase of machinery worth ₦500,000 on credit is recorded as:',
 'Debit Bank ₦500,000; Credit Machinery ₦500,000.',
 'Debit Machinery ₦500,000; Credit Accounts Payable ₦500,000.',
 'Debit Accounts Payable ₦500,000; Credit Machinery ₦500,000.',
 'Debit Purchases ₦500,000; Credit Bank ₦500,000.',
 'B',
 'Assets increase → Debit. Liabilities increase → Credit. Buying machinery on credit increases a fixed asset (Debit Machinery) and creates a liability to the supplier (Credit Accounts Payable/Creditors). Option A applies only when paid by cash.'),

('accounting', 'ALL',
 'A firm has a Current Ratio of 3:1 and a Quick Ratio of 1.5:1. If Current Liabilities are ₦400,000, what is the value of inventory?',
 '₦200,000',
 '₦400,000',
 '₦600,000',
 '₦800,000',
 'C',
 'Current Assets = 3 × ₦400,000 = ₦1,200,000. Quick Assets (Current Assets − Inventory) = 1.5 × ₦400,000 = ₦600,000. Therefore Inventory = ₦1,200,000 − ₦600,000 = ₦600,000.'),

('accounting', 'ALL',
 'The primary purpose of charging depreciation on fixed assets in financial accounting is to:',
 'Build up a cash fund to replace the asset at the end of its life.',
 'Allocate the cost of the asset systematically against revenue over its useful economic life (matching principle).',
 'Reflect the current market value of the asset in the balance sheet.',
 'Reduce the taxable profit of the business to minimise tax liability.',
 'B',
 'Depreciation applies the matching concept: the cost of a fixed asset generating revenue over several years is matched against that revenue over the same period. It is a non-cash charge — it does NOT create a cash fund, nor does it necessarily reflect market value.'),

('accounting', 'ALL',
 'In partnership accounts, interest on partners'' drawings is treated as:',
 'An expense in the Profit & Loss Account, reducing net profit.',
 'A credit in the Profit & Loss Appropriation Account, increasing profit available for distribution.',
 'A debit to the partners'' Capital Accounts only.',
 'A reduction in partners'' drawings with no effect on profit.',
 'B',
 'Interest on drawings is charged TO partners (penalising excessive drawings) and credited to the P&L Appropriation Account, increasing divisible profit. Journal entry: Debit Partners'' Current Accounts; Credit P&L Appropriation Account.'),

('accounting', 'ALL',
 'Gross profit is ₦500,000 on sales of ₦2,000,000 (COGS = ₦1,500,000). With average inventory of ₦300,000, the Gross Profit Margin and Inventory Turnover are respectively:',
 '25% and 5 times',
 '25% and 6.67 times',
 '33.3% and 5 times',
 '20% and 4 times',
 'A',
 'Gross Profit Margin = (₦500,000 / ₦2,000,000) × 100 = 25%. Inventory Turnover = COGS / Average Inventory = ₦1,500,000 / ₦300,000 = 5 times. Note: Inventory Turnover uses COGS, not sales revenue.'),

-- ═══════════════════════════ GEOGRAPHY ═══════════════════════════

('geography', 'ALL',
 'The "rain shadow" effect causes aridity on the leeward side of a mountain because:',
 'Air descends on the leeward side, warms adiabatically, and its relative humidity decreases.',
 'Cold ocean currents on the leeward coast suppress convectional rainfall.',
 'Trade winds lose all their moisture before reaching the leeward side.',
 'Urban heat islands on the leeward side prevent cloud formation.',
 'A',
 'Moist air rises over the windward slope, cools at the SALR, and orographic rainfall occurs. On the leeward side, the now-dry air descends and warms at the steeper DALR (9.8°C/km), resulting in warm, dry conditions — the rain shadow effect.'),

('geography', 'ALL',
 'The theory of continental drift — proposing that continents were once joined in a single landmass (Pangaea) — was first comprehensively proposed by:',
 'Charles Darwin',
 'Alfred Wegener',
 'James Hutton',
 'Harry Hess',
 'B',
 'Alfred Wegener published "The Origin of Continents and Oceans" (1915), presenting evidence: the fit of coastlines, matching fossil records (e.g. Glossopteris across Africa, South America, India), and identical rock formations. Harry Hess later provided the mechanism (seafloor spreading, 1962).'),

('geography', 'ALL',
 'A location classified as Csa in the Köppen climate classification experiences:',
 'Hot, humid summers and cold, snowy winters (humid continental).',
 'Hot, dry summers and mild, wet winters (Mediterranean).',
 'Warm, rainy summers and cool, dry winters (monsoon).',
 'Hot, wet summers and hot, dry winters (savanna).',
 'B',
 'In Köppen classification: C = temperate; s = dry summer; a = hottest month > 22°C. Csa is the Hot-Summer Mediterranean climate — found around the Mediterranean Sea, California, South Africa''s Cape region, and SW Australia.'),

('geography', 'ALL',
 'A subduction zone at a convergent tectonic plate boundary is characterised by:',
 'Two plates moving apart, allowing magma to rise and create new oceanic crust.',
 'A denser oceanic plate descending beneath a less dense plate, generating earthquakes and volcanic arcs.',
 'Two continental plates colliding horizontally to form fold mountain ranges.',
 'Plates sliding horizontally past each other along a transform fault.',
 'B',
 'At convergent boundaries where oceanic crust meets another plate, the denser oceanic plate subducts (descends) into the mantle. This produces deep-focus earthquakes, ocean trenches (e.g. Mariana Trench), and volcanic island arcs or coastal chains (e.g. Andes, Ring of Fire).'),

('geography', 'ALL',
 'In a Geographic Information System (GIS), a raster data model represents spatial information as:',
 'Lines and polygons defined by precise x,y coordinate pairs.',
 'A regular grid of cells (pixels), each assigned a single attribute value.',
 'Point locations linked to attribute tables in a relational database.',
 'Three-dimensional surface models built from elevation contours.',
 'B',
 'Raster GIS data divides space into a regular grid; each cell stores one value (e.g. elevation, temperature, land use). Satellite imagery and DEMs are raster. The alternative vector model uses points, lines, and polygons. Rasters suit continuous phenomena; vectors suit discrete features.'),

-- ═══════════════════════════ HISTORY ═══════════════════════════

('history', 'ALL',
 'The Berlin Conference of 1884–1885 was convened primarily to:',
 'Abolish the transatlantic slave trade through multinational agreement.',
 'Regulate European colonisation and trade in Africa, establishing rules for claiming territory.',
 'Create the League of Nations mandate system for African territories.',
 'Resolve the Anglo-French dispute over control of the Suez Canal.',
 'B',
 'Convened by Bismarck, the Berlin Conference set rules for the Scramble for Africa. The "principle of effective occupation" — requiring powers to demonstrate actual presence and control — accelerated partition. By 1914, only Ethiopia and Liberia remained independent.'),

('history', 'ALL',
 'The policy of Indirect Rule as systematically applied by the British in Northern Nigeria was most associated with:',
 'Frederick Lugard',
 'Cecil Rhodes',
 'Herbert Macaulay',
 'Nnamdi Azikiwe',
 'A',
 'Lord Frederick Lugard (Governor-General of Nigeria 1914–1919) codified and popularised indirect rule, governing through existing traditional rulers (emirs in the North). He outlined this in "The Dual Mandate in British Tropical Africa" (1922). Rhodes was associated with Southern Africa.'),

('history', 'ALL',
 'The Negritude literary and political movement — asserting the value of African cultural identity — was primarily founded by:',
 'Marcus Garvey and the Universal Negro Improvement Association.',
 'Léopold Sédar Senghor of Senegal and Aimé Césaire of Martinique.',
 'W.E.B. Du Bois and Booker T. Washington.',
 'Kwame Nkrumah and Julius Nyerere.',
 'B',
 'Negritude emerged in 1930s Paris among French-speaking African and Caribbean intellectuals. Senghor (later Senegal''s first president) and Césaire (poet and politician from Martinique) are its founders — celebrating African values as a counter to French assimilation policy and colonial racism.'),

('history', 'ALL',
 'The Magna Carta of 1215 is historically significant primarily because it:',
 'Established universal male suffrage and the right to vote in England.',
 'Placed limits on royal power and established that the king is subject to the law.',
 'Created the English Parliament as a permanent legislative institution.',
 'Abolished the feudal system and serfdom throughout England.',
 'B',
 'King John was forced by barons to sign Magna Carta ("Great Charter"), limiting arbitrary royal power. Key clauses protected against unlawful imprisonment (habeas corpus principle) and required due process. Parliament was formalised later in 1265 under Simon de Montfort.'),

('history', 'ALL',
 'Which best describes the significance of the Jihad led by Usman dan Fodio (1804–1808)?',
 'It created a unified pan-African state spanning all of West Africa.',
 'It established the Sokoto Caliphate — the largest pre-colonial state in sub-Saharan Africa — governed on Islamic principles.',
 'It overthrew British colonial administration in Northern Nigeria.',
 'It ended trans-Saharan trade routes and isolated Northern Nigeria from North Africa.',
 'B',
 'Usman dan Fodio''s jihad against the Hausa kings established the Sokoto Caliphate by 1809 — a theocratic state governed by Sharia, encompassing much of modern Northern Nigeria and beyond. At its peak it was among the largest states in Africa, with emirates governed by appointed flag-bearers (emirs).'),

-- ═══════════════════════════ AGRICULTURAL SCIENCE ═══════════════════════════

('agric', 'ALL',
 'The Cation Exchange Capacity (CEC) of a soil measures:',
 'The soil''s ability to retain and release water for plant uptake.',
 'The total quantity of positively charged ions (cations) the soil can hold and exchange.',
 'The rate at which soluble nutrients leach below the root zone.',
 'The percentage of organic matter contributing to soil fertility.',
 'B',
 'CEC (measured in cmol+/kg) indicates how well soil retains plant nutrients like Ca²⁺, Mg²⁺, K⁺. Clay and organic matter have high CEC. High-CEC soils are more fertile as they hold more nutrients against leaching. Sandy soils have very low CEC.'),

('agric', 'ALL',
 'When two alleles of a gene are BOTH fully expressed in the heterozygote (e.g. AB blood group where both A and B antigens are present), this pattern of inheritance is called:',
 'Incomplete dominance',
 'Codominance',
 'Epistasis',
 'Pleiotropy',
 'B',
 'Codominance: both alleles are fully and simultaneously expressed (e.g. ABO blood group AB). This differs from incomplete dominance, where the heterozygote shows an intermediate blended phenotype (e.g. red × white = pink in snapdragons). Epistasis is gene-gene interaction; pleiotropy is one gene affecting multiple traits.'),

('agric', 'ALL',
 'The practice of contour farming (ploughing and planting along contour lines perpendicular to the slope) is primarily designed to:',
 'Increase soil organic matter through accelerated decomposition.',
 'Reduce surface runoff velocity and minimise soil erosion on slopes.',
 'Improve soil aeration and internal drainage.',
 'Enhance atmospheric nitrogen fixation by leguminous crops.',
 'B',
 'Contour farming creates ridges and furrows that run across the slope, slowing water flow, increasing infiltration time, and trapping eroding soil particles. It is one of the most effective mechanical soil conservation practices, reducing erosion by up to 50% on sloping land.'),

('agric', 'ALL',
 'The primary route of transmission of Rinderpest (cattle plague, caused by Morbillivirus) is:',
 'Tick vectors transmitting the virus through blood-sucking.',
 'Direct contact with infected animals and inhalation of respiratory secretions or droplets.',
 'Contaminated soil harbouring the virus for extended periods.',
 'Tsetse fly vectors carrying the pathogen between animals.',
 'B',
 'Rinderpest spread primarily via direct contact and aerosol transmission of respiratory secretions. It was highly contagious with catastrophic mortality in cattle. The disease was globally eradicated in 2011 — only the second animal disease ever eradicated, after Smallpox in humans.'),

('agric', 'ALL',
 'The optimum soil pH range for most common agricultural crops is approximately:',
 '4.0 – 5.0 (strongly acid)',
 '5.5 – 7.0 (slightly acid to neutral)',
 '7.5 – 8.5 (moderately alkaline)',
 '8.0 – 9.5 (strongly alkaline)',
 'B',
 'Most crops grow best at pH 5.5–7.0 because: nutrient availability (N, P, K, Ca, Mg) is highest; beneficial soil microorganisms are most active; and toxic elements (Al³⁺, Mn²⁺) are least soluble. Below pH 5.5, aluminium toxicity inhibits root growth. Above pH 7.5, micronutrients (Fe, Mn, Zn) become unavailable.'),

-- ═══════════════════════════ FURTHER MATHEMATICS ═══════════════════════════

('further_maths', 'ALL',
 'The complex number (1 + i)⁸ evaluates to:',
 '16',
 '−16',
 '16i',
 '−16i',
 'A',
 '(1+i)² = 2i. (1+i)⁴ = (2i)² = 4i² = −4. (1+i)⁸ = (−4)² = 16. Alternative: |1+i|=√2, arg=π/4; (1+i)⁸ = (√2)⁸·e^(i·8·π/4) = 16·e^(i·2π) = 16·1 = 16.'),

('further_maths', 'ALL',
 'For 2×2 matrices A and B, if det(A) = −2 and det(B) = −2, then det(AB) equals:',
 '−2',
 '4',
 '8',
 '−4',
 'B',
 'Determinant product rule: det(AB) = det(A) × det(B) for square matrices of the same order. Therefore det(AB) = (−2) × (−2) = 4. This rule holds for any n×n matrices.'),

('further_maths', 'ALL',
 'The particular solution of dy/dx = y/x, given y = 2 when x = 1, is:',
 'y = x²',
 'y = 2x',
 'y = eˣ',
 'y = 2eˣ⁻¹',
 'B',
 'Separating variables: dy/y = dx/x → ln|y| = ln|x| + C → y = Ax. Applying the initial condition y(1) = 2: 2 = A(1) → A = 2. Particular solution: y = 2x.'),

('further_maths', 'ALL',
 'The variance of the data set {2, 4, 4, 4, 5, 5, 7, 9} is:',
 '2',
 '4',
 '5',
 '3',
 'B',
 'Mean μ = 40/8 = 5. Σ(x−μ)² = (−3)²+(−1)²+(−1)²+(−1)²+0²+0²+2²+4² = 9+1+1+1+0+0+4+16 = 32. Variance = 32/8 = 4. Standard deviation = 2.'),

('further_maths', 'ALL',
 'The scalar (dot) product of vectors a = (3, 4, 0) and b = (1, −1, 2) is:',
 '−1',
 '7',
 '1',
 '5',
 'A',
 'a·b = (3)(1) + (4)(−1) + (0)(2) = 3 − 4 + 0 = −1. Since a·b < 0, the angle between the vectors is obtuse (> 90°). |a| = 5, |b| = √6, so cos θ = −1/(5√6).'),

-- ═══════════════════════════ ISLAMIC RELIGIOUS STUDIES ═══════════════════════════

('irs', 'ALL',
 'In Islamic jurisprudence (Usul al-Fiqh), "Qiyas" refers to:',
 'The consensus of Islamic scholars on a legal ruling.',
 'Analogical reasoning — extending a ruling from a Quranic/Hadith precedent to a new case sharing the same underlying cause (Illah).',
 'Independent juristic reasoning by a qualified scholar without textual analogy.',
 'A ruling derived directly and exclusively from the Quran.',
 'B',
 'Qiyas (analogy) is the 4th source of Islamic law after Quran, Sunnah, and Ijma. A scholar identifies the operative cause (Illah) of an existing ruling and extends it to a new case with the same cause. Example: Khamr (wine) is forbidden for intoxication; by Qiyas, all intoxicants are forbidden.'),

('irs', 'ALL',
 'Which of the following is NOT one of the three classical categories of Tawhid (Oneness of Allah)?',
 'Tawhid al-Rububiyyah (Oneness of Lordship)',
 'Tawhid al-Uluhiyyah (Oneness of Worship)',
 'Tawhid al-Asma wa''l-Sifat (Oneness of Allah''s Names and Attributes)',
 'Tawhid al-Nubuwwah (Oneness of Prophethood)',
 'D',
 'Classical Islamic theology divides Tawhid into three: Rububiyyah (Allah alone is Creator/Sustainer), Uluhiyyah (worship directed to Allah alone, negating shirk), and Asma wa''l-Sifat (affirming Allah''s names and attributes without likening them to creation). Nubuwwah (prophethood) is a separate doctrine (Risalah).'),

('irs', 'ALL',
 'The categories of human actions in Islamic law (Al-Ahkam al-Khamsah) include all EXCEPT:',
 'Wajib (obligatory) — must be done; omission is sinful.',
 'Mubah (permissible/neutral) — no reward or sin attached.',
 'Bid''ah (blameworthy innovation) — a later-introduced practice.',
 'Makruh (discouraged) — omission is rewarded; commission is not sinful.',
 'C',
 'The five Islamic legal categories (Ahkam) are: Wajib/Fard (obligatory), Mandub/Mustahabb (recommended), Mubah (permissible), Makruh (discouraged), and Haram (forbidden). Bid''ah (innovation) is a separate evaluative concept for newly-introduced religious practices — not one of the five Ahkam.'),

('irs', 'ALL',
 'The Battle of Badr (2 AH / 624 CE) was a turning point in early Islamic history primarily because:',
 'It marked the year of the first revelation of the Quran to Prophet Muhammad.',
 'It was the first major military victory of the Muslim community, consolidating the authority of the Islamic state in Medina.',
 'It directly caused the Hijra (migration) of Muslims from Mecca to Medina.',
 'It established the Islamic (Hijri) calendar used by Muslims worldwide.',
 'B',
 'The Battle of Badr — 313 ill-equipped Muslims defeated a Quraysh force of ~1,000 — was Islam''s first major military victory. It boosted Muslim morale, demonstrated divine support, exposed internal hypocrites, and firmly established Muhammad''s political authority. Surah Al-Anfal (Ch. 8) discusses it in detail.'),

('irs', 'ALL',
 'In the science of Hadith, "Isnad" refers to:',
 'The actual text or content of a Hadith report (the statement or action described).',
 'The unbroken chain of transmitters through whom a Hadith is reported back to the Prophet.',
 'A Hadith authenticated by all four major Sunni schools of law.',
 'A Hadith reported by only a single narrator at any point in its transmission chain.',
 'B',
 'Every Hadith consists of: Isnad (chain of transmission — the sequence of narrators) and Matn (the actual text/content). Hadith scholars (Muhaddithin) evaluate authenticity primarily by analysing the Isnad — the character (Adalah) and memory precision (Dabt) of each narrator, and continuity of the chain.'),

-- ═══════════════════════════ CHRISTIAN RELIGIOUS STUDIES ═══════════════════════════

('crs', 'ALL',
 'The theological concept of theosis or "divinization" — the process by which humans participate in the divine nature — is most central to:',
 'Roman Catholicism',
 'Eastern Orthodoxy',
 'Calvinist Protestantism',
 'Pentecostalism',
 'B',
 'Theosis (Greek: θέωσις) is the central soteriological concept of Eastern Orthodox theology, summarised by Athanasius: "God became man so that man might become God." It refers to communion with God''s uncreated energies (Palamism). While Catholics acknowledge it, it is largely absent from Calvinist soteriology.'),

('crs', 'ALL',
 'The Council of Nicaea (325 CE) was convened primarily to resolve the controversy raised by Arius, who taught that:',
 'The New Testament canon should include the Gospel of Thomas.',
 'The Son (Christ) was a created being — not co-eternal with the Father ("there was a time when He was not").',
 'The Holy Spirit proceeds from both the Father AND the Son (Filioque).',
 'The bishop of Rome held supreme authority over all other bishops.',
 'B',
 'Arius taught that Christ was the Father''s highest creation, not co-eternal or co-equal. The Council condemned Arianism and produced the Nicene Creed affirming Christ as "of the same substance" (homoousios) as the Father. The Filioque dispute came later (867 CE); Roman primacy was addressed at other councils.'),

('crs', 'ALL',
 'The hermeneutical principle known as "sensus plenior" (fuller sense) refers to:',
 'The strictly literal meaning of a biblical text as the human author intended.',
 'A deeper spiritual meaning in Scripture intended by God that goes beyond what the human author consciously understood.',
 'The moral or ethical application of biblical texts to contemporary Christian life.',
 'The allegorical interpretation method used exclusively for Old Testament prophecy.',
 'B',
 '"Sensus plenior" (Raymond Brown, 1955) refers to the additional, deeper meaning intended by God but not fully grasped by the human author — often seen in OT texts understood as messianic prophecy only in light of Christ. It differs from allegory (ignores literal sense) and typology (focuses on historical correspondences).'),

('crs', 'ALL',
 'The doctrine of justification by faith alone (sola fide) is most systematically developed in:',
 'The Gospel of John',
 'The Epistle to the Romans',
 'The Book of Revelation',
 'The Acts of the Apostles',
 'B',
 'Romans (especially chapters 1–5) is Paul''s fullest exposition of justification: "a person is justified by faith apart from the works of the law" (Romans 3:28). Luther''s rediscovery of this text sparked the Reformation. Galatians also develops the theme, but Romans is the systematic treatment.'),

('crs', 'ALL',
 'The "Deuterocanonical" books (called Apocrypha by Protestants — e.g. Tobit, Maccabees, Sirach) are accepted as canonical Scripture by:',
 'All Protestant denominations as part of the standard biblical canon.',
 'Roman Catholic and Eastern Orthodox churches, but not by most Protestant denominations.',
 'Seventh-day Adventists and Jehovah''s Witnesses only.',
 'All Christian denominations globally without dispute.',
 'B',
 'The deuterocanonicals were part of the Septuagint (LXX) used by early Christians. The Council of Trent (1546) formally defined them as canonical for Catholics. Orthodox churches accept them (and additional texts). The Protestant Reformation rejected them, following the Hebrew canon, so most Protestant Bibles omit them.'),

-- ═══════════════════════════ APTITUDE TEST ═══════════════════════════

('aptitude', 'ALL',
 'A sequence follows the pattern: 2, 6, 18, 54, ___. What is the next term?',
 '108',
 '162',
 '216',
 '144',
 'B',
 'Each term is multiplied by 3: 2×3=6, 6×3=18, 18×3=54, 54×3=162. This is a geometric sequence with first term a=2 and common ratio r=3.'),

('aptitude', 'ALL',
 'If FRIEND is coded as HUMJTK (each letter shifted by incrementally increasing values: +2, +3, +4, +5, +6, +7), then ENEMY is coded as:',
 'GQIRE',
 'GRIQE',
 'FQIRE',
 'GQIRF',
 'A',
 'Apply shifts (+2, +3, +4, +5, +6) to each letter of ENEMY: E+2=G, N+3=Q, E+4=I, M+5=R, Y+6=E. Therefore ENEMY → GQIRE.'),

('aptitude', 'ALL',
 'A train 200 m long passes a stationary pole in 10 seconds. How long will it take to pass a platform 300 m long at the same speed?',
 '20 seconds',
 '25 seconds',
 '30 seconds',
 '15 seconds',
 'B',
 'Speed = 200/10 = 20 m/s. To pass the platform, the train must cover its own length plus the platform length = 200+300 = 500 m. Time = 500/20 = 25 seconds.'),

('aptitude', 'ALL',
 'In a class of 50 students, 30 study Mathematics, 25 study Physics, and 10 study both subjects. How many students study NEITHER?',
 '5',
 '10',
 '15',
 '0',
 'A',
 'By inclusion-exclusion: n(M∪P) = n(M) + n(P) − n(M∩P) = 30+25−10 = 45. Students studying neither = Total − n(M∪P) = 50−45 = 5.'),

('aptitude', 'ALL',
 'A man walks 3 km North, then 4 km East. What is his straight-line distance from his starting point?',
 '5 km',
 '7 km',
 '6 km',
 '3.5 km',
 'A',
 'The path forms a right-angled triangle with legs 3 km and 4 km. By Pythagoras'' theorem: d = √(3²+4²) = √(9+16) = √25 = 5 km. This is the classic 3-4-5 Pythagorean triple.');
